### ISSUE TITLE
Azure.Messaging.ServiceBus: The lock supplied is invalid

### ISSUE THREAD

**Issue by cosminstirbu** [Azure/azure-functions-dotnet-worker#1003]
Hello,

It seems that if a Service Bus trigger function throws an exception, even after the function has finished executing, I'm seeing a `Azure.Messaging.ServiceBus: The lock supplied is invalid` exception in the console.

Any reasons why the function attempts to renew the lock token after it failed executing? This adds noise to our Application Insights logs.

```
[2022-08-23T12:34:03.472Z] Worker process started and initialized.
[2022-08-23T12:34:38.603Z] Executing 'Functions.MyFunctionFunction' (Reason='(null)', Id=6ebb7300-380c-461d-9429-85ef76066dce)
[2022-08-23T12:34:38.605Z] Trigger Details: MessageId: 5e4e10d7bbbf418f8170c0261f208e42, SequenceNumber: 13, DeliveryCount: 1, EnqueuedTimeUtc: 2022-08-23T12:34:38.3280000+00:00, LockedUntilUtc: 2022-08-23T12:35:08.3440000+00:00, SessionId: (null)
[2022-08-23T12:34:38.800Z] Configured endpoint MyFunction, Consumer: MyCompany.MyAppIntegration.MyFunction.Function.MassTransitConsumers.MyFunctionConsumer
[2022-08-23T12:34:39.793Z] Executed 'Functions.MyFunctionFunction' (Failed, Id=6ebb7300-380c-461d-9429-85ef76066dce, Duration=1214ms)
[2022-08-23T12:34:39.794Z] System.Private.CoreLib: Exception while executing function: Functions.MyFunctionFunction. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (The method or operation is not implemented.)
[2022-08-23T12:34:39.795Z]  ---> System.NotImplementedException: The method or operation is not implemented.
[2022-08-23T12:34:39.796Z]    at MyCompany.MyAppIntegration.MyFunction.Function.MyFunctionFunction.Run(Byte[] message, FunctionContext context) in C:\Repos\MyCompany\MyApp\src\MyCompany.MyAppIntegration.MyFunction.Function\MyFunctionFunction.cs:line 21
[2022-08-23T12:34:39.798Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 22
[2022-08-23T12:34:39.799Z]    --- End of inner exception stack trace ---
[2022-08-23T12:34:39.801Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2022-08-23T12:34:39.802Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2022-08-23T12:34:39.807Z]    at System.Threading.Tasks.Task`1.get_Result()
[2022-08-23T12:34:39.809Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2022-08-23T12:34:39.810Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2022-08-23T12:34:39.812Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-08-23T12:34:39.813Z] --- End of stack trace from previous location ---
[2022-08-23T12:34:39.814Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2022-08-23T12:34:39.816Z] --- End of stack trace from previous location ---
[2022-08-23T12:34:39.817Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2022-08-23T12:34:39.823Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2022-08-23T12:34:39.824Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 199
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2022-08-23T12:34:39.827Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2022-08-23T12:34:39.828Z]    at System.Threading.Tasks.Task`1.get_Result()
[2022-08-23T12:34:39.830Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2022-08-23T12:34:39.832Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2022-08-23T12:34:39.833Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-08-23T12:34:39.839Z] --- End of stack trace from previous location ---
[2022-08-23T12:34:39.840Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2022-08-23T12:34:39.842Z] --- End of stack trace from previous location ---
[2022-08-23T12:34:39.844Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2022-08-23T12:34:39.845Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2022-08-23T12:34:39.847Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 199.
[2022-08-23T12:34:39.913Z] Message processing error (Action=ProcessMessageCallback, EntityPath=test-cosmin, Endpoint=myapp-dev-sbn.servicebus.windows.net)
[2022-08-23T12:34:39.917Z] System.Private.CoreLib: Exception while executing function: Functions.MyFunctionFunction. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (The method or operation is not implemented.)
[2022-08-23T12:34:39.919Z]  ---> System.NotImplementedException: The method or operation is not implemented.
[2022-08-23T12:34:39.923Z]    at MyCompany.MyAppIntegration.MyFunction.Function.MyFunctionFunction.Run(Byte[] message, FunctionContext context) in C:\Repos\MyCompany\MyApp\src\MyCompany.MyAppIntegration.MyFunction.Function\MyFunctionFunction.cs:line 21
[2022-08-23T12:34:39.926Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 22
[2022-08-23T12:34:39.928Z]    --- End of inner exception stack trace ---
[2022-08-23T12:34:39.933Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2022-08-23T12:34:39.939Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2022-08-23T12:34:39.941Z]    at System.Threading.Tasks.Task`1.get_Result()
[2022-08-23T12:34:39.943Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2022-08-23T12:34:39.946Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2022-08-23T12:34:39.947Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-08-23T12:34:39.949Z] --- End of stack trace from previous location ---
[2022-08-23T12:34:39.954Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2022-08-23T12:34:39.956Z] --- End of stack trace from previous location ---
[2022-08-23T12:34:39.958Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2022-08-23T12:34:39.960Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2022-08-23T12:34:39.962Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 199
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2022-08-23T12:34:39.965Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2022-08-23T12:34:39.971Z]    at System.Threading.Tasks.Task`1.get_Result()
[2022-08-23T12:34:39.972Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2022-08-23T12:34:39.974Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2022-08-23T12:34:39.976Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-08-23T12:34:39.978Z] --- End of stack trace from previous location ---
[2022-08-23T12:34:39.979Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2022-08-23T12:34:39.980Z] --- End of stack trace from previous location ---
[2022-08-23T12:34:39.986Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2022-08-23T12:34:39.988Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2022-08-23T12:34:39.992Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 199.
[2022-08-23T12:34:59.014Z] Message processing error (Action=RenewLock, EntityPath=test-cosmin, Endpoint=myapp-dev-sbn.servicebus.windows.net)
[2022-08-23T12:34:59.017Z] Azure.Messaging.ServiceBus: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:171c39c8-917c-4c3b-b435-5e7460e2a38a, TrackingId:7917be18-7e2f-4eaf-907c-4f46f487adb9_B23, SystemTracker:myapp-dev-sbn:Queue:test-cosmin, Timestamp:2022-08-23T12:34:58 (MessageLockLost).
```

As you can see in the logs above `Azure.Messaging.ServiceBus: The lock supplied is invalid` is logged 20 seconds after the last log message, this is rather unexpected as I don't understand why the runtime attempts to renew the lock of a failed execution which lead to a dead-lettered message.

**Comment by brettsam** [comment]
We'll see if we can repro this; it may be an issue in the ServiceBus extension itself, rather than the worker.

**Comment by EmilDamian** [comment]
The same issue here, consumption finished on 7 ms with succes (auto), but lock expired after 12 seconds.

**Comment by tapasudenia** [comment]
We are migrating to Azure.Messaging.ServiceBus from Microsoft.Azure.ServiceBus using the guide [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md)

However, I have experienced the same error happening, when we are trying to `_serviceBusReceiver.CompleteMessageAsync(serviceBusReceivedMessage);`. 

Things already tried.
 - Set the `ServiceBusSessionReceiverOptions ` explicitly.
 - Tried using `await receiver.ReceiveMessageAsync();` instead of `await processor.StartProcessingAsync();` to start message processing. However, the later one didn't work / receive message at all. 
 - Tried changing MaxAutoLockRenewalDuration to different values, but the message gets processed within few minutes, so it should complete the lock
 
We want to complete the message in all the scenarios whether it fails or it doesn't fail, thats why we have the CompleteMessageAsync in the `finally` block.

Please suggest

**Sample Code:**
```
private async Task Subscribe()
{
  try
  {
      var serviceBusConnectionString = $"some-valid-connection-string";
      var _serviceBusClient = new ServiceBusClient(serviceBusConnectionString);

      var receiverOptions = new ServiceBusReceiverOptions
      {
          ReceiveMode = ServiceBusReceiveMode.PeekLock,
          
      };
      _serviceBusReceiver = _serviceBusClient.CreateReceiver("some-valid-queue-name", receiverOptions);
      var options = new ServiceBusProcessorOptions
      {
          MaxAutoLockRenewalDuration = TimeSpan.FromMinutes(60),
          AutoCompleteMessages = false,
          MaxConcurrentCalls = 10,  
          ReceiveMode = ServiceBusReceiveMode.PeekLock
      };

      // create a processor that we can use to process the messages
      _serviceBusProcessor = _serviceBusClient.CreateProcessor("some-valid-queue-name", options);
      _serviceBusProcessor.ProcessErrorAsync += Processor_ProcessErrorAsync;
      _serviceBusProcessor.ProcessMessageAsync += Processor_ProcessMessageAsync;

      await _serviceBusProcessor.StartProcessingAsync();
  }
  catch (Exception ex)
  {
      _logger.Error(ex, "Subscribe to service bus Failed.");
      throw;
  }
}
private async Task Processor_ProcessMessageAsync(ProcessMessageEventArgs arg)
{
    try
    {
       // Some business logic to process the message            
    }
    catch (Exception e)
    {
        _logger.Error(e);
    }
    finally
    {
        await CompleteLock(arg.Message);
    }
}

 private async Task Processor_ProcessErrorAsync(ProcessErrorEventArgs arg)
 {
         _logger.Error(arg.Exception, "Service Bus Messaging Exception");
 }

private async Task CompleteLock(ServiceBusReceivedMessage serviceBusReceivedMessage)
{
    try
    {
        if (!_serviceBusReceiver.IsClosed)
        {
            await _serviceBusReceiver.CompleteMessageAsync(serviceBusReceivedMessage);
            _logger.Info("Completed lock");
        }
        else
        {
            _logger.Info("Could not complete the lock because the MessageReceiver is closing");
        }
    }
    catch (Exception e)
    {
        _logger.Error(e, "Failed to complete lock");
        throw;
    }
}
```
**ERROR**
`ERROR Failed to complete lock with Exception Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance. (MessageLockLost). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ThrowLockLostException()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.DisposeMessageAsync(Guid lockToken, Outcome outcome, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteInternalAsync(Guid lockToken, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<CompleteAsync>b__47_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__22`1.<<RunOperation>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteAsync(Guid lockToken, CancellationToken cancellationToken)`

**Comment by SeanFeldman** [comment]
@tapasudenia are you using this code in Azure Functions?

**Comment by tapasudenia** [comment]
No. It is just a regular dotnet 6 API.

**Comment by SeanFeldman** [comment]
I'm confused because you posting this in Azure Functions SDK repo... Wrong repo?

**Comment by tapasudenia** [comment]
I saw the similar thread, my bad, I will remove it from here and post in other one. Thanks

**Comment by avnet78** [comment]
I am getting the same exception. Any update on this?

**Comment by ilaiyarajak** [comment]
I am also facing same issue at 
`await messageActions.CompleteMessageAsync(message);`

Exception is 
> Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.

**Comment by Matthewsre** [comment]
> I am also facing same issue at `await messageActions.CompleteMessageAsync(message);`
> 
> Exception is
> 
> > Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.

I just started getting this error for the CompleteMessageAsync call as well, did you ever figure out how to handle this?

**Comment by tapasudenia** [comment]
So as far as I remember for this exception, whereever you are passing `ProcessMessageEventArgs` you have to use args.CompleteMessageAsync(arg.Message). You should not get the invalid lock exception. 

The problem in my code was, I was using a different ServiceBusReceiver to to complete the lock.

In short replaced, _serviceBusReceiver.CompleteAsync() with args.CompleteMessageAsync(arg.Message where args is ProcessMessageEventArgs and it solved the exception in my case.

**Comment by ThePatrickMartin** [comment]
Also facing this issue. Our function runs every 5 minutes to process messages which were placed in a dead letter queue by another function. We're using ServiceBusReceiver.CompleteMessage(msg) to manually complete the message after sending an email.  **On the first function execution, the email is sent as expected, but we receive the invalid lock error when completing the message. Thus, the message remains in the queue to be processed on the next run. However, on the next execution, the email is sent, but we do not receive the error and the message completes correctly**.

Any insight here would be appreciated!
