### ISSUE TITLE
PackageReferenceRollbackException during AzureWebJobsStorage dependency configuration process

### ISSUE THREAD

**Issue by HMoen** [Azure/azure-functions-dotnet-worker#1010]
VS 2022 17.3.3

Connecting to the AI dependency was smooth, but when connecting to the storage account for AzureWebJobsStorage in the publish profile, it gives the following exception below. Clearing all Nuget caches under Tools => Options did not fix the issue.

.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="3.0.9" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

> Connecting to Azure Storage dependency storage1 in the project...
Adding AzureWebJobsStorage to store AzureAppSettings...
Adding AzureWebJobsStorage:blob to store AzureAppSettings...
Adding AzureWebJobsStorage:queue to store AzureAppSettings...
Adding permissions for app service...
Ensuring the app service has permissions to access resource 'xxxxxxxxxxxxxxxxeastus'...
Installing NuGet packages to project...
Installing package 'Azure.Storage.Blobs' with version '12.3.0'.
ErrorNuGet.PackageManagement.PackageReferenceRollbackException: Package restore failed. Rolling back package changes for 'API.Providers'.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalCoreAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.WebTools.Shared.VS.NuGet.NuGetPackageManager.<InstallAsync>d__42.MoveNext()
ErrorFailed to configure NuGet packages.
ErrorFailed to configure dependency Azure Storage storage1.
![Capture](https://user-images.githubusercontent.com/2124254/187554337-2b3b4c4a-2bfd-4159-b066-a467b6b0fe10.JPG)
![Capture2](https://user-images.githubusercontent.com/2124254/187554340-1def4372-9375-4437-966f-f4cf1d2a5675.JPG)

**Comment by HMoen** [comment]
Progress... manually adding the azure storage nuget packages allowed adding of the storage service dependency:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.0.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.13.1" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.11.0" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.11.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.CosmosDB" Version="3.0.9" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0" />
  </ItemGroup>
```

However, now publishing the consumption func app to Azure fails with:

> Publish has encountered an error.
Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
> A diagnostic log has been written to the following location:
> "C:\Users\...\AppData\Local\Temp\tmpB14D.tmp"

Content of diagnostic log:
> 8/30/2022 10:00:24 PM
System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---
Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
===================

Content of output log:
>The attempt to publish the ZIP file through https://xxx.scm.azurewebsites.net/api/zipdeploy failed with HTTP status code Unauthorized

Following [this suggestion](https://stackoverflow.com/a/71153822) to delete/recreate the publish profile and restarting the func app solved the issue. 

Leaving this here in case someone falls down this rabbit hole ...
