### ISSUE TITLE
Net48 isolated worker sample fails to find runtime in VS2022

### ISSUE THREAD

**Issue by Wraith2** [Azure/azure-functions-dotnet-worker#1023]
I'm investigating azure functions as a method of isolating some program logic currently running in-proc in an app service which uses a badly behaving library which generates dynamic methods and compiles code when invoked, this is causing memory problems.

To do this I'm looking at the netfx isolated worker scenario. I downloaded the repo zip, extracted, opened the sln and compiled successfully.
If I set the startup project to samples\FunctionApp\FunctionApp.csproj and run the project starts and is ready to accept input, as part of the startup the console identifies that I have installed:
```
Azure Functions Core Tools
Core Tools Version:       4.0.4736 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.8.1.18957
```

If I set the startup project to samples\NetFxWorker\NetFxWorker,csproj and the run all i get is a message box from visual studio telling me that:
```
---------------------------
Microsoft Visual Studio
---------------------------
There is no Functions runtime available that matches the version specified in the project.
```

The latest 32 and 64 bit tools are installed per the repo readme. One sample using the v4 runtime works, the netfx isolated sample does not.

VS2022 17.3.3 64 bit, azure workloads installed, additional function core tools installed

**Comment by kshyju** [comment]
@Wraith2 As of today, you need to use VS 2022 preview version If you want to work with .NET framework isolated/NET 7 isolated projects. See below blog post for details.

[Building .NET Serverless applications with isolated model in Azure Functions and Visual Studio 2022](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/building-net-serverless-applications-with-isolated-model-in/ba-p/3598425)

**Comment by Wraith2** [comment]
I want to use netfx 4.8.

**Comment by Wraith2** [comment]
Needing the preview version and RC version of the runtime to use the samples is unintuitive and is not documented in the readme. In the searching I did to try and find how to create an isolated worker that blog post never once came up. So please consider this scenario poorly documented. If that's how it should be done in future that's fine but today on stable released apis and tools it is strange.

Using the preview VS I can get the NetFxWorker project to start but it will fail to run with the exception
```
Unhandled Exception: System.InvalidOperationException: The gRPC channel URI 'http://:0' could not be parsed.
   at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.<>c.<AddGrpc>b__1_1(IServiceProvider p) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 65
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at NetFxWorker.Program.Main(String[] args) in D:\Programming\csharp10\azure-functions-dotnet-worker-main\samples\NetFxWorker\Program.cs:line 21
```

The sample itself is a single http triggered function that isn't directly using Grpc so I have to assume that requirement is coming from inside the framework somehow. So no using preview VS doesn't work.

**Comment by Wraith2** [comment]
Trying to start a new project also doesn't work because the option i want doesn't exist. In the blog post you linked the target dropdown has a "NET Framework Isolated" option, in 17.4.0 Preview 1 that option is not present,
![Untitled](https://user-images.githubusercontent.com/13322696/188737992-78973f51-50c4-468c-8178-1795c9f8b607.png)

**Comment by kshyju** [comment]
@Wraith2 
We will investigate this behavior.  Thank you!

For time being, could you try this?
1. Close all VS instances.
2. Delete the "**_AzureFunctionsTools_**" directory from your local app data folder (`%LOCALAPPDATA%`)
3. Open a new instance and check the "Create new" dialog.

The samples folder in our repo contains code for active development bits & bits that is in preview/beta mode. The goal is to allow the community to have this as a handy reference if they want to try out the latest bits.

**Comment by Wraith2** [comment]
Clearing that folder has enabled the netfx isolated option in the installer wizard dropdown.

Since this is for new development i'm in the wrong place. Can you point me to any existing samples of netfx isolated workers? these were the only ones I could find.

**Comment by kshyju** [comment]
You can refer the NetFxWorker sample in the repo. What issue are you having with that? 

You need to use the preview version of VS **_as of today_** since this is a new feature we started supporting recently. This is a point in time issue. The stable version of VS will support these templates very soon.
