### ISSUE TITLE
Isolated function using docker works in debug but not as a standard container or via compose 

### ISSUE THREAD

**Issue by demyte** [Azure/azure-functions-dotnet-worker#1119]
Hi there,

I am using .net7 rc2 preview and azure functions in isolated mode.

When I debug them as a console app or in a container, they work correctly, but when I build them into a local container or compose them as a set of containers, I get the error below.

It looks like it is somethign to do with grpc starting up, which I don't need, but its hard to get arround when using `hostBuilder.ConfigureFunctionsWorkerDefaults()`.

I feel like this has come in with the rc2 update, but I can not be 100% certain as I was doing moving from normal to isolated functions over the last few days and am not sure on the timing

Appreciate any and all assistance.

dotnet SDKs:
```
> dotnet --list-sdks                                                                                                                                                        
6.0.400 [C:\Program Files\dotnet\sdk]
6.0.402 [C:\Program Files\dotnet\sdk]
7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]
7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
```

Error: 
``` 
info: Host.Function.Console[0]
      https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-rc.2.22472.3&arch=x64&rid=debian.11-x64
fail: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Failed to start a new language worker for runtime: dotnet-isolated.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 271
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 154
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 146
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 137
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.<>c__DisplayClass56_0.<<StartWorkerProcesses>b__0>d.MoveNext() in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 229
```

and then ultimately, the container stops with:
```
info: Host.Function.Console[0]
      https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-rc.2.22472.3&arch=x64&rid=debian.11-x64
fail: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recover
info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Stopping JobHost
info: Host.Startup[0]
      Job host stopped
```

The project has these references:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<DockerFastModeProjectMountDirectory>/home/site/wwwroot</DockerFastModeProjectMountDirectory>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>
<!--- 	... other stuff here ...  -->
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.11.0-preview2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.8.0-preview2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.4.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0-rc.2.22472.3" />
	</ItemGroup>
</Project>
```

The host.json is:

``` json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        },
        "logLevel": {
            "xxxxxxxx.*": "Debug"
        }
    }
}
```

The local.settings.json is:

``` json
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
    },
    "Host": {
        "CORS": "*"
    }
}
```

The launchSettings.json is:

``` json
{
  "profiles": {
    "xxxxxxxxxxxxxxx": {
      "commandName": "Project",
      "commandLineArgs": "--port 31002"
    },
    "Docker": {
      "commandName": "Docker",
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
      "httpPort": 31002,
      "useSSL": false
    }
  }
}
```

The startup is:
``` c#
await new DataFunctionStartup().RunAsync();
```

``` c#

public class DataFunctionStartup : BaseFunctionsStartup<DataFunctionStartup> { }
 
```

``` c#
/// <summary>
/// Shared base class for all functions startups to use
/// </summary>
public class BaseFunctionsStartup<T>
{
    public async Task RunAsync()
    {
        var hostBuilder = CreateHostBuilder();
        var host = hostBuilder.Build();

        // Populate the static resolver with our built DI provider
        ServiceResolver.Configure(host.Services);

        await host.RunAsync();
    }

    private IHostBuilder CreateHostBuilder()
    {
        var hostBuilder = new HostBuilder()
            .ConfigureHostConfiguration(ConfigureHostConfiguration)
            .ConfigureAppConfiguration(BuildAppConfiguration)
            .ConfigureFunctionsWorkerDefaults(ConfigureFunctionsWorker, ConfigureOptions)
            .ConfigureOpenApi()
            .ConfigureServices(Configure);

        return hostBuilder;
    }

    private void ConfigureHostConfiguration(IConfigurationBuilder config)
    {
    }

    private void ConfigureFunctionsWorker(HostBuilderContext context, IFunctionsWorkerApplicationBuilder builder)
    {
        builder.UseNewtonsoftJson(new JsonSerializerSettings
        {
            ContractResolver = new DefaultContractResolver
            {
                NamingStrategy = new CamelCaseNamingStrategy()
            },
            NullValueHandling = NullValueHandling.Ignore
        });

        builder.UseDefaultWorkerMiddleware();

    }

    private void ConfigureOptions(WorkerOptions options)
    {
    }

    /// <summary>
    /// Builds out the default configuraiton from the appsettings files
    /// </summary>
    /// <param name="context">The <see cref="HostBuilderContext"/></param>
    /// <param name="configBuilder">The <see cref="IConfigurationBuilder"/> to use to chain configurations into</param>
    private static void BuildAppConfiguration(HostBuilderContext context, IConfigurationBuilder configBuilder)
    {
        //
        //  NOTE:
        //      appsettings.development.json is generated by the dev machine build system from the
        //      appsettings.development.json.template and as such is populated with configured values
        //      at that time.
        //
        configBuilder
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: false)
            .AddJsonFile($"appsettings.{context.HostingEnvironment.EnvironmentName.ToLower()}.json", optional: true, reloadOnChange: false)
            .AddEnvironmentVariables();
    }

    /// <summary>
    /// Adds globally used services by all functions and then calls to the Injectioneer to wire
    /// up each of the dependant projects requirements
    /// </summary>
    /// <param name="context">The <see cref="HostBuilderContext"/></param>
    /// <param name="services">The <see cref="IServiceCollection"/> DI container</param>
    private void Configure(HostBuilderContext context, IServiceCollection services)
    {
        // globally add logging
        services.AddLogging();

        if (context.Configuration == null) throw new Exception("STARTUP ERROR: Unable to build configuration");

        Injectioneer.WireUp<T>(services, context.Configuration);
    }
}
```

*Full log from startup in container*
```
info: Host.Triggers.Warmup[0]
      Initializing Warmup Extension.
info: Host.Startup[503]
      Initializing Host. OperationId: '6348a5f5-9c5a-4215-9267-f965c41787d0'.
info: Host.Startup[504]
      Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=6348a5f5-9c5a-4215-9267-f965c41787d0
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      LoggerFilterOptions
      {
        "MinLevel": "None",
        "Rules": [
          {
            "ProviderName": null,
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          },
          {
            "ProviderName": null,
            "CategoryName": "xxxx.*",
            "LogLevel": "Debug",
            "Filter": null
          },
          {
            "ProviderName": null,
            "CategoryName": "Host.Function.ToolingConsoleLog",
            "LogLevel": "Information",
            "Filter": null
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": "None",
            "Filter": null
          },
          {
            "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
            "CategoryName": null,
            "LogLevel": null,
            "Filter": "<AddFilter>b__0"
          }
        ]
      }
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      ConcurrencyOptions
      {
        "DynamicConcurrencyEnabled": false,
        "MaximumFunctionConcurrency": 500,
        "CPUThreshold": 0.8,
        "SnapshotPersistenceEnabled": true
      }
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      FunctionResultAggregatorOptions
      {
        "BatchSize": 1000,
        "FlushTimeout": "00:00:30",
        "IsEnabled": true
      }
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      SingletonOptions
      {
        "LockPeriod": "00:00:15",
        "ListenerLockPeriod": "00:01:00",
        "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
        "LockAcquisitionPollingInterval": "00:00:05",
        "ListenerLockRecoveryPollingInterval": "00:01:00"
      }
info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Starting JobHost
info: Host.Startup[401]
      Starting Host (HostId=4ebaabf448f4-2137340777, InstanceId=e40cac63-0634-4d3d-883b-c6f5ee4c282c, Version=4.12.2.2, ProcessId=1, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
info: Host.Startup[314]
      Loading functions metadata
info: Host.Startup[326]
      Reading functions metadata
info: Host.Startup[327]
      1 functions found
info: Host.Startup[315]
      7 functions loaded
info: Host.Startup[0]
      Generating 7 job function(s)
info: Host.Function.Console[0]
      You must install or update .NET to run this application.
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      App: /home/site/wwwroot/xxxxxxxxxxxxxxxxxxxxxxxxx
info: Host.Function.Console[0]
      Architecture: x64
info: Host.Function.Console[0]
      Framework: 'Microsoft.NETCore.App', version '7.0.0-rc.2.22472.3' (x64)
info: Host.Function.Console[0]
      .NET location: /usr/share/dotnet/
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      The following frameworks were found:
info: Host.Function.Console[0]
        7.0.0-rc.2.22464.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      Learn about framework resolution:
fail: Host.Function.Console[0]
      https://aka.ms/dotnet/app-launch-failed
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      To install missing framework, download:
info: Host.Function.Console[0]
      https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-rc.2.22472.3&arch=x64&rid=debian.11-x64
info: Host.Function.Console[0]
      You must install or update .NET to run this application.
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      App: /home/site/wwwroot/xxxxxxxxxxxxxxxxxxxxxxxxxxx
info: Host.Function.Console[0]
      Architecture: x64
info: Host.Function.Console[0]
      Framework: 'Microsoft.NETCore.App', version '7.0.0-rc.2.22472.3' (x64)
info: Host.Function.Console[0]
      .NET location: /usr/share/dotnet/
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      The following frameworks were found:
info: Host.Function.Console[0]
        7.0.0-rc.2.22464.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      Learn about framework resolution:
fail: Host.Function.Console[0]
      https://aka.ms/dotnet/app-launch-failed
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      To install missing framework, download:
info: Host.Function.Console[0]
      https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-rc.2.22472.3&arch=x64&rid=debian.11-x64
fail: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Failed to start a new language worker for runtime: dotnet-isolated.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 271
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 154
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 146
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 137
         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.<>c__DisplayClass56_0.<<StartWorkerProcesses>b__0>d.MoveNext() in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 229
info: Host.Startup[0]
      Found the following functions:
      Host.Functions.xxxxxxxxxxxxxxxxxxxxxx
      Host.Functions.xxxxxxxxxxxxxxxxxxxxxx
      Host.Functions.xxxxxxxxxxxxxxxxxxxxxx
      Host.Functions.RenderOAuth2Redirect
      Host.Functions.RenderOpenApiDocument
      Host.Functions.RenderSwaggerDocument
      Host.Functions.RenderSwaggerUI
      
info: Microsoft.Azure.WebJobs.Hosting.OptionsLoggingService[0]
      HttpOptions
      {
        "DynamicThrottlesEnabled": false,
        "EnableChunkedRequestBinding": false,
        "MaxConcurrentRequests": -1,
        "MaxOutstandingRequests": -1,
        "RoutePrefix": "api"
      }
info: Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostHttpRoutesManager[0]
      Initializing function HTTP routes
      Mapped function route xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      Mapped function route xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      Mapped function route xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      Mapped function route 'api/oauth2-redirect.html' [GET] to 'RenderOAuth2Redirect'
      Mapped function route 'api/openapi/{version}.{extension}' [GET] to 'RenderOpenApiDocument'
      Mapped function route 'api/swagger.{extension}' [GET] to 'RenderSwaggerDocument'
      Mapped function route 'api/swagger/ui' [GET] to 'RenderSwaggerUI'
      
info: Host.Startup[412]
      Host initialized (86ms)
info: Host.Startup[413]
      Host started (99ms)
info: Host.Startup[0]
      Job host started
Hosting environment: Production
Content root path: /azure-functions-host
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
info: Host.General[337]
      Host lock lease acquired by instance ID '000000000000000000000000BB995748'.
info: Host.Function.Console[0]
      You must install or update .NET to run this application.
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      App: /home/site/wwwroot/xxxxxxxxxxxxxxxxxxxxxxxxxxxx
info: Host.Function.Console[0]
      Architecture: x64
info: Host.Function.Console[0]
      Framework: 'Microsoft.NETCore.App', version '7.0.0-rc.2.22472.3' (x64)
info: Host.Function.Console[0]
      .NET location: /usr/share/dotnet/
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      The following frameworks were found:
info: Host.Function.Console[0]
        7.0.0-rc.2.22464.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      Learn about framework resolution:
fail: Host.Function.Console[0]
      https://aka.ms/dotnet/app-launch-failed
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      To install missing framework, download:
info: Host.Function.Console[0]
      https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0-rc.2.22472.3&arch=x64&rid=debian.11-x64
fail: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
      Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recover
info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Stopping JobHost
info: Host.Startup[0]
      Job host stopped
```

**Comment by kshyju** [comment]
@demyte Would you be able to share a minimal repro of this, including the Docker file used to build? A GitHub repo will be great. Thanks!

**Comment by kshyju** [comment]
Looks like the repo you shared is empty! Can you push the minimal repro function app to this repo. Please include your DOCKERFILE as well.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/144469/195753306-64d181c6-bcd1-4bcf-983c-129c6ed84600.png">

**Comment by kshyju** [comment]
Thanks for sharing the repo and dockerfile.

In your Dockerfile, the function app code is being built using sdk:7.0, which has `Microsoft.NETCore.App 7.0.0-rc.2.22472.3` of (as of today.)

You can run `docker run --rm mcr.microsoft.com/dotnet/sdk:7.0 dotnet --info` to see what runtimes/sdks are installed.

If you run `docker run --rm mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7.0 dotnet --info` you will see that `Microsoft.NETCore.App 7.0.0-rc.2.22464.1` in it. This is because dotnet-isolated:4-dotnet-isolated7.0 image was built a few weeks ago and it **_used the latest bits as of that day_**. I think that is causing the issue you are seeing.

I tried looking for an **_old_**(ex: dotnet7 preview5) dotnet sdk tag [here](https://hub.docker.com/_/microsoft-dotnet-sdk/), but could not find anything which was in preview. If we find one, we can use that for the build layer.

Good news is, we will be releasing the refreshed version of azure-functions/dotnet-isolated:4-dotnet-isolated7.0 image and that should have the latest runtime. @CooperLink can share an ETA of that release.

**Comment by BenjaBobs** [comment]
When will the new image be released?

**Comment by ChrisIsidora** [comment]
@CooperLink any idea when the new images will be released?

**Comment by BenjaBobs** [comment]
For anyone finding this, here's the work around my team is using, for installing .NET 7 in our Dockerfile:
```dockerfile
# Install .NET 7
# 1st we need curl so we can download the runtime
RUN apt-get update; apt-get -qq -y install curl
# next up we download and extract the runtime to the dotnet folder
RUN dotnet_runtime_version=7.0.0 && curl -sSL https://dotnetcli.azureedge.net/dotnet/Runtime/$dotnet_runtime_version/dotnet-runtime-$dotnet_runtime_version-linux-x64.tar.gz --output dotnet.tar.gz \
    && mkdir -p /usr/share/dotnet \
    && tar -ozxf dotnet.tar.gz -C /usr/share/dotnet\
    && rm dotnet.tar.gz
# dotnet --info should verify that .NET 7 was installed
RUN dotnet --info
```
