### ISSUE TITLE
Bindings does not resolve properties of poco input parameters

### ISSUE THREAD

**Issue by andsj073** [Azure/azure-functions-dotnet-worker#1218]
Hello
Using Net7.0 and AzureFunctions v4 the following type of Function declaration does not work runtime.
(This worked fine on Net6 in-process)
Sending the queue name as a string parameter "queue" and referring to it by {queue} in binding decl. works fine.

        [Function(nameof(SendMsgToDynamicQueue))]
        [ServiceBusOutput("{mdMsg.QueueName}", Connection = "CONNECTION_PREFIX")] 
        public static string SendMsgToDynamicQueue(
            [ActivityTrigger] MetaDataMessage mdMsg, 
            FunctionContext executionContext)
        { }

    [Serializable]  
    public class MetaDataMessage 
    {
        public string QueueName { get; set; }
    }

Error message:

```log
[2022-12-08T09:35:31.195Z] Executed 'Functions.SendMsgToDynamicQueue' (Failed, Id=76e38d84-7425-4d1b-9ab3-54f639786678, Duration=4275ms)
[2022-12-08T09:35:31.197Z] System.Private.CoreLib: Exception while executing function: Functions.SendMsgToDynamicQueue. Microsoft.Azure.WebJobs.Host: Error while accessing 'QueueName': property doesn't exist.
[2022-12-08T09:35:31.204Z] 08a2b026-8289-4395-997e-99548a24f144: Function 'SendMsgToDynamicQueue (Activity)' failed with an error. Reason: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.SendMsgToDynamicQueue
[2022-12-08T09:35:31.205Z]  ---> System.InvalidOperationException: Error while accessing 'QueueName': property doesn't exist.
[2022-12-08T09:35:31.207Z]    at Microsoft.Azure.WebJobs.Host.Bindings.Path.BindingTemplateToken.ExpressionToken.Evaluate(IReadOnlyDictionary`2 bindingData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Path\BindingTemplateToken.cs:line 197
[2022-12-08T09:35:31.208Z]    at Microsoft.Azure.WebJobs.Host.Bindings.Path.BindingTemplate.Bind(IReadOnlyDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Path\BindingTemplate.cs:line 112
[2022-12-08T09:35:31.209Z]    at Microsoft.Azure.WebJobs.ServiceBus.Bindings.ParameterizedServiceBusPath.Bind(IReadOnlyDictionary`2 bindingData)
[2022-12-08T09:35:31.210Z]    at Microsoft.Azure.WebJobs.ServiceBus.Bindings.ServiceBusBinding.BindAsync(BindingContext context)
[2022-12-08T09:35:31.212Z]    at Microsoft.Azure.WebJobs.Binder.BindAsync[TValue](Attribute[] attributes, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Runtime\Binder.cs:line 117
[2022-12-08T09:35:31.214Z]    at Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.BindAsyncCollectorAsync[T](BindingContext context)
[2022-12-08T09:35:31.215Z]    at Microsoft.Azure.WebJobs.Script.Binding.ExtensionBinding.BindAsync(BindingContext context) in /_/src/WebJobs.Script/Binding/ExtensionBinding.cs:line 88
[2022-12-08T09:35:31.216Z]    at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.<>c__DisplayClass13_0.<<BindOutputsAsync>b__0>d.MoveNext() in /_/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 170
[2022-12-08T09:35:31.217Z] --- End of stack trace from previous location ---
[2022-12-08T09:35:31.218Z]    at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.BindOutputsAsync(Object input, Binder binder, ScriptInvocationResult result) in /_/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 174
[2022-12-08T09:35:31.220Z]    at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /_/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 98
[2022-12-08T09:35:31.221Z]    at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /_/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
[2022-12-08T09:35:31.224Z]    at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /_/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
[2022-12-08T09:35:31.227Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[2022-12-08T09:35:31.228Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 581       
[2022-12-08T09:35:31.230Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 527
[2022-12-08T09:35:31.231Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 306
[2022-12-08T09:35:31.232Z]    --- End of inner exception stack trace ---
[2022-12-08T09:35:31.233Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 352
[2022-12-08T09:35:31.235Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108. IsReplay: False. State: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.9.0. SequenceNumber: 24. TaskEventId: 6
```

**Comment by andsj073** [comment]
Hello

1. Yes I can confirm this. The code is ported from Net6 I process that worked, everything else the same (queue names etc). And yes debugger shows existing queue name. 
2. Hardcoded queuename works. Even when passed as a string parameter (ie not in a property of a poco) works.

**Comment by andsj073** [comment]
I actually had the same problem with a BlobInput binding where I try to specify the container and name dynamically with poco having two properties Container and Name and binding “{poco.Container}/{poco.Name}”. Worked in-process

**Comment by jviau** [comment]
What happens if you remove the `[Serializable]` attribute from your POCO?

**Comment by andsj073** [comment]
> What happens if you remove the `[Serializable]` attribute from your POCO?

Same, Serializable was added later as an attempt to remedy

**Comment by liliankasem** [comment]
I don't know about output bindings as the SDK binding work never touched that, so that will require more investigation. Can you share a minimal project repro for us to debug with?

However, for input and trigger bindings, expressions are not support in dotnet-isolated (with the SDK binding extensions) due to a breaking change bug that we are not able to address till the next major host version.

- https://github.com/Azure/azure-functions-dotnet-worker/issues/1080
- https://github.com/Azure/azure-webjobs-sdk/issues/2930
