### ISSUE TITLE
Microsoft.Azure.Functions.Worker --version 1.13.0 does not work in Azure Function Linux Consumption Plan

### ISSUE THREAD

**Issue by leidegre** [Azure/azure-functions-dotnet-worker#1459]
This is what my log stream looked like when I tried running version 1.13.0 and I was getting the _Server Error. There was an unexpected error in the request processing_ page after timeout. After I downgraded to the more popular version 1.10.0 it started working again.

```
Connected!
2023-04-11T13:21:46Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1405
2023-04-11T13:21:46Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: 'e4aa50cd-c068-41e2-99b6-2c2e3b866f33', runtime: 'dotnet-isolated'
2023-04-11T13:21:46Z   [Verbose]   Disposing language worker channel with id:e4aa50cd-c068-41e2-99b6-2c2e3b866f33
2023-04-11T13:21:46Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-04-11T13:21:46Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
2023-04-11T13:21:54Z   [Verbose]   Initiating background SyncTriggers operation
2023-04-11T13:22:06Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1405
2023-04-11T13:22:06Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: 'accfc9cb-de9b-49ce-8f53-500e75518296', runtime: 'dotnet-isolated'
2023-04-11T13:22:06Z   [Verbose]   Disposing language worker channel with id:accfc9cb-de9b-49ce-8f53-500e75518296
2023-04-11T13:22:06Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-04-11T13:22:06Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
2023-04-11T13:22:20Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1405
2023-04-11T13:22:20Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: 'a8d5be16-6fd0-4301-b944-6a0a14521ea0', runtime: 'dotnet-isolated'
2023-04-11T13:22:20Z   [Verbose]   Disposing language worker channel with id:a8d5be16-6fd0-4301-b944-6a0a14521ea0
2023-04-11T13:22:20Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-04-11T13:22:20Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
2023-04-11T13:22:29Z   [Verbose]   Initiating background SyncTriggers operation
2023-04-11T13:22:43Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1405
--- End of stack trace from previous location ---
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 275
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 152
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 144
2023-04-11T13:22:43Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: '0493eb81-080b-426a-93b9-156bc6deab30', runtime: 'dotnet-isolated'
2023-04-11T13:22:43Z   [Verbose]   Disposing language worker channel with id:0493eb81-080b-426a-93b9-156bc6deab30
2023-04-11T13:22:43Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-04-11T13:22:43Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
2023-04-11T13:22:55Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1405
2023-04-11T13:22:55Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: '9a5a0ac8-5dc1-4899-bd97-05b042dde29c', runtime: 'dotnet-isolated'
2023-04-11T13:22:55Z   [Verbose]   Disposing language worker channel with id:9a5a0ac8-5dc1-4899-bd97-05b042dde29c
2023-04-11T13:22:55Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-04-11T13:22:55Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
2023-04-11T13:23:04Z   [Verbose]   Initiating background SyncTriggers operation
2023-04-11T13:23:31Z   [Verbose]   Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1405
2023-04-11T13:23:31Z   [Verbose]   Attempting to dispose webhost or jobhost channel for workerId: 'c2e6a72b-4efb-447d-a3b9-ab40f61a59d7', runtime: 'dotnet-isolated'
2023-04-11T13:23:31Z   [Verbose]   Disposing language worker channel with id:c2e6a72b-4efb-447d-a3b9-ab40f61a59d7
2023-04-11T13:23:31Z   [Verbose]   No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
2023-04-11T13:23:31Z   [Verbose]   Restarting worker channel for runtime: 'dotnet-isolated'
2023-04-11T13:23:39Z   [Verbose]   Initiating background SyncTriggers operation
2023-04-11T13:23:56Z   [Information]   Host lock lease acquired by instance ID '000000000000000000000000B2644BB9'.
2023-04-11T13:27:35Z   [Information]   Host lock lease acquired by instance ID '0000000000000000000000003590342E'.
```

**Comment by SeanFeldman** [comment]
It works with a Linux hosting plan. I haven't tested with Consumption.

**Comment by akang2023** [comment]
We've ran into the same problem.  We are on Linux on Consumption

**Comment by leidegre** [comment]
No. It did not fix itself ;)

I just did a deployment of this code to an Linux Azure Function Consumption Plan
[azfn-linux-consumption.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/11395385/azfn-linux-consumption.zip) and it just looks like this when you try to access the "Hello" function

https://john-linux-azfn.azurewebsites.net/api/Hello?code=pPvb...

![image](https://user-images.githubusercontent.com/63085/236152036-c7d5f8c7-ce28-4538-b6b9-8867789e5373.png)

**Comment by kshyju** [comment]
Hi folks, sorry for the inconvenience. We identified a race condition issue which might cause this behavior and fixed it in #1508 and released in worker package [1.14.0](https://github.com/Azure/azure-functions-dotnet-worker/releases/tag/1.14.0). Please try this version.

https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/1.14.0

**Comment by fabiocav** [comment]
> Okay. Yeah. That did it.
> 
> I would really like to know how this could have happened in the first place.
> 
> Don't you guys do validation before you release stuff? Would this be something you validate as part of a release pipeline?

@leidegre all releases go through a number of validation steps, the public ones you can see as part of CI and release pipelines, as well as a number of additional validations for behavior and performance on different SKUs and platform configurations. This was, unfortunately, an issue that was not reproducing in our existing tests. That has been addressed and we're continuously reviewing and improving that validation process, so hopefully this is not something we'll see happen again.

Thanks for reporting.

**Comment by leidegre** [comment]
Okay great. That's all I wanted.
