### ISSUE TITLE
Dependency Injection - Isoloated functionapp fails on Azure (Linux plan)

### ISSUE THREAD

**Issue by saisworld** [Azure/azure-functions-dotnet-worker#1542]
I have an isolated function app that runs locally without any error but when published to Functionapp via Visual studio, it fails with below error. 
`Exception while executing function: Functions.xxxxx Result: Failure
Exception: System.InvalidOperationException: Unable to resolve service for type 'xxxxxx.AppConfiguration' while attempting to activate 'xxxxx.DailyMorningEmails'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23`

In the `program.cs`,  I'm adding the class to the DI like this - 

```
.ConfigureServices(async  services =>
    {
     
       ..... 
    
       services.AddSingleton(appConfiguration);
    }
```

I'm injecting it in the Function constructor and it works correctly locally but fails in Azure. In Azure, its hosted on Linux ASP with .net 6. 
Please advise

**Comment by kshyju** [comment]
Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.

**Comment by saisworld** [comment]
Here is the program.cs content - 

```
var host = new HostBuilder()

    .ConfigureAppConfiguration(c =>
    {
        configRoot = c.SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
#if DEBUG
              .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
#endif
              .AddEnvironmentVariables().Build();
    }).ConfigureLogging(logging =>
    {
       // logging.ClearProviders();
    })
        .ConfigureFunctionsWorkerDefaults(builder =>
        {           
            builder= LoggingConfig.Config(builder, configRoot);
        })
    .ConfigureServices(async  services =>
    {
        var environmentName = configRoot.GetValue<string>("Environment");
        //register businessmanager classes using reflection.
    
        services.RegisterAssemblyPublicNonGenericClasses(assembliesToScan)
           .Where(c => c.Name.EndsWith("BusinessManager") || c.Name.EndsWith("DataAccess"))
        .AsPublicImplementedInterfaces(ServiceLifetime.Transient);

        var keyvaultService = new KeyVaultService(configRoot.GetValue<string>("KeyvaultUrl"));
        services.AddTransient<IKeyVaultService>(x => keyvaultService);
        var appConfiguration = new AppConfiguration();

        //custom scoped registration for getting connectionstring
        if (environmentName == "Development")
        {
            appConfiguration.ConnectionString = configRoot.GetValue<string>("ConnectionStrings:DBcontext");
        }
        else
        {
            //for prod get connectionstring from keyvault           
            appConfiguration.ConnectionString = await keyvaultService.GetSecret("DbContextConnString");
        }

        services.AddScoped(x => new ProquroContext(appConfiguration.ConnectionString));
        services.AddSingleton(appConfiguration);

 

        //framework
        //services.AddTransient<IFileStorage, AzureBlobStorage>();
        services.AddTransient<IEmail, Email>();
        //services.AddTransient<IFileProcessor, FileProcessor>();

        services.AddSingleton(new EmailSettings()
        {
            SMTPHost = configRoot.GetValue<string>("EmailSettings:SMTPHost"),
            SMTPPort = configRoot.GetValue<int>("EmailSettings:SMTPPort"),
            SMTPUsername = configRoot.GetValue<string>("EmailSettings:SMTPUsername"),
            SMTPPasswordKey = configRoot.GetValue<string>("EmailSettings:SMTPPasswordKey"),
            SenderEmail = configRoot.GetValue<string>("EmailSettings:SenderEmail"),
            ReplyTo = configRoot.GetValue<string>("EmailSettings:ReplyTo"),
            SenderName = configRoot.GetValue<string>("EmailSettings:SenderName"),
            SMTPPassword = environmentName == "Development" ?
            configRoot.GetValue<string>("EmailSettings:SMTPPassword") //for local only
            : await keyvaultService.GetSecret("ProquroSmtpPassword") // on azure
        });


    });

await host.Build().RunAsync();
```

**Comment by kshyju** [comment]
@saisworld Is this the absolute minimum code one needs to replicate the issue? Wondering we can trim it down to even smaller repro.
