### ISSUE TITLE
HttpTrigger with query string parameter not working

### ISSUE THREAD

**Issue by swilkodev** [Azure/azure-functions-dotnet-worker#163]
Using the below HttpTrigger signature with preview 4.

`[FunctionName(nameof(ExportTodos))]`
`public async Task<HttpResponseData> ExportTodos([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "todolists/export/{id}")]`
            `HttpRequestData req,`
           ` int id,`
           ` FunctionExecutionContext executionContext)`
`{`
``
`}`

I get the following error when calling the API

[2021-02-24T09:33:35.132Z] Executed 'Functions.ExportTodos' (Failed, Id=4c729cdd-d310-465e-a7ba-54467aca8075, Duration=132ms)
[2021-02-24T09:33:35.135Z] System.Private.CoreLib: Exception while executing function: Functions.ExportTodos. System.Private.CoreLib: Result: Failure
Exception: Object reference not set to an instance of an object.
Stack:    at lambda_method2(Closure , TodoFunctions , Object[] )
[2021-02-24T09:33:35.137Z]    at Microsoft.Azure.Functions.Worker.Invocation.TaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker\Invocation\TaskMethodInvoker.cs:line 23
[2021-02-24T09:33:35.138Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionInvoker.cs:line 31
[2021-02-24T09:33:35.139Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionExecutionContext context) in D:\a\1\s\src\DotNetWorker\Invocation\DefaultFunctionExecutor.cs:line 16
[2021-02-24T09:33:35.141Z]    at Microsoft.Azure.Functions.Worker.FunctionBroker.InvokeAsync(FunctionInvocation invocation) in D:\a\1\s\src\DotNetWorker\Broker\FunctionBroker.cs:line 55.  

This signature works fine with .NET core 3.1 solution with HttpRequest.

**Comment by fabiocav** [comment]
This should be addressed with the update dropping this week.

@mhoeger / @brettsam for awareness.

**Comment by swilkodev** [comment]
Confirming this one is fixed in preview 5.
