### ISSUE TITLE
NullReferenceException thrown when query string value is missing

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-dotnet-worker#1651]
Start with the following working function definition:

```csharp
        [Function("helloworld")]
        public HttpResponseData HelloWorld(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
        {
            _logger.LogInformation("C# HTTP trigger function processed a request.");
            var response = req.CreateResponse(HttpStatusCode.OK);
            return response;
        }
```

Now, add a parameter that will come from the query string, with a default value:
```csharp
        [Function("helloworld")]
        public HttpResponseData HelloWorld(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
            int foo=100)
        {
            _logger.LogInformation("C# HTTP trigger function processed a request.");
            var response = req.CreateResponse(HttpStatusCode.OK);
            return response;
        }
```

Next, invoke the function but do NOT pass the query string param:

GET http://localhost:7157/api/helloworld

Expected behavior: The default value is used. Or, failing that, at least provide an error message that is more meaningful to the user, saying that this scenario is not supported. 

Actual behavior: a NullReferenceException is thrown, and the error message/stack do not make the problem obvious:

```
[2023-06-21T00:11:02.831Z] Function 'helloworld', Invocation id '32806cc9-5bbc-44cd-82af-9834fb926f35': An exception was thrown by the invocation.
[2023-06-21T00:11:02.832Z] Result: Function 'helloworld', Invocation id '32806cc9-5bbc-44cd-82af-9834fb926f35': An exception was thrown by the invocation.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
[2023-06-21T00:11:02.833Z]    at lambda_method1(Closure , Function1 , Object[] )
[2023-06-21T00:11:02.834Z]    at Microsoft.Azure.Functions.Worker.Invocation.MethodInvokerWithReturnValue`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\MethodInvokerWithReturnValue.cs:line 22
[2023-06-21T00:11:02.835Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2023-06-21T00:11:02.836Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2023-06-21T00:11:02.837Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-06-21T00:11:02.838Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
Stack:    at lambda_method1(Closure , Function1 , Object[] )
[2023-06-21T00:11:02.839Z]    at Microsoft.Azure.Functions.Worker.Invocation.MethodInvokerWithReturnValue`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\MethodInvokerWithReturnValue.cs:line 22
[2023-06-21T00:11:02.840Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2023-06-21T00:11:02.841Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2023-06-21T00:11:02.842Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-06-21T00:11:02.843Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77.
[2023-06-21T00:11:02.850Z] Executed 'Functions.helloworld' (Failed, Id=32806cc9-5bbc-44cd-82af-9834fb926f35, Duration=227ms)
[2023-06-21T00:11:02.852Z] System.Private.CoreLib: Exception while executing function: Functions.helloworld. System.Private.CoreLib: Result: Failure
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
[2023-06-21T00:11:02.853Z]    at lambda_method1(Closure , Function1 , Object[] )
[2023-06-21T00:11:02.853Z]    at Microsoft.Azure.Functions.Worker.Invocation.MethodInvokerWithReturnValue`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\MethodInvokerWithReturnValue.cs:line 22
[2023-06-21T00:11:02.854Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2023-06-21T00:11:02.856Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2023-06-21T00:11:02.857Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-06-21T00:11:02.858Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2023-06-21T00:11:02.859Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at lambda_method1(Closure , Function1 , Object[] )
[2023-06-21T00:11:02.860Z]    at Microsoft.Azure.Functions.Worker.Invocation.MethodInvokerWithReturnValue`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\MethodInvokerWithReturnValue.cs:line 22
[2023-06-21T00:11:02.861Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2023-06-21T00:11:02.862Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2023-06-21T00:11:02.863Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-06-21T00:11:02.865Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2023-06-21T00:11:02.866Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.
```

**Comment by fabiocav** [comment]
Closed as resolved.

**Comment by fabiocav** [comment]
This will be available with the next release of the worker package
