### ISSUE TITLE
Getting error after upgrading Blob extension to version 6.0.0

### ISSUE THREAD

**Issue by SoleCode** [Azure/azure-functions-dotnet-worker#1786]
I use BlobTrigger (isolated mode, function v4, .NET 7). After I upgrade the "Microsoft.Azure.Functions.Worker.Extensions.Storage" from "5.1.2" to "6.0.0", I'm seeing this error:
Executed 'Functions.****Trigger'
System.InvalidOperationException: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Microsoft.Azure.Functions.Worker.BlobStorageBindingOptions]' from root provider.
System.Private.CoreLib: Exception while executing function: Functions.BatchFileEntityChangeTrigger. System.Private.CoreLib: Result: Failure
Exception: System.InvalidOperationException: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Microsoft.Azure.Functions.Worker.BlobStorageBindingOptions]' from root provider

**Comment by liliankasem** [comment]
Can you provide a minimal function app repro project so we can investigate?

**Comment by cvi-mft** [comment]
I have a minimal repro project here. The error occurs only when using `Host.CreateDefaultBuilder` since the DI validation isn't triggered by the empty initialization of the Host. To repro:
1. Run Repro Function
2. Add a blob to the container "repro" in the storage emulator.

[BlobStorageBindingOptionsRepro.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/12288246/BlobStorageBindingOptionsRepro.zip)

**Comment by SoleCode** [comment]
Thank you @cvi-mft.
@liliankasem please use the repo provided by @cvi-mft

**Comment by liliankasem** [comment]
Thank you for the repro, we'll get this assigned soon and work on a fix

**Comment by SoleCode** [comment]
@liliankasem thank for fixing the issue, I have upgraded to 6.0.1 now I'm seeing different error
this is my Az Fx
```
public async Task BatchFileTrigger([BlobTrigger("%ContainerName%/subfolder/{fileName}.{extension}", Connection = "AzureStorageConnection")] Stream obj, string fileName, string extension, CancellationToken cancellationToken)
```
This is the error I'm seeing
```
[2023-08-10T01:26:01.964Z] Function 'BatchFileTrigger', Invocation id 'e64667c4-73c6-4179-9679-9c2580495d03': An exception was thrown by the invocation.
[2023-08-10T01:26:01.964Z]       Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'BatchFileTrigger': Cannot convert input parameter 'obj' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.InvalidOperationException: Blob storage connection configuration 'AzureStorageConnection' does not exist. Make sure that it is a defined App Setting.
[2023-08-10T01:26:01.966Z] Result: Function 'BatchFileTrigger', Invocation id 'e64667c4-73c6-4179-9679-9c2580495d03': An exception was thrown by the invocation.
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'BatchFileTrigger': Cannot convert input parameter 'obj' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.InvalidOperationException: Blob storage connection configuration 'AzureStorageConnection' does not exist. Make sure that it is a defined App Setting.
[2023-08-10T01:26:01.968Z]          at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptionsSetup.Configure(String name, BlobStorageBindingOptions options) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptionsSetup.cs:line 44
[2023-08-10T01:26:01.971Z] Executed 'Functions.BatchFileTrigger' (Failed, Id=e64667c4-73c6-4179-9679-9c2580495d03, Duration=72ms)
[2023-08-10T01:26:01.972Z]          at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
[2023-08-10T01:26:01.973Z] System.Private.CoreLib: Exception while executing function: Functions.BatchFileTrigger. System.Private.CoreLib: Result: Failure
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'BatchFileTrigger': Cannot convert input parameter 'obj' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.InvalidOperationException: Blob storage connection configuration 'AzureStorageConnection' does not exist. Make sure that it is a defined App Setting.
[2023-08-10T01:26:01.977Z]    at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptionsSetup.Configure(String name, BlobStorageBindingOptions options) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptionsSetup.cs:line 44
[2023-08-10T01:26:01.979Z]    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
[2023-08-10T01:26:01.974Z]          at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[2023-08-10T01:26:01.980Z]    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[2023-08-10T01:26:01.981Z]       --- End of stack trace from previous location ---
[2023-08-10T01:26:01.982Z] --- End of stack trace from previous location ---
[2023-08-10T01:26:01.984Z]    at System.Lazy`1.CreateValue()
[2023-08-10T01:26:01.983Z]          at System.Lazy`1.CreateValue()
[2023-08-10T01:26:01.985Z]    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
[2023-08-10T01:26:01.993Z]          at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
[2023-08-10T01:26:01.996Z]    at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
[2023-08-10T01:26:01.997Z]          at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
[2023-08-10T01:26:01.998Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.CreateBlobContainerClient(String connectionName, String containerName) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 253
[2023-08-10T01:26:02.000Z]          at Microsoft.Azure.Functions.Worker.BlobStorageConverter.CreateBlobContainerClient(String connectionName, String containerName) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 253
[2023-08-10T01:26:02.001Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertModelBindingDataAsync(Type targetType, BlobBindingData blobData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 118
[2023-08-10T01:26:02.002Z]          at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertModelBindingDataAsync(Type targetType, BlobBindingData blobData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 118
[2023-08-10T01:26:02.004Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertFromBindingDataAsync(ConverterContext context, ModelBindingData modelBindingData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 63
[2023-08-10T01:26:02.005Z]          at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertFromBindingDataAsync(ConverterContext context, ModelBindingData modelBindingData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 63
[2023-08-10T01:26:02.007Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
[2023-08-10T01:26:02.008Z]          at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
[2023-08-10T01:26:02.016Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 42
[2023-08-10T01:26:02.018Z]          at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 42
[2023-08-10T01:26:02.019Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-08-10T01:26:02.020Z]          at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-08-10T01:26:02.022Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.Invoke(FunctionContext functionContext, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 22
[2023-08-10T01:26:02.023Z]          at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.Invoke(FunctionContext functionContext, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 22
[2023-08-10T01:26:02.025Z] Request [4985fb95-445b-4b21-bca5-33666705def0] GET http://127.0.0.1:10001/devstoreaccount1/azure-webjobs-blobtrigger-us3219807w1-1606134809/messages?numofmessages=32&visibilitytimeout=600
[2023-08-10T01:26:01.971Z]    at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptionsSetup.Configure(String name, BlobStorageBindingOptions options) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptionsSetup.cs:line 44
[2023-08-10T01:26:02.028Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2023-08-10T01:26:02.031Z]          at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
```

**Comment by liliankasem** [comment]
> @liliankasem thank you for fixing the issue, I have upgraded to 6.0.1 now I'm seeing different error this is my Az Fx
> 
> ```
> public async Task BatchFileTrigger([BlobTrigger("%ContainerName%/subfolder/{fileName}.{extension}", Connection = "AzureStorageConnection")] Stream obj, string fileName, string extension, CancellationToken cancellationToken)
> ```
> 
> This is the error I'm seeing
> 
> ```
> [2023-08-10T01:26:01.964Z] Function 'BatchFileTrigger', Invocation id 'e64667c4-73c6-4179-9679-9c2580495d03': An exception was thrown by the invocation.
> [2023-08-10T01:26:01.964Z]       Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'BatchFileTrigger': Cannot convert input parameter 'obj' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.InvalidOperationException: Blob storage connection configuration 'AzureStorageConnection' does not exist. Make sure that it is a defined App Setting.
> [2023-08-10T01:26:01.966Z] Result: Function 'BatchFileTrigger', Invocation id 'e64667c4-73c6-4179-9679-9c2580495d03': An exception was thrown by the invocation.
> Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'BatchFileTrigger': Cannot convert input parameter 'obj' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.InvalidOperationException: Blob storage connection configuration 'AzureStorageConnection' does not exist. Make sure that it is a defined App Setting.
> [2023-08-10T01:26:01.968Z]          at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptionsSetup.Configure(String name, BlobStorageBindingOptions options) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptionsSetup.cs:line 44
> [2023-08-10T01:26:01.971Z] Executed 'Functions.BatchFileTrigger' (Failed, Id=e64667c4-73c6-4179-9679-9c2580495d03, Duration=72ms)
> [2023-08-10T01:26:01.972Z]          at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
> [2023-08-10T01:26:01.973Z] System.Private.CoreLib: Exception while executing function: Functions.BatchFileTrigger. System.Private.CoreLib: Result: Failure
> Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'BatchFileTrigger': Cannot convert input parameter 'obj' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.InvalidOperationException: Blob storage connection configuration 'AzureStorageConnection' does not exist. Make sure that it is a defined App Setting.
> [2023-08-10T01:26:01.977Z]    at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptionsSetup.Configure(String name, BlobStorageBindingOptions options) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptionsSetup.cs:line 44
> [2023-08-10T01:26:01.979Z]    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
> [2023-08-10T01:26:01.974Z]          at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
> [2023-08-10T01:26:01.980Z]    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
> [2023-08-10T01:26:01.981Z]       --- End of stack trace from previous location ---
> [2023-08-10T01:26:01.982Z] --- End of stack trace from previous location ---
> [2023-08-10T01:26:01.984Z]    at System.Lazy`1.CreateValue()
> [2023-08-10T01:26:01.983Z]          at System.Lazy`1.CreateValue()
> [2023-08-10T01:26:01.985Z]    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
> [2023-08-10T01:26:01.993Z]          at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
> [2023-08-10T01:26:01.996Z]    at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
> [2023-08-10T01:26:01.997Z]          at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
> [2023-08-10T01:26:01.998Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.CreateBlobContainerClient(String connectionName, String containerName) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 253
> [2023-08-10T01:26:02.000Z]          at Microsoft.Azure.Functions.Worker.BlobStorageConverter.CreateBlobContainerClient(String connectionName, String containerName) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 253
> [2023-08-10T01:26:02.001Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertModelBindingDataAsync(Type targetType, BlobBindingData blobData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 118
> [2023-08-10T01:26:02.002Z]          at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertModelBindingDataAsync(Type targetType, BlobBindingData blobData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 118
> [2023-08-10T01:26:02.004Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertFromBindingDataAsync(ConverterContext context, ModelBindingData modelBindingData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 63
> [2023-08-10T01:26:02.005Z]          at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertFromBindingDataAsync(ConverterContext context, ModelBindingData modelBindingData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 63
> [2023-08-10T01:26:02.007Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
> [2023-08-10T01:26:02.008Z]          at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
> [2023-08-10T01:26:02.016Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 42
> [2023-08-10T01:26:02.018Z]          at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 42
> [2023-08-10T01:26:02.019Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2023-08-10T01:26:02.020Z]          at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
> [2023-08-10T01:26:02.022Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.Invoke(FunctionContext functionContext, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 22
> [2023-08-10T01:26:02.023Z]          at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.Invoke(FunctionContext functionContext, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 22
> [2023-08-10T01:26:02.025Z] Request [4985fb95-445b-4b21-bca5-33666705def0] GET http://127.0.0.1:10001/devstoreaccount1/azure-webjobs-blobtrigger-us3219807w1-1606134809/messages?numofmessages=32&visibilitytimeout=600
> [2023-08-10T01:26:01.971Z]    at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptionsSetup.Configure(String name, BlobStorageBindingOptions options) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptionsSetup.cs:line 44
> [2023-08-10T01:26:02.028Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
> [2023-08-10T01:26:02.031Z]          at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
> ```
> 
> My Az Fx works with version 5.1.2 without any issue. All packages in my project are up-to-date.

Yikes. And the app setting is definitely there? Can you share a minimal repro project for me to look at so make sure I'm not missing anything
