### ISSUE TITLE
No Cancellation Token on Azure Function Method

### ISSUE THREAD

**Issue by BroMarduk** [Azure/azure-functions-dotnet-worker#180]
In the previous framework, I could pass a cancellation token to an Azure Function Method:

```
        [FunctionName("my-function")]
        public async Task<IActionResult> MyFunction(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)] HttpRequest req,
        CancellationToken cancellationToken)
        {
             ...
        }
```
if I try and do that now, an error occurs when calling the method with the cancellation token:

```
        [FunctionName("my-function")]
        public async Task<HttpResponseData> MyFunction(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)] HttpRequestData req,
            FunctionExecutionContext executionContext),
            CancellationToken cancellationToken)
        {
             ...
        }
```

This is the error that occurs when calling the method:

```
[2021-02-05T01:44:09.069Z] System.Private.CoreLib: Exception while executing function: Functions.migrate. System.Private.CoreLib: Result: Failure
Exception: Sequence contains no elements
Stack:    at System.Linq.ThrowHelper.ThrowNoElementsException()
[2021-02-05T01:44:09.070Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionExecutionContext context)
[2021-02-05T01:44:09.071Z]    at Microsoft.Azure.Functions.Worker.FunctionBroker.InvokeAsync(InvocationRequest invocationRequest) in D:\a\1\s\src\DotNetWorker\Broker\FunctionBroker.cs:line 44.
```

Will support be added back in for the tokens?

**Comment by dmytro-gokun** [comment]
Now, when version 1.0.0 is out... is it possible to use CancellationTokens?

**Comment by tidusjar** [comment]
Is there any update on this? 

I'd like to understand the reasoning behind removing the cancellation token, especially in the case of HttpTriggerFunctions where using a `CancellationToken` makes **A LOT** of sense. 

This is a bit of a deal breaker personally for me as I feel like this is a step backwards and is preventing me from upgrading to net core 5.

**Comment by HMoen** [comment]
@tidusjar, you can try this suggestion https://github.com/Azure/azure-functions-host/issues/6911#issuecomment-842528631 by injecting the [IHostApplicationLifetime](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime?view=dotnet-plat-ext-5.0) into the function and watching the  [ApplicationStopping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime.applicationstopping?view=dotnet-plat-ext-5.0#microsoft-extensions-hosting-ihostapplicationlifetime-applicationstopping) cancellation token.

**Comment by tidusjar** [comment]
> @tidusjar, you can try this suggestion https://github.com/Azure/azure-functions-host/issues/6911#issuecomment-842528631 by injecting the [IHostApplicationLifetime](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime?view=dotnet-plat-ext-5.0) into the function and watching the  [ApplicationStopping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime.applicationstopping?view=dotnet-plat-ext-5.0#microsoft-extensions-hosting-ihostapplicationlifetime-applicationstopping) cancellation token.

Thanks for the suggestion, but this does not resolve my issue. My issue is regarding when a Http request is cancelled, there Is currently no way to handle this  

The cancellation token you mentioned is regarding the application lifecycle. But I appreciate the pointer.

**Comment by HMoen** [comment]
@tidusjar, I always understood the [cancellation token](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#cancellation-tokens) being passed in the function method was the operating system notifying the function is about to terminate.

I think what you're looking for is [HttpContext.RequestAborted](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestaborted?view=aspnetcore-5.0) based on this [thread](https://stackoverflow.com/a/63439515).

**Comment by SeanFeldman** [comment]
This is why the SDK should provide cancellation token rather than developers come up with their own solutions and recreated the same thing time and time again. From all the things that are being improved with the isolated worker, this feels like a step in the wrong direction. @fabiocav any plans to address this?

**Comment by nzthiago** [comment]
To be surfaced to the .NET isolated worker this depends on a host update related to this feature https://github.com/Azure/azure-functions-host/issues/7785, and requires further design decisions and prioritization, so for now [the documentation here](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#differences-with-net-class-library-functions) is up to date. Note that even though the cancellation token isn't flowing into the out of proc function, a graceful period should still be given to your function as [per this work](https://github.com/Azure/azure-functions-host/issues/7772) in Consumption and Premium plans.

**Comment by Manthazar** [comment]
> @tidusjar, I always understood the [cancellation token](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#cancellation-tokens) being passed in the function method was the operating system notifying function it is about to terminate.
> 
> I think what you're looking for is [HttpContext.RequestAborted](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestaborted?view=aspnetcore-5.0) based on this [thread](https://stackoverflow.com/a/63439515) .

The stackoverflow page doesn't help here because there is http context to which we could link the token.

**Comment by thomaslevesque** [comment]
I'm getting a NullReferenceException in the host's code when I add a cancellation token to a timer trigger:

```
[2022-05-07T22:58:51.934Z] Executed 'Functions.MyFunction' (Failed, Id=6b958381-1d1f-43f5-b701-abb6daaab3c4, Duration=6409ms)
[2022-05-07T22:58:51.935Z] System.Private.CoreLib: Exception while executing function: Functions.MyFunction. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
[2022-05-07T22:58:51.936Z]  ---> System.NullReferenceException: Object reference not set to an instance of an object.
[2022-05-07T22:58:51.936Z]    at lambda_method1(Closure , MyFunction , Object[] )
[2022-05-07T22:58:51.937Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidTask
MethodInvoker.cs:line 22
[2022-05-07T22:58:51.937Z]    --- End of inner exception stack trace ---
[2022-05-07T22:58:51.938Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2022-05-07T22:58:51.938Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2022-05-07T22:58:51.938Z]    at System.Threading.Tasks.Task`1.get_Result()
[2022-05-07T22:58:51.939Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:
line 32
[2022-05-07T22:58:51.939Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2022-05-07T22:58:51.940Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2022-05-07T22:58:51.941Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-05-07T22:58:51.942Z] --- End of stack trace from previous location ---
[2022-05-07T22:58:51.942Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-05-07T22:58:51.943Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2022-05-07T22:58:51.944Z] --- End of stack trace from previous location ---
[2022-05-07T22:58:51.945Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor
.cs:line 44
[2022-05-07T22:58:51.946Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\Out
putBindings\OutputBindingsMiddleware.cs:line 13
[2022-05-07T22:58:51.946Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationF
eaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2022-05-07T22:58:51.947Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2022-05-07T22:58:51.948Z]    at System.Threading.Tasks.Task`1.get_Result()
[2022-05-07T22:58:51.948Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:
line 32
[2022-05-07T22:58:51.949Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2022-05-07T22:58:51.949Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2022-05-07T22:58:51.950Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-05-07T22:58:51.951Z] --- End of stack trace from previous location ---
[2022-05-07T22:58:51.951Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[2022-05-07T22:58:51.952Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2022-05-07T22:58:51.953Z] --- End of stack trace from previous location ---
[2022-05-07T22:58:51.953Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor
.cs:line 44
[2022-05-07T22:58:51.954Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\Out
putBindings\OutputBindingsMiddleware.cs:line 13
[2022-05-07T22:58:51.954Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationF
eaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167.
```

(admittedly, it might not make much sense to add a cancellation to a time-triggered function, but still, it shouldn't fail like this... at the very least, if it's not supported, it should indicate it clearly rather than throw a NRE)

**Comment by mjallaq88** [comment]
I have tried the sample code in Release1.9.0 and I still don't see the feature is working. I invoke the azure function and cancel it but the cancellation token is not being catched.

**Comment by kshyju** [comment]
@mjallaq88 Could you please open a new issue with relevant repro information? If you can share a minimal repro (a github repo would be great), we can take a look. Thanks!
