### ISSUE TITLE
Getting Null Exception

### ISSUE THREAD

**Issue by chassq** [Azure/azure-functions-dotnet-worker#181]
See attached image when trying to run. Get is using local and trying a storage account in azure
<img width="1913" alt="Screenshot 2021-02-01 133613" src="https://user-images.githubusercontent.com/4785384/106502664-a3bce300-6492-11eb-9f0d-85f242ffd19d.png">

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at Microsoft.Azure.WebJobs.Script.Grpc.Messages.StartStream.set_WorkerId(String value) in D:\a\1\s\src\DotNetWorker\obj\Release\net5.0\FunctionRpc.cs:line 1414
   at Microsoft.Azure.Functions.Worker.WorkerHostedService.SendStartStreamMessageAsync(IClientStreamWriter`1 requestStream) in D:\a\1\s\src\DotNetWorker\WorkerHostedService.cs:line 48
   at Microsoft.Azure.Functions.Worker.WorkerHostedService.StartAsync(CancellationToken cancellationToken) in D:\a\1\s\src\DotNetWorker\WorkerHostedService.cs:line 37
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at FunctionApp.Program.Main(String[] args) in C:\Users\charl\Source\Repos\azure-functions-dotnet-worker-preview\FunctionApp\Program.cs:line 34
   at FunctionApp.Program.<Main>(String[] args)

C:\Users\charl\Source\Repos\azure-functions-dotnet-worker-preview\FunctionApp\bin\Debug\net5.0\FunctionApp.exe (process 22880) exited with code -532462766.
Press any key to close this window . . .

**Comment by chassq** [comment]
Installed the latest https://github.com/Azure/azure-functions-core-tools. Cloned the https://github.com/Azure/azure-functions-dotnet-worker-preview repo. Using latest VS 2019 preview.

Now I get this:
<img width="1904" alt="Screenshot 2021-02-26 034656" src="https://user-images.githubusercontent.com/4785384/109277617-9111a180-77e5-11eb-99c6-5ea95fb41a2e.png">

**Comment by fabiocav** [comment]
Can you please share the full stack? Any connection information in local settings would also be help (sanitized to remove secrets)

**Comment by chassq** [comment]
We have changed no code or settings with this for now. Just using what is in the project as is for now. When you say "Full Stack" can you give me a list of what you need. Not sure what that means.

**Comment by kshyju** [comment]
Hi @chassq 👋

How are you trying to run this? Are you doing `dotnet run` on the FunctionApp.exe? The "_Invalid URI: The hostname could not be parsed_" usually happens when an incorrect debug/run configuration is used which causes `dotnet run` to be executed against the function app exe. See a [similar issue with RIDER IDE](https://github.com/Azure/Azure-Functions/issues/2032#issuecomment-941028418) for a bit more details.

You are not supposed to run the `dotnet run` command on an isolated (out-of-process) function app. Instead, we should use function CLI command `func start`. Behind the scenes, this command starts the host process, and the host process will internally invoke the out-of-process function app. When it does this, the host passes some information the worker needs so that it can properly communicate with the host (things like the address & port number to be used for GRPC communication between host and worker)

The C# out-of-process function app cannot run by itself. It runs with the host (func.exe).

Let us know if you are still facing this issue. Sharing a minimal repro (a github repo link) would help us to investigate further. Thanks!

**Comment by chassq** [comment]
I do not think this is an issue for us anymore. We are moving on to dotnet 6.
