### ISSUE TITLE
Azure Functions: Exception with Managed Identity and EventGrid source for Blob Trigger

### ISSUE THREAD

**Issue by gp-nttdata** [Azure/azure-functions-dotnet-worker#1890]
Hello everyone.
I am having a problem with Azure Function with a Blob Trigger:
Environment:
```
.NET: 7
Function SDK: 4
Blob Extension Version: 6.1.0
Process Mode: Isolated
```

After following this tutorial https://learn.microsoft.com/en-us/azure/azure-functions/functions-event-grid-blob-trigger to change the transport from `BlobTriggerSource.LogsAndContainerScan` to `BlobTriggerSource.EventGrid` everything was working fine. I was able to enter (and debug) the function when I uploaded a new file to the storage account.

When I tried to use Managed Identity, instead of a connection string, I got the following error:
```
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function '<FUNCTION_NAME>': Cannot convert input parameter 'stream' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
```
with the following call stack:
```
- at Microsoft.Azure.Functions.Worker.BlobStorageConverter.CreateBlobContainerClient(String connectionName, String containerName) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 253
- at Azure.Storage.StorageConnectionString.Parse(String connectionString)
- at Azure.Storage.Blobs.BlobServiceClient..ctor(String connectionString, BlobClientOptions options)
- at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertModelBindingDataAsync(Type targetType, BlobBindingData blobData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 118
- at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertFromBindingDataAsync(ConverterContext context, ModelBindingData modelBindingData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 63
- at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptions.CreateClient() in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptions.cs:line 35
- at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
```

In my `local.settings.json` I have added the settings as per described here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger (section "Identity-based connections").

Is Managed Identity with EventGrid source for Blob Trigger Azure Function supported ?

**Comment by gp-nttdata** [comment]
@fabiocav Hello again.
I am coming back in just to check if there has been any investigation going on ?
As this functionality is very important to us, I would be really glad if you could share any update on the ticket? 

Thanks again for your help and cooperation.
Kind regards.

**Comment by hunderi** [comment]
This is an issue for us as well.
```
.NET: 7
Function SDK: 4
Blob Extension Version: 6.2.0
Process Mode: Isolated
```

If I use a managed identity connection and BlobTrigger I get the same error:
```
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for 
Function 'IngestFunction': Cannot convert input parameter 'stream' to type 'System.IO.Stream' from type 
'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.ArgumentNullException: Value cannot 
be null. (Parameter 'connectionString')
```

The connectionstring parameter is stored with the `__serviceUri` suffix.

Attribute binding:
```
public async Task UploadFile([BlobTrigger("archive-json/{name}", 
Connection = "StorageAccountConnectionString")] Stream stream, string name)
```


We will move away from manged identity and back to using a storage key for the time being.

**Comment by kurt-mueller-osumc** [comment]
Hi @hunderi and @gp-nttdata, 

I ran into this exact same problem and I managed to get my blob trigger working by enabling the blob storage extension. You can find an official azure function template example here: 

https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/ProjectTemplate_v4.x/FSharp-Isolated/Program.fs

Specifically, I enabled this line:

```fsharp
appBuilder.ConfigureBlobStorageExtension() |> ignore
```

**Comment by NathanAWhitworth** [comment]
We also ran into this issue while using the `serviceUri` form and the Queue access seems to have been the problem.

> The blob trigger handles failure across multiple retries by writing [poison blobs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger#poison-blobs) to a queue. In the serviceUri form, the AzureWebJobsStorage connection is used.

https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger#identity-based-connections

We were using Azurite for `AzureWebJobsStorage` when testing this, which doesn't appear to work with this setup.

Passing `blobServiceUri` and `queueServiceUri` separately (both pointing to a storage account) and assigning `Storage Queue Data Contributor` on the account got it working.

**Comment by MatthiasVnh** [comment]
Is there any update on this ticket?
I have just recently run into this very same issue when upgrading from .NET 6 (in-process) to .NET 8 (Isolated).

**Comment by rav4coding** [comment]
I got same issue when upgrading from .NET 6 (in-process) to .NET 8 (Isolated). 
It works if I switch back to full connection string (with key).

**Comment by ZurenoC** [comment]
I'm also very interested in this issue, connection string works perfectly. Using "blobservice__serviceUri": "https://<mystorageaccount>.blob.core.windows.net/", it fires when it detects a file, but doesn't even get to the methods { before failing.

**Comment by ibis7** [comment]
Having the same problem upgrading from .NET 6 in-process to .NET 8 isolated

**Comment by enzosambucetti** [comment]
Same problem here.

**Comment by pianomanjh** [comment]
> Having the same problem upgrading from .NET 6 in-process to .NET 8 isolated.
> 
> Edit:
> 
> What @NathanAWhitworth said works, in the Function Environment Variables I had to add two new ones:
> 
> StorageAccountConnection__blobServiceUri and StorageAccountConnection__queueServiceUri
> 
> With those variables it should work fine (you should also check the roles, in my case I already had those)

@ibis7 Did you have MyConnection__serviceUri and MyConnection__blobServiceUri pointing to the same url?  I've also run into this issue.

**Comment by ibis7** [comment]
@pianomanjh I don't remember the initial value of serviceUri, but blobServiceUri and queueServiceUri ended up with different urls (one pointing to the queue service and the other one to the blob service). We also were able to remove the old serviceUri variable.
Regarding the storage account, we are pointing to a different one from the function storage account.

**Comment by DC0507** [comment]
Hello everyone, I was working hard with @pianomanjh to get the right approach to enable Managed Identity for his Blob Trigger. 

Finally, we got it with the below steps:

[Steps.pdf](https://github.com/user-attachments/files/16716918/Steps.pdf)

Any questions or comments, feel free to reach me out.

**Comment by kurt-mueller-osumc** [comment]
> Hello everyone, I was working hard with @pianomanjh to get the right approach to enable Managed Identity for his Blob Trigger.
> 
> Finally, we got it with the below steps:
> 
> [Steps.pdf](https://github.com/user-attachments/files/16716918/Steps.pdf)
> 
> Any questions or comments, feel free to reach me out.

@DC0507 unfortunately I don't have the necessary permissions to access the doc.

**Comment by DC0507** [comment]
Hi, @kurt-mueller-osumc. I updated the file. Please let me know if you can view the contents. If no, I could paste here the steps.

**Comment by kurt-mueller-osumc** [comment]
No joy. Now I get prompted to sign in to my microsoft account.

**Comment by DC0507** [comment]
Testing resources:
 
•	Function App: dotnet-isolated-test
•	Storage Account: devtestingba05
 
1.	In my Function App, I enabled Managed Identity (System Assigned): 
2.	In the Storage Accout (IAM) blade, I added the three roles: Storage Blob Data Owner, Storage Account Contributor and Storage Queue Data Contributor.
3.	In my code, I left the prefix of my Storage Account (devtestingba05_STORAGE): 
5.	In the App Settings, I modify the AzureWebJobsStorage setting and value. Also, I added the required settings for the blob and queue:
 
"name": AzureWebJobsStorage__accountname",
"value": "devtestingba05" #The name of your Storage Account
 
 
"name": "devtestingba05_STORAGE__blobServiceUri" #StorageAccountName_STORAGE__blobServiceURI
"value": "https://devtestingba05.blob.core.windows.net/" #https://StorageAccountName.blob.core.windows.net/
 
"name": "devtestingba05_STORAGE__queueServiceUri" #StorageAccountName_STORAGE__queueServiceURI
"value": "https://devtestingba05.queue.core.windows.net/" #https://StorageAccountName.queue.core.windows.net/

**Comment by pianomanjh** [comment]
Note, I was able to get the blob trigger and Stream parameter working with just the `MyAccount__blobServiceUri` and `MyAccount__queueServiceUri` configuration set.  (Set to the triggering blob account).  I did not need the `__accountname`.  I also have not attempted to use Managed Identity for the actual AzureWebJobs storage account yet.

**Comment by liliankasem** [comment]
Hey folks, for general blob binding use with managed identity, I'm going to share the same guidance I wrote up [here](https://github.com/Azure/Azure-Functions/issues/2504#issuecomment-2477253418):

If you are using a `BlobTrigger` binding, the `queueServiceUri` _must_ also be provided as mentioned in the docs:

>1 <CONNECTION_NAME_PREFIX>__blobServiceUri can be used as an alias. If the connection configuration will be used by a blob trigger, blobServiceUri must also be accompanied by queueServiceUri. See below.

([docs link](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-csharp#identity-based-connections))

If you've configured system managed identity, you will need both of these for a `BlobTrigger` to work:

- <CONNECTION_NAME_PREFIX>__blobServiceUri
- <CONNECTION_NAME_PREFIX>__queueServiceUri

If you're using a `BlobInput` binding (without a blob trigger), the service uri alone should be sufficient:

- <CONNECTION_NAME_PREFIX>__serviceUri

----

As for the original issue, I think this is specifically asking about the new EventGrid source for blob bindings, correct? @gp-nttdata, just to make sure I'm clear on my investigation: are you still experiencing this today with all the latest bits, and the above guidance does not work for you? If so, I'll work on a repro and look into this soon.

**Comment by mattchenderson** [comment]
While I have not personally seen the error mentioned in the original post, I can assert some confusing behavior in terms of permissions requirements. It seems like the event grid mode may still require the permissions needed to perform scanning, which is not expected. That issue is not something we'd track here on the worker, and a new item may be needed for that elsewhere, but I did want to flag it in case anyone arrives at this issue as a result.

**Comment by liliankasem** [comment]
@mattchenderson can you open another issue to track that?

Going to close this issue as I haven't heard from the original author in almost a year. If you're facing a similar issue, please open a new issue with as many details as possible. Thanks.
