### ISSUE TITLE
Default BlobTrigger function from F# dotnet-isolated template throws FunctionInputConverterException

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [Azure/azure-functions-dotnet-worker#1907]
# Summary

The default `BlobTrigger` function from the F# dotnet-isolated template throws a `Microsoft.Azure.Functions.Worker.FunctionInputConverterException` whenever it is triggered.  

## Azure Function Version

```bash
% func

Azure Functions Core Tools
Core Tools Version:       4.0.5348 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.24.5.21262
```

## Code

I have a public repository where I can replicate this error on a Macbook Pro, Surface Laptop, and inside a docker container on a Surface Laptop:

https://github.com/kurt-mueller-osumc/blob-triggered-function/blob/main/ReadBlob.fs

```fsharp
namespace Comrit.Functions

open System
open System.IO
open Microsoft.Azure.Functions.Worker
open Microsoft.Extensions.Logging

module ReadBlob =

    [<Function("ReadBlob")>]
    let run
        (
            [<BlobTrigger("samples-workitems/{name}", Connection = "")>] myBlob: Stream,
            name: string,
            context: FunctionContext
        ) =
        let logger
            = context.GetLogger "ReadBlob"

        use blobStreamReader
            = new StreamReader(myBlob)

        let blobContent
            = blobStreamReader.ReadToEndAsync()
            |> Async.AwaitTask
            |> Async.RunSynchronously

        let msg =
            sprintf "F# Blob trigger function Processed blob\nName: %s \n Data: %s" name blobContent

        logger.LogInformation msg
```

## Error

As stated, whenever this function is triggered, it will throw an `Microsoft.Azure.Functions.Worker.FunctionInputConverterException`.

```
[2023-09-14T14:10:50.443Z] Function 'ReadBlob', Invocation id 'cc4eef61-0e3d-4287-8651-9767a29dbac8': An exception was thrown by the invocation.
[2023-09-14T14:10:50.443Z] Result: Function 'ReadBlob', Invocation id 'cc4eef61-0e3d-4287-8651-9767a29dbac8': An exception was thrown by the invocation.
[2023-09-14T14:10:50.443Z] Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'ReadBlob': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
[2023-09-14T14:10:50.443Z]    at Azure.Storage.StorageConnectionString.Parse(String connectionString)
[2023-09-14T14:10:50.443Z]    at Azure.Storage.Blobs.BlobServiceClient..ctor(String connectionString, BlobClientOptions options)
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptions.CreateClient() in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptions.cs:line 35
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.CreateBlobContainerClient(String connectionName, String containerName) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 253
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertModelBindingDataAsync(Type targetType, BlobBindingData blobData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 118
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertFromBindingDataAsync(ConverterContext context, ModelBindingData modelBindingData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 63
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 42
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2023-09-14T14:10:50.444Z] Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 42
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-09-14T14:10:50.444Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77.
[2023-09-14T14:10:50.458Z] Executed 'Functions.ReadBlob' (Failed, Id=cc4eef61-0e3d-4287-8651-9767a29dbac8, Duration=113ms)
[2023-09-14T14:10:50.458Z] System.Private.CoreLib: Exception while executing function: Functions.ReadBlob. System.Private.CoreLib: Result: Failure
[2023-09-14T14:10:50.458Z] Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'ReadBlob': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
[2023-09-14T14:10:50.458Z]    at Azure.Storage.StorageConnectionString.Parse(String connectionString)
[2023-09-14T14:10:50.458Z]    at Azure.Storage.Blobs.BlobServiceClient..ctor(String connectionString, BlobClientOptions options)
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.BlobStorageBindingOptions.CreateClient() in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\Config\BlobStorageBindingOptions.cs:line 35
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.CreateBlobContainerClient(String connectionName, String containerName) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 253
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertModelBindingDataAsync(Type targetType, BlobBindingData blobData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 118
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.BlobStorageConverter.ConvertFromBindingDataAsync(ConverterContext context, ModelBindingData modelBindingData) in D:\a\_work\1\s\extensions\Worker.Extensions.Storage.Blobs\src\BlobStorageConverter.cs:line 63
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 42
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2023-09-14T14:10:50.458Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
[2023-09-14T14:10:50.459Z] Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 105
[2023-09-14T14:10:50.459Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 42
[2023-09-14T14:10:50.459Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-09-14T14:10:50.459Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2023-09-14T14:10:50.459Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.
```

**Comment by kshyju** [comment]
See #1899 

Can you try to use the extension method mentioned there manually inside your main method?

**Comment by kurt-mueller-osumc** [comment]
Hi @kshyju, thank you for pointing this out to me. This works 😄.

**Comment by kshyju** [comment]
Great! Closing as answered.

**Comment by kurt-mueller-osumc** [comment]
Hey kshyju, why I am grateful this is working, how is this not a bug? I generated a default template and function and received a cryptic error message. When I generate a `BlobTriggered` function, I receive compiler errors telling me that certain libraries cannot be found. I then have to go add those library's manifest. 

But this except isn't particularly helpful and, imo, doesn't lead me down the right path to fix the issue:

```bash
[2023-09-14T14:10:50.443Z] Function 'ReadBlob', Invocation id 'cc4eef61-0e3d-4287-8651-9767a29dbac8': An exception was thrown by the invocation.
[2023-09-14T14:10:50.443Z] Result: Function 'ReadBlob', Invocation id 'cc4eef61-0e3d-4287-8651-9767a29dbac8': An exception was thrown by the invocation.
[2023-09-14T14:10:50.443Z] Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'ReadBlob': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
```

**Comment by kshyju** [comment]
@kurt-mueller-osumc Yes, this is a bug at the moment. The issue I linked above is to track the work to fix the VS templates so you do not need to do this manually & public documentation.

We also accept contributions from the community. So If you are up for it, please feel free to make a contribution to fix docs/templates. Thanks!
