### ISSUE TITLE
Failed to start a new language worker for runtime: dotnet-isolated, Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-functions-dotnet-worker#1920]
I have the following **.NET 7 Isolated** Azure Function.

#### Azure Function Core Tools
```
Core Tools Version:       4.0.5348 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.24.5.21262
```
#### csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.10.1" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.Functions.Worker" Version="6.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.14.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```
#### Program.cs
```csharp
using Azure.Identity;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

IHost host = new HostBuilder()
    .ConfigureAppConfiguration((hostingContext, builder) =>
    {
        var aacEndpoint = "<aac-endpoint>";
        var keyPrefix = "<key-prefix>";
        var label = "<label>";
        
        var azureCredential = new DefaultAzureCredential();

        builder
            .AddAzureAppConfiguration(options =>
            {
                options
                    .Connect(new Uri(aacEndpoint), azureCredential)
                    .Select($"{keyPrefix}*", Microsoft.Extensions.Configuration.AzureAppConfiguration.LabelFilter.Null)
                    .Select($"{keyPrefix}*", label)
                    .TrimKeyPrefix(keyPrefix)
                    .ConfigureKeyVault(kv =>
                    {
                        kv.SetCredential(azureCredential);
                    });
            });
    })
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices((hostingContext, services) =>
    {
        IConfiguration configuration = services.BuildServiceProvider().GetService<IConfiguration>();
        
        // TODO: Check configuration
    })
    .Build();

Console.WriteLine("Starting host...");

host.Run();
```
Now when I run this, I am getting the following error.
```
Host lock lease acquired by instance ID '000000000000000000000000CF6A328F'.
Starting worker process failed
Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
Failed to start a new language worker for runtime: dotnet-isolated.
Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
Starting worker process failed
Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
```
#### StackTrace
```
Unhandled exception. System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1557
--- End of stack trace from previous location ---
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 283
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 152
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 144
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.StartWorkerChannel(String runtime) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 583
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.StartWorkerChannel(String runtime) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 595
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.DisposeAndRestartWorkerChannel(String runtime, String workerId, Exception workerException) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 545
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.WorkerError(WorkerErrorEvent workerError) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 459
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```
#### Additional Notes:
* I have access to Azure App Configuration (AAC). 
* AAC contains `KeyVault` references and all the permissions are configured.

**Comment by jaliyaudagedara** [comment]
Similar issue: 
   Failed to start a new language worker for runtime: dotnet-isolated #1458 

+ @satvu

**Comment by kshyju** [comment]
@jaliyaudagedara The `Program.cs` code you shared above does not look like a valid startup code for a dotnet-isolated function app. Usuaully the startup code will have a call to `ConfigureFunctionsWorkerDefaults` method call on the `IHostBuilder` instances. See sample [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/de3e2a07473061dbac99f75a95dd19bbc52bc26f/samples/Net7Worker/Program.cs#L6-L10)

I suggest you to create a new function app using Visual studio New->Function App template, which will give you the minimal code needed for your function app to work and slowly adding your app specific code in a binary search fashion (add half of the code and see it works. If it still fails trim it to even half). In this way you will be able to figure out which part of your code is causing the failure.

**Comment by jaliyaudagedara** [comment]
@kshyju, I’m sorry, ConfigureFunctionsWorkerDefaults() is there after ConfigureAppConfiguration. 

Have missed it as part of code formatting.

**Comment by FahaoTang** [comment]
This issue also occurs to latest .NET 8 Azure Functions Apps for both hosting in consumption plan environment or Azure Container App environment. Refer to this one for details: https://github.com/Azure/azure-functions-on-container-apps/issues/34

**Comment by FahaoTang** [comment]
> This issue also occurs to latest .NET 8 Azure Functions Apps for both hosting in consumption plan environment or Azure Container App environment. Refer to this one for details: [Azure/azure-functions-on-container-apps#34](https://github.com/Azure/azure-functions-on-container-apps/issues/34)

I have added this issue to this bug one: https://github.com/Azure/azure-functions-dotnet-worker/issues/1920

**Comment by FahaoTang** [comment]
> @jaliyaudagedara The `Program.cs` code you shared above does not look like a valid startup code for a dotnet-isolated function app. Usuaully the startup code will have a call to `ConfigureFunctionsWorkerDefaults` method call on the `IHostBuilder` instances. See sample [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/de3e2a07473061dbac99f75a95dd19bbc52bc26f/samples/Net7Worker/Program.cs#L6-L10)
> 
> I suggest you to create a new function app using Visual studio New->Function App template, which will give you the minimal code needed for your function app to work and slowly adding your app specific code in a binary search fashion (add half of the code and see it works. If it still fails trim it to even half). In this way you will be able to figure out which part of your code is causing the failure.

I do have ConfigureFunctionsWorkerDefaults in my code but it fails and it was running ok previously as isolated. 

```
using Kontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.Reflection;

namespace Kontext.Azure.Functions
{
    public class Program
    {
        public static void Main()
        {
            var dbConnString = Environment.GetEnvironmentVariable("***");
            var host = new HostBuilder()
                    .ConfigureAppConfiguration(config =>
                    {
                        config.AddJsonFile("appsettings.json", false, false).AddEnvironmentVariables().Build();
                    })
                    .ConfigureFunctionsWorkerDefaults()
                    .ConfigureServices(services =>
                    {
                        services.AddOptions<MailingOptions>().Configure<IConfiguration>((settings, configuration) => configuration.GetSection("AppConfig:MailingConfig").Bind(settings));
                        services.AddOptions<SubscriptionOptions>().Configure<IConfiguration>((settings, configuration) => configuration.GetSection("AppConfig:Subscription").Bind(settings));
                        services.AddSingleton<IMemoryCache, MemoryCache>();
                        services.AddSingleton<IHtmlSanitizer, DefaultHtmlSanitizer>();
                        services.AddDbContext<ApplicationDbContext>(options =>
                        options.UseSqlServer(
                           dbConnString, b => b.MigrationsAssembly("Kontext.Data.Migrations")));
                        services.AddEntityFrameworkStores<int, ApplicationDbContext>();
                        services.AddSubscriptionService();
                        services.AddAutoMapper(Assembly.GetCallingAssembly(), Assembly.GetAssembly(typeof(DefaultMapperProfile)));
                        services.AddScoped<SubscriptionManager>();
                        services.AddScoped<MessageManager>();
                        // For IStringLocalizer
                        services.AddLocalization();

                    })
                    .Build();

            host.Run();
        }
    }
}

```

**Comment by kshyju** [comment]
@FahaoTang Just to confirm. Everything was working fine for you and then you started getting this error? Did you do a new deployment from a platform where .NET8 RC1 bits are present? Liked I mentioned in the other issue, .NET RC1 deployment to functions environment is still in progress. So that might be one cause for a failed startup of the isolated language worker. Can you check your AI logs to see what error details are you seeing there?

**Comment by FahaoTang** [comment]
> @FahaoTang Just to confirm. Everything was working fine for you and then you started getting this error? Did you do a new deployment from a platform where .NET8 RC1 bits are present? Liked I mentioned in the other issue, .NET RC1 deployment to functions environment is still in progress. So that might be one cause for a failed startup of the isolated language worker. Can you check your AI logs to see what error details are you seeing there?


Hi @kshyju I am building my own docker image using 
`FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0 AS base` in MCR. I just tested locally, it looks like it is because this image only includes framework of `8.0.0-preview.7.23375.6` while I am trying to use  `Framework: 'Microsoft.NETCore.App', version '8.0.0-rc.1.23419.4'`? And is this because what you mentioned? i.e. .NET 8 RC1 is not published yet into MCR. So if I roll it back to  `8.0.0-preview.7.23375.6`  it should work?

```
2023-09-23 13:52:18       The following frameworks were found:
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18         8.0.0-preview.7.23375.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```


Full error when running custom image locally:

```
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       Framework: 'Microsoft.NETCore.App', version '8.0.0-rc.1.23419.4' (x64)
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       .NET location: /usr/share/dotnet/
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       The following frameworks were found:
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18         8.0.0-preview.7.23375.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       Learn more:
2023-09-23 13:52:18 fail: Host.Function.Console[0]
2023-09-23 13:52:18       https://aka.ms/dotnet/app-launch-failed
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       To install missing framework, download:
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0-rc.1.23419.4&arch=x64&rid=linux-x64&os=debian.12
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       You must install or update .NET to run this application.
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       App: /home/site/wwwroot/Kontext.Azure.Functions.dll
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       Architecture: x64
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       Framework: 'Microsoft.NETCore.App', version '8.0.0-rc.1.23419.4' (x64)
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       .NET location: /usr/share/dotnet/
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       The following frameworks were found:
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18         8.0.0-preview.7.23375.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       Learn more:
2023-09-23 13:52:18 fail: Host.Function.Console[0]
2023-09-23 13:52:18       https://aka.ms/dotnet/app-launch-failed
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       To install missing framework, download:
2023-09-23 13:52:18 info: Host.Function.Console[0]
2023-09-23 13:52:18       https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0-rc.1.23419.4&arch=x64&rid=linux-x64&os=debian.12
2023-09-23 13:52:18 fail: Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
2023-09-23 13:52:18       Failed to start a new language worker for runtime: dotnet-isolated.
2023-09-23 13:52:18       System.Threading.Tasks.TaskCanceledException: A task was canceled.
2023-09-23 13:52:18          at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 283
2023-09-23 13:52:18          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 152
2023-09-23 13:52:18          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 144
2023-09-23 13:52:18          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(IEnumerable`1 languages) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 135
2023-09-23 13:52:18          at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.<>c__DisplayClass55_0.<<StartWorkerProcesses>b__0>d.MoveNext() in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 215
```

**Comment by kshyju** [comment]
@FahaoTang 
> .NET 8 RC1 is not published yet into MCR. So if I roll it back to 8.0.0-preview.7.23375.6 it should work?

Correct. The deployment of NET 8 RC1 bits is in progress and should be available be early next week.

**Comment by FahaoTang** [comment]
> @FahaoTang
> 
> > .NET 8 RC1 is not published yet into MCR. So if I roll it back to 8.0.0-preview.7.23375.6 it should work?
> 
> Correct. The deployment of NET 8 RC1 bits is in progress and should be available be early next week.

It doesn't work for me. I've now decided to roll back all my changes to .NET 7 and will only migrate to .NET 8 when it is stable.

**Comment by jaliyaudagedara** [comment]
I know this is weird, but somehow my project is working fine now 😐.

**Comment by kshyju** [comment]
Closing as OP's original problem seems to disappear. Please open a new issue if you run into other issues.
