### ISSUE TITLE
When using ASP.NET Core integration, ObjectDisposedException is thrown when the request is cancelled

### ISSUE THREAD

**Issue by xin9le** [Azure/azure-functions-dotnet-worker#1929]
# Summary

When using ASP.NET Core integration, if a request thrown to an HttpTrigger developed is cancelled by the client side, an `ObjectDisposedException` occurs. The stack trace is as follows. This does not occur when ASP.NET Core integration is not used.

## Stack trace
```
System.Private.CoreLib: Exception while executing function: Functions.Http_Sample. System.Private.CoreLib: Result: Failure
Exception: System.ObjectDisposedException: Request has finished and HttpContext disposed.
 Object name: 'HttpContext'.
    at Microsoft.AspNetCore.Http.DefaultHttpContext.ThrowContextDisposed()
    at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Features()
    at Microsoft.AspNetCore.Routing.RoutingHttpContextExtensions.GetRouteData(HttpContext httpContext)
    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 52
    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at Microsoft.AspNetCore.Http.DefaultHttpContext.ThrowContextDisposed()
    at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Features()
    at Microsoft.AspNetCore.Routing.RoutingHttpContextExtensions.GetRouteData(HttpContext httpContext)
    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 52
    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.
```

## Applicable section
- https://github.com/Azure/azure-functions-dotnet-worker/blob/40d73ee8107eb48c63bcaef868522fcbcaf0d549/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs#L52C100-L52C100

# Excpected behavior

- Terminate the request appropriately without causing an `ObjectDisposedException`.

# Reproduction code

- [HttpContextDisposedSample.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/12721060/HttpContextDisposedSample.zip)

```cs
using Microsoft.Extensions.Hosting;

var host
    = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .Build();
host.Run();
```

```cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;

namespace FunctionApp2;

public class Http_Sample
{
    private readonly ILogger _logger;

    public Http_Sample(ILoggerFactory loggerFactory)
    {
        _logger = loggerFactory.CreateLogger<Http_Sample>();
    }

    [Function(nameof(Http_Sample))]
    public async Task<IActionResult> EntryPoint(
        [HttpTrigger(AuthorizationLevel.Function, "get", Route = "sample")] HttpRequest request,
        FunctionContext context)
    {
        // note:
        //  - ObjectDisposedException is thrown when the request is cancelled.

        try
        {
            var delay = TimeSpan.FromSeconds(10);
            await Task.Delay(delay, context.CancellationToken);
            return new OkResult();
        }
        catch (Exception ex)
        {
            this._logger.LogWarning(ex, "Error occurred");
            return new StatusCodeResult(500);
        }
    }
}
```

**Comment by jviau** [comment]
Looking at our code, I believe the culprit is this: https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Http.AspNetCore/src/Coordinator/ContextReference.cs#L38

We are registering cancellation callbacks. I don't think we should be doing that. Our AspNetCore HTTP pipeline should not at any point manually handle the cancellation token. It should be entirely up to the customer to decide when, if, and how they observe that cancellation token. Anything we need to cleanup as part of cancellation should be done as the stack unwinds.

@satvu @brettsam

**Comment by douglasware** [comment]
I am observing this behavior independently of any cancellation I can see while debugging simply by calling 

`return new OkObjectResult(message); `

Where message is a POCO. This only happens in the deployed version of the function, never with the local, and the behavior is 100% with the particular function. Everything works right up until the call to return.

**Comment by aivdov** [comment]
Any ETA when is this going to be fixed?

**Comment by satvu** [comment]
@douglasware Can you share a minimal repro (preferably GitHub repo link)? For the deployed version, could you also share your app name privately using [these instructions](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately). Additionally, what core-tools version are you using locally to test? If the cause is separate from the original post, we will open a new issue with more details to track. Thanks!

@aivdov Could you share a bit more about your scenario? A minimal repro and a description of the behavior would help with investigation. Thanks!

**Comment by satvu** [comment]
Additionally - @xin9le, @douglasware, @aivdov are errors occurring for every invocation or intermittently?

**Comment by xin9le** [comment]
@satvu 
Based on my experience using ASP.NET Core Integration in a production environment, it is only "*occasionally detected*". While it is not catastrophic, I do recognize that it is an exception that should not normally occur (= should not be detected).

**Comment by satvu** [comment]
**Update:** the investigation for this issue has revealed a larger problem that would require a design review and subsequent refactoring. We will skip the temporary mitigation as it only prevents some scenarios of this error message and introduces new behaviors that differ from the desired end result of a long-term fix. 

To follow progress on long-term fix items, you can follow #2180 and #2189.

**Comment by xin9le** [comment]
Thank you for your investigation. I understand that handling cancellations can be a challenging issue, but I also look forward to seeing improvements.

**Comment by rochapablo** [comment]
+1

**Comment by dfjetcharge** [comment]
+1

**Comment by nadershamma** [comment]
I'm still getting this error on azure

`Result: Failure Exception: System.ObjectDisposedException: Request has finished and HttpContext disposed. Object name: 'HttpContext'. at Microsoft.AspNetCore.Http.DefaultHttpContext.ThrowContextDisposed() at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Features() at Microsoft.AspNetCore.Routing.RoutingHttpContextExtensions.GetRouteData(HttpContext httpContext) at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 54 at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77 at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88 Stack: at Microsoft.AspNetCore.Http.DefaultHttpContext.ThrowContextDisposed() at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Features() at Microsoft.AspNetCore.Routing.RoutingHttpContextExtensions.GetRouteData(HttpContext httpContext) at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 54 at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77 at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88`

**Comment by satvu** [comment]
We've made a lot of changes in this area in the past few months, including fixes in both the host and the extension package related to cancellation flow and error handling. I am unable to repro this error again with the original repro code provided (despite being able to previously) with the latest host version and extension package. 

Will let the bot close this unless there are any additional reports/complaints with the latest bits.

**Comment by xin9le** [comment]
@satvu 
I extend my sincere gratitude for your prolonged assistance in this matter. In the production environment under my management, it appears that the detection of `ObjectDisposedException` has significantly decreased at present. I intend to update the NuGet Package to the latest version once again and observe the situation for a period of time.

**Comment by xin9le** [comment]
@satvu
We updated `Microsoft.Azure.Functions.Worker` to v1.23.0 on 2024/08/16 and continued our service operations. However, it appears that the issue recurred once on 2024/08/22. We hope this information can serve as useful feedback.

![image](https://github.com/user-attachments/assets/5f0950bb-2094-492c-b723-66ee91146f63)

**Comment by ybadragon** [comment]
My company is also running into this same issue, it started occurring after moving our azure function over to dotnet isolated on 9/13

**Comment by wjdavis5** [comment]
@im-samz  - Wanted to tag you on this one. About to open a case here for a function in WestUS.
