### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0

### ISSUE THREAD

**Issue by sh-jthorpe** [Azure/azure-functions-dotnet-worker#1950]
I'm getting this exception when calling an HttpTrigger. I just switched this function to use the isolated worker.

Function works fine when running locally.

Application insight exception info:

timestamp [UTC]
2023-10-09T09:33:58.3723328Z
problemId
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
type
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException
assembly
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
method
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
outerType
Microsoft.Azure.WebJobs.Host.FunctionInvocationException
outerMessage
Exception while executing function: Functions.Testb
outerAssembly
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
outerMethod
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
innermostType
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException
innermostMessage
Result: Failure
Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context)
at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack: at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context)
at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
innermostAssembly
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
innermostMethod
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw

FUNCTIONS_EXTENSION_VERSION: "~4"
FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
linuxFxVersion: "DOTNET-ISOLATED|6.0"

- Using dotnet 6
- I don't have any package reference to Microsoft.Azure.WebJobs.*

csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>Enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.15.0" OutputItemType="Analyzer" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.0.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    </ItemGroup>
    <ItemGroup>

        <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </None>
    </ItemGroup>
</Project>
```

Program.cs: I've removed a lot of code to see if i can get it working:

```
using Microsoft.Extensions.Hosting;

IHost host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .Build();

host.Run();
```

I've also tried adding `<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="7.0.0"/>`
and `<FunctionsPreservedDependencies Include="System.Diagnostics.DiagnosticSource.dll" />`

I've spent the whole day on this, and other issues with switching from dotnet isolated. What a headache :)

**Comment by aaslan-saltagroup** [comment]
So I reverted these two back:

```
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
```

It seems the culprit is in the dependencies after you upgrade from these version on, because then the updates bring `System.Diagnostics.DiagnosticSource` 7.0.0.0 with it:

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/140737334/04ae4ed0-9043-45b0-bc21-3660998a4c2e)


This is also true for any dependencies that have `Azure.Core` `v1.36` or later

**Comment by nboeckmann** [comment]
Hi,

there's another way of solving this. Add the following to your csproj file and it will not clear out the library when creating the package that is being pushed to the function.

```
  <ItemGroup>
    <FunctionsPreservedDependencies Include="System.Diagnostics.DiagnosticSource.dll"/>
  </ItemGroup>
```

Nils

**Comment by munkii** [comment]
> I faced the same issue when using the Azure DevOps pipeline to publish to Azure. When publishing from VS2022, it was working correctly.
> 
> The error was:
> 
> ```
> Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=...'. The system cannot find the file specified.
> ```
> 
> Comparing the differences between the pipeline package and the VS package, I could see that the **System.Diagnostics.DiagnosticSource.dll** was in version 6 for the pipeline and version 7 for the VS package.
> 
> I checked my function app dependencies: ![image](https://private-user-images.githubusercontent.com/17547143/290324530-901704d8-53bc-4d03-b540-6b69efde9b80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Nzc0MTUsIm5iZiI6MTcwNDQ3NzExNSwicGF0aCI6Ii8xNzU0NzE0My8yOTAzMjQ1MzAtOTAxNzA0ZDgtNTNiYy00ZDAzLWI1NDAtNmI2OWVmZGU5YjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE3NTE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YmUyZWU2NjNiNWM1MjM4NWMxZWIxYmU4NWIyYjE1YTIyNzU1ZGIwYmE4ZTFlYjIwNDMyYzQ5MzlkOGMzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OVO4SnJ4EXA8vKw8fdUmadRwfyJXBs3xlN-zwsLH2gE)
> 
> And found that EF > SqlClient have the same dependency but version 6: ![image](https://private-user-images.githubusercontent.com/17547143/290325255-ddc60714-c204-4766-a8ff-ff860529a5d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Nzc0MTUsIm5iZiI6MTcwNDQ3NzExNSwicGF0aCI6Ii8xNzU0NzE0My8yOTAzMjUyNTUtZGRjNjA3MTQtYzIwNC00NzY2LWE4ZmYtZmY4NjA1MjlhNWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE3NTE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZWIyOTAzNGUyYTVhOWU4OTQ2Y2ZjOWFiZGI1ZDM2NTAyNmNlMTRjNzQwYzY4MzQ3MjRhNzIyNTBjMTE5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MTUHXbYKOX7VDz8t89FlohdCH14uXEFBARKTGWlfSEs)
> 
> So, I came across this issue [dotnet/sdk#3886](https://github.com/dotnet/sdk/issues/3886) and changed my publish command to:
> 
> ```yaml
>   - task: DotNetCoreCLI@2
>     displayName: "dotnet publish "
>     inputs:
>       command: publish
>       projects: '**/MyFunctionApp.csproj'
>       arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
>       publishWebProjects: false
>       zipAfterPublish: True
> ```
> 
> This solved my problem.

@KelvisGama what did you change in your publish command?

**Comment by KelvisGama** [comment]
@munkii I just specified the project input
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/17547143/2431b89b-9b3b-41fc-9979-3dc97cf0d50c)

**Comment by fabiocav** [comment]
Following up on this issue and wanted to validate whether this is something you're still seeing. There was an issue with one of the extensions when this was opened, but that should no longer be a problem. Can you please confirm?

Thanks!

**Comment by munkii** [comment]
FWIW we certainly do not see this issue anymore
