### ISSUE TITLE
Initializing worker process failed / System.TimeoutException: The operation has timed out.

### ISSUE THREAD

**Issue by davidpetric** [Azure/azure-functions-dotnet-worker#1978]
Started to fail randomly, after I changed some code.
   
   Please see logs here for build and console: https://gist.github.com/davidpetric/942ea3c3bc7eafd1b85ddf442ec2dfe3

Visual Studio just crashes without any explanation:

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/13138387/e9b9a2c9-854e-412a-9970-09a9c843769c)

Running ''func start' from project root Fix.csproj in terminal I get:

```c#
Unhandled exception. System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.PendingItem.OnTimeout() in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 1564
--- End of stack trace from previous location ---
   at Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) in /_/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs:line 283
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, IEnumerable`1 languages) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 152  
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(Int32 attemptCount, String language) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 144
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.StartWorkerChannel(String runtime) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 583
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.StartWorkerChannel(String runtime) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 595
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.DisposeAndRestartWorkerChannel(String runtime, String workerId, Exception workerException) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 545
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.WorkerError(WorkerErrorEvent workerError) in /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 459
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
   
   ```
   

   
   .csproj
   
   ```xml
   <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <UserSecretsId>d103f90f-915f-4b49-b8cf-9293eba61b19</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Azure.Data.Tables" Version="12.8.0" />
    <PackageReference Include="Azure.Identity" Version="1.7.0" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Core" Version="1.15.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Abstractions" Version="1.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.5.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.14.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.2.0" />
    <PackageReference Include="Fixflo.WebApi.Client.V2" Version="2.0.1.59455" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="6.0.19" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.6.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="NJsonSchema" Version="10.9.0" />
    <PackageReference Include="FluentValidation" Version="11.5.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.5.2" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\EnvironmentExtensions\Utilites.csproj" />
    <ProjectReference Include="..\..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\..\Persistence\Tenancy.Api.Client\Tenancy.Api.Client.csproj" />
    <ProjectReference Include="..\Qube.Api.Client\Qube.Api.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
   ```
   
   
   

   Program.cs
```c#
using Fix.Api.ApiServices;
using Fix.Api.Data;
using Fix.Api.Profiles;
using Fix.Api.Services;

using Microsoft.Azure.Functions.Worker.Extensions.OpenApi.Extensions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

IHost host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(worker => worker.UseNewtonsoftJson())
    .ConfigureAppConfiguration(builder =>
    {
        builder.SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .AddUserSecrets(Assembly.GetExecutingAssembly(), optional: true);
    })
    .ConfigureServices((context, services) => ConfigureAppServices(services, context.Configuration))
    .Build();

await host.StartAsync();

static void ConfigureAppServices(IServiceCollection services, IConfiguration configuration)
{
    services.Configure<JsonSerializerOptions>(options =>
    {
        options.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
        options.Converters.Add(new JsonStringEnumConverter());
    });

    services.AddHttpClient();

    services.AddScoped<IMessageActionStrategyFactory, MessageActionStrategyFactory>();

    services.AddScoped<IFixQubeSuppliersService, FixQubeSuppliersService>();

    services.RegisterAllAssignableType<IMessageActionStrategy>();

    ConfigureAutoMapper(services);

    services.RegisterDomainServices();

    services.RegisterDbServices(configuration);
}

static void ConfigureAutoMapper(IServiceCollection services)
{
    Assembly assembly = typeof(AddressProfile).Assembly;

    MapperConfiguration config = new(mc => mc.AddMaps(assembly));

    try
    {
        config.AssertConfigurationIsValid();
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
        throw;
    }

    services.AddAutoMapper(assembly);
}

static bool IsDevelopment()
  => string.Equals(EnvironmentName(), "Development", StringComparison.OrdinalIgnoreCase);

static string EnvironmentName()
  => Environment.GetEnvironmentVariable("AZURE_FUNCTIONS_ENVIRONMENT");


```

**Comment by davidpetric** [comment]
Sometimes I get this before it crashes in logs with exception

```cs
Error writing message type WorkerInitRequest to workerId: 1802dc1b-ff71-4fb1-a3b7-47dbcb3dcb5d
Microsoft.AspNetCore.Server.Kestrel.Core: Cannot write to the response body, the response has completed.
Object name: 'HttpResponseStream'.
Host lock lease acquired by instance ID '000000000000000000000000668AF8E7'.
nitializing worker process failed
````

**Comment by davidpetric** [comment]
I was able to fix this issue by changing code in Program.cs from `await host.StartAsync();` to ` host.Run();`

I had lots of changes in code so I wasn't able to figure out what changed until I looked at every change in the commit and saw I changed the code to use StartAsync instead of Run.
