### ISSUE TITLE
ServiceBus triggered function fails on startup on net4.8 after updating Microsoft.Azure.Functions.Worker.Sdk from 1.15.1 to 1.16.1

### ISSUE THREAD

**Issue by Pepsi1x1** [Azure/azure-functions-dotnet-worker#2053]
The following Assembly load fails during start up on net4.8 after updating Microsoft.Azure.Functions.Worker.Sdk from 1.15.1 to 1.16.1

```
[2023-11-10T18:27:53.827Z] Worker failed to load function: 'LmsWorker' with functionId: '265042846'.
[2023-11-10T18:27:53.828Z] Worker failed to load function: 'TokenWorker' with functionId: '1737301676'.
[2023-11-10T18:27:53.828Z] Result: Failure
Exception: System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll' or one of its dependencies. The system cannot find the file specified.[2023-11-10T18:27:53.829Z] Result: Failure
Exception: System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll' or one of its dependencies. The system cannot find the file specified.[2023-11-10T18:27:53.829Z] File name: 'file:///C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll'
[2023-11-10T18:27:53.830Z] File name: 'file:///C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll'
[2023-11-10T18:27:53.831Z]    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.831Z]    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.832Z]    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.832Z]    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.834Z]    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
[2023-11-10T18:27:53.835Z]    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
[2023-11-10T18:27:53.836Z]    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
[2023-11-10T18:27:53.837Z]    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
[2023-11-10T18:27:53.838Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultMethodInfoLocator.GetMethod(String pathToAssembly, String entryPoint) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultMethodInfoLocator.cs:line 27[2023-11-10T18:27:53.839Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultMethodInfoLocator.GetMethod(String pathToAssembly, String entryPoint) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultMethodInfoLocator.cs:line 27[2023-11-10T18:27:53.840Z]    at Microsoft.Azure.Functions.Worker.Definition.GrpcFunctionDefinition..ctor(FunctionLoadRequest loadRequest, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Definition\GrpcFunctionDefinition.cs:line 56
[2023-11-10T18:27:53.841Z]    at Microsoft.Azure.Functions.Worker.Definition.GrpcFunctionDefinition..ctor(FunctionLoadRequest loadRequest, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Definition\GrpcFunctionDefinition.cs:line 56
[2023-11-10T18:27:53.845Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
[2023-11-10T18:27:53.846Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
[2023-11-10T18:27:53.847Z]
[2023-11-10T18:27:53.848Z]
[2023-11-10T18:27:53.849Z] === Pre-bind state information ===
[2023-11-10T18:27:53.849Z] === Pre-bind state information ===
[2023-11-10T18:27:53.850Z] LOG: Where-ref bind. Location = C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll
[2023-11-10T18:27:53.851Z] LOG: Where-ref bind. Location = C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll
[2023-11-10T18:27:53.853Z] LOG: Appbase = file:///C:/$tfs/ISL/Brightspace.Worker.AzFunc/bin/Debug/net48/
[2023-11-10T18:27:53.854Z] LOG: Appbase = file:///C:/$tfs/ISL/Brightspace.Worker.AzFunc/bin/Debug/net48/
[2023-11-10T18:27:53.855Z] LOG: Initial PrivatePath = NULL
[2023-11-10T18:27:53.856Z] LOG: Initial PrivatePath = NULL
[2023-11-10T18:27:53.856Z] Calling assembly : (Unknown).
[2023-11-10T18:27:53.857Z] Calling assembly : (Unknown).
[2023-11-10T18:27:53.858Z] ===
[2023-11-10T18:27:53.861Z] ===
[2023-11-10T18:27:53.861Z] LOG: This bind starts in LoadFrom load context.
[2023-11-10T18:27:53.862Z] LOG: This bind starts in LoadFrom load context.
[2023-11-10T18:27:53.863Z] WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
[2023-11-10T18:27:53.864Z] WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
[2023-11-10T18:27:53.865Z] LOG: Using application configuration file: C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.exe.Config
[2023-11-10T18:27:53.866Z] LOG: Using application configuration file: C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.exe.Config
[2023-11-10T18:27:53.867Z] LOG: Using host configuration file:
[2023-11-10T18:27:53.869Z] LOG: Using host configuration file:
[2023-11-10T18:27:53.869Z] LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
[2023-11-10T18:27:53.870Z] LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
[2023-11-10T18:27:53.871Z] LOG: The same bind was seen before, and was failed with hr = 0x80070002.
[2023-11-10T18:27:53.872Z] LOG: Attempting download of new URL file:///C:/$tfs/ISL/Brightspace.Worker.AzFunc/bin/Debug/net48/Brightspace.Worker.AzFunc.dll.[2023-11-10T18:27:53.873Z]
Stack:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

[2023-11-10T18:27:53.877Z]    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.877Z]
Stack:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.879Z]    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
[2023-11-10T18:27:53.880Z]    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.881Z]    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
[2023-11-10T18:27:53.882Z]    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
[2023-11-10T18:27:53.883Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultMethodInfoLocator.GetMethod(String pathToAssembly, String entryPoint) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultMethodInfoLocator.cs:line 27[2023-11-10T18:27:53.884Z]    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
[2023-11-10T18:27:53.886Z]    at Microsoft.Azure.Functions.Worker.Definition.GrpcFunctionDefinition..ctor(FunctionLoadRequest loadRequest, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Definition\GrpcFunctionDefinition.cs:line 56
[2023-11-10T18:27:53.886Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultMethodInfoLocator.GetMethod(String pathToAssembly, String entryPoint) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultMethodInfoLocator.cs:line 27[2023-11-10T18:27:53.888Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269.
[2023-11-10T18:27:53.889Z]    at Microsoft.Azure.Functions.Worker.Definition.GrpcFunctionDefinition..ctor(FunctionLoadRequest loadRequest, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Definition\GrpcFunctionDefinition.cs:line 56
[2023-11-10T18:27:53.890Z] Worker failed to load function: 'IslWorker' with functionId: '1297590910'.
[2023-11-10T18:27:53.893Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269.
[2023-11-10T18:27:53.894Z] Result: Failure
Exception: System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll' or one of its dependencies. The system cannot find the file specified.[2023-11-10T18:27:53.896Z] File name: 'file:///C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll'
[2023-11-10T18:27:53.897Z]    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.898Z]    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.899Z]    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
[2023-11-10T18:27:53.901Z]    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
[2023-11-10T18:27:53.902Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultMethodInfoLocator.GetMethod(String pathToAssembly, String entryPoint) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultMethodInfoLocator.cs:line 27[2023-11-10T18:27:53.903Z]    at Microsoft.Azure.Functions.Worker.Definition.GrpcFunctionDefinition..ctor(FunctionLoadRequest loadRequest, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Definition\GrpcFunctionDefinition.cs:line 56
[2023-11-10T18:27:53.904Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
[2023-11-10T18:27:53.908Z]
[2023-11-10T18:27:53.909Z] === Pre-bind state information ===
[2023-11-10T18:27:53.910Z] LOG: Where-ref bind. Location = C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.dll
[2023-11-10T18:27:53.911Z] LOG: Appbase = file:///C:/$tfs/ISL/Brightspace.Worker.AzFunc/bin/Debug/net48/
[2023-11-10T18:27:53.913Z] LOG: Initial PrivatePath = NULL
[2023-11-10T18:27:53.915Z] Calling assembly : (Unknown).
[2023-11-10T18:27:53.916Z] ===
[2023-11-10T18:27:53.918Z] LOG: This bind starts in LoadFrom load context.
[2023-11-10T18:27:53.919Z] WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
[2023-11-10T18:27:53.920Z] LOG: Using application configuration file: C:\$tfs\ISL\Brightspace.Worker.AzFunc\bin\Debug\net48\Brightspace.Worker.AzFunc.exe.Config
[2023-11-10T18:27:53.921Z] LOG: Using host configuration file:
[2023-11-10T18:27:53.924Z] LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
[2023-11-10T18:27:53.925Z] LOG: Attempting download of new URL file:///C:/$tfs/ISL/Brightspace.Worker.AzFunc/bin/Debug/net48/Brightspace.Worker.AzFunc.dll.
[2023-11-10T18:27:53.926Z]
Stack:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.927Z]    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-10T18:27:53.928Z]    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
[2023-11-10T18:27:53.929Z]    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
[2023-11-10T18:27:53.930Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultMethodInfoLocator.GetMethod(String pathToAssembly, String entryPoint) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultMethodInfoLocator.cs:line 27[2023-11-10T18:27:53.931Z]    at Microsoft.Azure.Functions.Worker.Definition.GrpcFunctionDefinition..ctor(FunctionLoadRequest loadRequest, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Definition\GrpcFunctionDefinition.cs:line 56
[2023-11-10T18:27:53.932Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269.
```

**Comment by Pepsi1x1** [comment]
Note 1.16.0 seems to have the same issue

**Comment by Pepsi1x1** [comment]
Appears to be the issue described in #2052

**Comment by fabiocav** [comment]
Thank you @Pepsi1x1 . Can you confirm you have the same condition captured in #2052 ? If so, we'll close this as a duplicate and will be releasing that fix soon.

**Comment by Pepsi1x1** [comment]
Hi @fabiocav, I can confirm that the mitigation described in the issue resolved the exception. So I believe it is the same position. Happy to close
