### ISSUE TITLE
Azure Function .NET Framework Isolated V4 fails to start with default project

### ISSUE THREAD

**Issue by cookston** [Azure/azure-functions-dotnet-worker#2082]
Launch VS2022 (Version 17.7.7 VisualStudio.17.Release/17.7.7+34302.85)
Create a new Azure Function project
Select .NET Framework Isolated V4
e.g.
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/2190792/2750b286-01ef-4426-8eff-1c56c8919ec0)
Press Create
Run project

Project runs then immediately crashes.

```

Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

[2023-11-20T18:03:57.589Z] Found D:\dev\scratch\FunctionApp6\FunctionApp6.csproj. Using for user secrets file configuration.
[2023-11-20T18:04:02.089Z] Azure Functions .NET Worker (PID: 35464) initialized in debug mode. Waiting for debugger to attach...
[2023-11-20T18:04:02.134Z] Worker process started and initialized.
[2023-11-20T18:04:02.195Z] Worker failed to load function: 'Function1' with functionId: '3491568611'.
[2023-11-20T18:04:02.196Z] Result: Failure
Exception: System.IO.FileNotFoundException: Could not load file or assembly 'file:///D:\dev\scratch\FunctionApp6\bin\Debug\net48\FunctionApp6.dll' or one of its dependencies. The system cannot find the file specified.
[2023-11-20T18:04:02.196Z] File name: 'file:///D:\dev\scratch\FunctionApp6\bin\Debug\net48\FunctionApp6.dll'
[2023-11-20T18:04:02.197Z]    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-20T18:04:02.197Z]    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-20T18:04:02.198Z]    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
[2023-11-20T18:04:02.199Z]    at System.Reflection.Assembly.LoadFrom(String assemblyFile)

[2023-11-20T18:04:02.199Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultMethodInfoLocator.GetMethod(String pathToAssembly, String entryPoint) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultMethodInfoLocator.cs:line 27
Functions:
[2023-11-20T18:04:02.200Z]    at Microsoft.Azure.Functions.Worker.Definition.GrpcFunctionDefinition..ctor(FunctionLoadRequest loadRequest, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Definition\GrpcFunctionDefinition.cs:line 56

[2023-11-20T18:04:02.202Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
[2023-11-20T18:04:02.203Z]
        Function1: [GET,POST] http://localhost:7014/api/Function1

[2023-11-20T18:04:02.208Z] === Pre-bind state information ===
[2023-11-20T18:04:02.210Z] LOG: Where-ref bind. Location = D:\dev\scratch\FunctionApp6\bin\Debug\net48\FunctionApp6.dll
For detailed output, run func with --verbose flag.
[2023-11-20T18:04:02.211Z] LOG: Appbase = file:///D:/dev/scratch/FunctionApp6/bin/Debug/net48/
[2023-11-20T18:04:02.213Z] LOG: Initial PrivatePath = NULL
[2023-11-20T18:04:02.214Z] Calling assembly : (Unknown).
[2023-11-20T18:04:02.215Z] ===
[2023-11-20T18:04:02.215Z] LOG: This bind starts in LoadFrom load context.
[2023-11-20T18:04:02.216Z] WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
[2023-11-20T18:04:02.218Z] LOG: Using application configuration file: D:\dev\scratch\FunctionApp6\bin\Debug\net48\FunctionApp6.exe.Config
[2023-11-20T18:04:02.219Z] LOG: Using host configuration file:
[2023-11-20T18:04:02.220Z] LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
[2023-11-20T18:04:02.223Z] LOG: Attempting download of new URL file:///D:/dev/scratch/FunctionApp6/bin/Debug/net48/FunctionApp6.dll.
[2023-11-20T18:04:02.225Z]
Stack:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-20T18:04:02.226Z]    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
[2023-11-20T18:04:02.227Z]    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
[2023-11-20T18:04:02.229Z]    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
[2023-11-20T18:04:02.229Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultMethodInfoLocator.GetMethod(String pathToAssembly, String entryPoint) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultMethodInfoLocator.cs:line 27
[2023-11-20T18:04:02.231Z]    at Microsoft.Azure.Functions.Worker.Definition.GrpcFunctionDefinition..ctor(FunctionLoadRequest loadRequest, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Definition\GrpcFunctionDefinition.cs:line 56
[2023-11-20T18:04:02.232Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269.
[2023-11-20T18:04:07.101Z] Host lock lease acquired by instance ID '00000000000000000000000000005F9F'.
```

**Comment by cookston** [comment]
I found that if I change the .csproj package reference, from :

```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.2" />
```

To:

```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.10.0" />
```

Then it seems to work.

**Comment by kshyju** [comment]
@cookston Thanks for reporting. Indeed this was a regression appeared in 1.16.x version. We are working on a fix and will be releasing a new version of the package with the fix. Until then you can mitigate the issue by using version 1.15.1.

**Comment by cookston** [comment]
Thank you!
