### ISSUE TITLE
A host error has occurred during startup operation - related to .NET 8 rollout?

### ISSUE THREAD

**Issue by rodolfograve** [Azure/azure-functions-dotnet-worker#2094]
UK South, Elastic Plan.

No deployments or changes for 2 days. Suddenly, the Function stops today at 12:00 and the log is full of messages like this:

C:\home\LogFiles\Application\Functions\Host> 

```
2023-11-24T14:26:49.301 [Error] A host error has occurred during startup operation '3e909354-c8bb-4c01-8b67-aa6e53709945'.
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.Azure.WebJobs.Script.WorkerFunctionMetadataProvider.GetFunctionMetadataAsync(IEnumerable`1 workerConfigs,Boolean forceRefresh) at /_/src/WebJobs.Script/Host/WorkerFunctionMetadataProvider.cs : 84
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.FunctionMetadataProvider.GetFunctionMetadataAsync(IEnumerable`1 workerConfigs,IEnvironment environment,Boolean forceRefresh) at /_/src/WebJobs.Script/Host/FunctionMetadataProvider.cs : 45
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.LoadFunctionMetadata(Boolean forceRefresh,Boolean includeCustomProviders,IFunctionInvocationDispatcher dispatcher,IList`1 workerConfigs) at /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs : 146
   at Microsoft.Azure.WebJobs.Script.FunctionMetadataManager.GetFunctionMetadata(Boolean forceRefresh,Boolean applyAllowList,Boolean includeCustomProviders,IList`1 workerConfigs) at /_/src/WebJobs.Script/Host/FunctionMetadataManager.cs : 90
   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ExternalConfigurationStartupValidator.Validate(IConfigurationRoot originalConfig) at /_/src/WebJobs.Script/DependencyInjection/ExternalConfigurationStartupValidator.cs : 42
   at Microsoft.Azure.WebJobs.Script.DependencyInjection.ExternalConfigurationStartupValidatorService.StartAsync(CancellationToken cancellationToken) at /_/src/WebJobs.Script/DependencyInjection/ExternalConfigurationStartupValidatorService.cs : 33
   at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation,Int32 attemptCount,JobHostStartupMode startupMode) at /_/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs : 328
```

The evenlog.xml file is full of entries like this:

```
<Event>
        <System>
            <Provider Name="IIS AspNetCore Module V2"/>
            <EventID>1033</EventID>
            <Level>4</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2023-11-24T13:04:44Z"/>
            <EventRecordID>12277296</EventRecordID>
            <Channel>Application</Channel>
            <Computer>pd1sdwk000VWT</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application 'MACHINE/WEBROOT/APPHOST/NEMSPRDP0WEBAPPAUTHFN' has shutdown.</Data>
            <Data>Process Id: 4584.</Data>
            <Data>File Version: 16.0.23292.24. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 2aa401550574f93402eba13ff9a4827ef01a2f3a</Data>
        </EventData>
    </Event>
```

I suspect this is all related to the rollout of .NET 8 (similar to #2075 and #2078)

**Comment by rodolfograve** [comment]
@kshyju Thanks for getting back to me.

The options available to share my app name privately won't work when the host is simply not running. There's nothing listening on that end. No logs are generated. Maybe you should consider adding another way of sharing private data with your team?

In any case, I'm desperate for a solution at this point so I'll share the name of my Function App publicly:

1. Name: nemsdevwebappd0authfn
2. Region: UK South
3. Timestamp: 28/Nov/2023 07:46 (GMT)

The latest "successful" deployment was 27/Nov/2023 9:38AM (GMT). As explained above, accessing the home page shows a 503 error. I just tried the invocation of one of the Functions now: 28/Nov/2023 07:46 (GMT).

**Comment by kshyju** [comment]
@rodolfograve Ack. Thanks for sharing the details. I will investigate. One question- Did you try any other SKUs? like Windows premium/app service or Linux consumption?

**Comment by rodolfograve** [comment]
Thanks, @kshyju.

No, it's not easy for me to try a different SKU because of this issue: https://github.com/Azure/Azure-Functions/issues/155

Re-creating this Function App requires a lot of configuration that we haven't been able to fully automate (integration with Azure AD B2C, Event Grid, etc.)

**Comment by kshyju** [comment]
@rodolfograve Thanks for your patience. I was finally able to look into your app and I do not see any evidence of the app running on 28th. Are you sure the deployment process was successful? What deployment method was used?

The latest logs I see is starting at 2023-11-30 15:58:08.8450064 UTC. I also noticed your app is targeting NET7.

Unfortunately, there were some issues with .NET8 rollout. Not all machines were updated (There are millions of machines which needs to be updated, so it takes time). Currently the team is working to fix that gap and hopefully all machines will have the NET8 bits shortly. See https://github.com/Azure/azure-functions-dotnet-worker/issues/2075#issuecomment-1834754643

**Comment by rodolfograve** [comment]
Hi.

As I have explained before, the app is not running. The host goes down and no process seems to be running as soon as I deploy the .NET 8 version of this.

I do need to keep working so I deployed the .NET 7 version of the Function for a while, before re-deploying the .NET 8.

**Comment by rodolfograve** [comment]
I'm happy to report that things are working OK for me since yesterday, both on Consumption Plan and Elastic. UK South.
