### ISSUE TITLE
Unable to load functions because they already exist after .NET 8 upgrade

### ISSUE THREAD

**Issue by jmbockhorst** [Azure/azure-functions-dotnet-worker#2144]
I am seeing this error after upgrading to .NET 8. When the app starts up it will work for a few minutes, then some of the instances start failing with this error for all functions.

```
Exception: System.InvalidOperationException: Unable to load Function 'Health'. A function with the id '1892054954' name already exists.
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
   at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
Stack:    at Microsoft.Azure.Functions.Worker.FunctionsApplication.LoadFunction(FunctionDefinition definition) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 62
   at Microsoft.Azure.Functions.Worker.GrpcWorker.FunctionLoadRequestHandler(FunctionLoadRequest request, IFunctionsApplication application, IMethodInfoLocator methodInfoLocator) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 269
```

#### Investigative information

- Timestamp: 2023-12-06T15:58:50.861
- Invocation ID: 342b2cca-f3d4-48d2-8d3b-c5567addd0c3
- Region: North Central US

**Comment by fabiocav** [comment]
Moving to .NET worker repo. 

@kshyju for awareness as he is investigating this issue.

**Comment by jackbatzner** [comment]
This is similar to #2124

**Comment by kshyju** [comment]
I am going to close this issue as we have #2124 tracking the work to fix that issue. Thank you!
