### ISSUE TITLE
Isolated Process with DurableClient and ASP.NET Core integration will throw exception on CreateCheckStatusResponse

### ISSUE THREAD

**Issue by Duranom** [Azure/azure-functions-dotnet-worker#2156]
**Description**
This issue is re-raised here as result of discussion in [azure-functions-durable-extension issue: 2683](https://github.com/Azure/azure-functions-durable-extension/issues/2683)

Packages used:
- [Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore v1.1.1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore/1.1.1)
- [Microsoft.Azure.Functions.Worker.Extensions.DurableTask v1.1.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.DurableTask/1.1.0)

When using these versions of the functions packages that provides ASP.NET Core integration and DurableTaskClient, or newer, the method [CreateCheckStatusResponse](https://github.com/Azure/azure-functions-durable-extension/blob/3dd943bc227f5e63a58c3b585400669accd636d7/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs#L46C24-L46C24) will throw an InvalidOperationException because the implementation writes to the `HttpResponseData` through serialization synchronous.

This point has been raised in the (azure-functions-durable-extension repo)[https://github.com/Azure/azure-functions-durable-extension/issues/2683], and there the following points came to light:
- It is unclear when using Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore package if you should still use a `HttpTrigger` function that accepts and returns `HttpRequestData` \ `HttpResponseData`. This as of v1.1.1 the package seem to provide support through [AspNetCoreHttpRequestData.cs](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Http.AspNetCore/src/HttpDataModel/AspNetCoreHttpRequestData.cs) and does seem to play nice for now, but it is not clear if this is recommended
  - If it is not advised can this be added to [asp.net core integration documentation](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration)
- From Durable's teams perspective they are using the type as intended so the issue is re-raised here. So no async version will be introduced.
- Not clear whom/where a async version of CreateCheckStatusResponse has to be made for AspNetCore integration

All that I know is that to solve the exception is that an extension method version would need to be introduced that performs the serialization asynchronous, that extension method version would than be taken changes should the non-asynchronous version be updated and to avoid the work around.

Reference:
https://github.com/Azure/azure-functions-durable-extension/issues/2683

**Expected behavior**
When using ASP.NET Core integration and the durable task extension method there should be no exception thrown, however as synchronous writing is not allowed since ASP.NET Core 3+ a Async version will be needed to be exposed.

**Actual behavior**
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead
```
Result: An unhandled exception occurred.
Exception: System.AggregateException: One or more errors occurred. (Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.)
  ---> System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    at Azure.Core.Serialization.JsonObjectSerializer.Serialize(Stream stream, Object value, Type inputType, CancellationToken cancellationToken)
    at Microsoft.Azure.Functions.Worker.DurableTaskClientExtensions.CreateCheckStatusResponse(DurableTaskClient client, HttpRequestData request, String instanceId, HttpStatusCode statusCode, CancellationToken cancellation) in /_/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:line 97
    at Microsoft.Azure.Functions.Worker.DurableTaskClientExtensions.CreateCheckStatusResponse(DurableTaskClient client, HttpRequestData request, String instanceId, CancellationToken cancellation) in /_/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:line 34
```

### Relevant source code snippets
```csharp
[Function("SimpleHttpTriggerHttpData")]
public async Task<HttpResponseData> Run(
[HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestData req,
[DurableClient] DurableTaskClient durableClient)
{
       return durableClient.CreateCheckStatusResponse(req, "FakeId"); //Will result in exception
}
```

**Known Workarounds**
One option is to copy the `CreateCheckStatusResponse` into the consumers project and make a asynchronous version, however this does introduce having to keep an eye on the original code every time the package is updated in case of changes.

Another option from that ASP.NET Core provided for those updating in the past was to apply the following configuration which will allow calling synchronous writes to the HttpRequest. However this would be rather avoided:
```
services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
```

**Side note**
When using ASP.NET Core integration it would be nice to also have a `CreateCheckStatusResponse` version that accepts `HttpRequest` and returns an `ActionResult` to keep it more consistent with the ASP.NET Core integration HttpTriggers. However that would be just a nice to have.

**Comment by satvu** [comment]
Thanks for the detailed writeup! Ack on the docs improvement - it is not recommended to use `HttpRequestData` and `HttpResponseData` with the new ASP.NET Core integration, but the support is there to make migration easier. We'll take a look and get back to this as soon as we can given US holiday schedules.

**Comment by Duranom** [comment]
Thank you for clarity, at least the migration support does help to a degree.

Updated the "side note" at the bottom to "Addition request" for ASP.NET core integration, as it is a very impactful change to go (back) to `HttpRequestData/HttpResponseData` and remove ASP.NET core integration when you introduce Durable Task at later stage. 
(And have to be honest, ASP.net core integration really is nicer 😃 especially when moving ASP.net core candidates to functions)

Added coded version workaround that works with IActionResult, aside from enabling synchronous writing at previous issue [azure-functions-durable-extension/issues/2683](https://github.com/Azure/azure-functions-durable-extension/issues/2683#issuecomment-1859004872). Though it does need reflection (not optimized) and would need to keep constant watch on two repo's on every package update.

**Comment by jviau** [comment]
@Duranom is there any major drawback to enabling synchronous IO?

**Comment by jviau** [comment]
After some discussion, we decided the best workaround is for Durable to add async APIs for the existing `CreateCheckStatusResponse`. Will transfer to durable repo for this work.
