### ISSUE TITLE
Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]

### ISSUE THREAD

**Issue by Jhonny5Az** [Azure/azure-functions-dotnet-worker#2167]
HI I have this issue with net7.0, dotnet-isolated, the documentation said that I can work with stream but my code crash always,
I work with this packages:
```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.2.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" /> 
```
My function is this:
```
[Function(nameof(CMImageResizer))]
public async Task Run(
    [BlobTrigger("rawimages/{name}", Connection = "StorageAccountConnectionString")] Stream myBlob,
    [BlobInput("resizedimages/{name}", Connection = "StorageAccountConnectionString")] Stream resizedImage, string name)
{
  try
   {
   _log.LogInformation("Processing image:{name} size: {myBlobLength} Bytes", name, myBlob.Length);
```
And the error code is:
`[2023-12-24T05:35:39.629Z] Executing 'Functions.CMImageResizer' (Reason='New blob detected(LogsAndContainerScan): rawimages/taladro1.jpg', Id=00c22256-e65c-478c-82c3-eaca92c310b7)
[2023-12-24T05:35:39.632Z] Trigger Details: MessageId: 2f450295-dae1-42f5-ac2e-089d5b0d2a55, DequeueCount: 1, InsertedOn: 2023-12-24T05:35:38.000+00:00, BlobCreated: 2023-12-24T04:42:41.000+00:00, BlobLastModified: 2023-12-24T05:35:28.000+00:00
[2023-12-24T05:35:40.601Z] Function 'CMImageResizer', Invocation id '00c22256-e65c-478c-82c3-eaca92c310b7': An exception was thrown by the invocation.
[2023-12-24T05:35:40.604Z] Result: Function 'CMImageResizer', Invocation id '00c22256-e65c-478c-82c3-eaca92c310b7': An exception was thrown by the invocation.
[2023-12-24T05:35:40.604Z] Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'CMImageResizer': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. Error:System.Text.Json.JsonException: 'R' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
[2023-12-24T05:35:40.604Z]  ---> System.Text.Json.JsonReaderException: 'R' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
[2023-12-24T05:35:40.604Z]    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
[2023-12-24T05:35:40.604Z]    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
[2023-12-24T05:35:40.604Z]    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
[2023-12-24T05:35:40.604Z]    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
[2023-12-24T05:35:40.604Z]    at System.Text.Json.Utf8JsonReader.Read()
[2023-12-24T05:35:40.604Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
`

**Comment by ewarwick** [comment]
Your problem looks similar to mine: #2319 
In my case stream only works if i remove the {param} expressions from the trigger/input and output annotations - although this is obviously not a real solution since we both likely need the function to work for more than a single hard-coded filename.

**Comment by domv3** [comment]
If your storage connection string is defined as a user secret then you need to add user secrets into your program.cs.
You can also get away with adding it into you local.settings.json file as well. Here's how I added user secrets to my program.cs. After I added this, my cannon convert 'stream' to System.IO.Stream error went away.
`.ConfigureAppConfiguration(config =>
{
    config.AddUserSecrets<YourFunctionName>(optional: true, reloadOnChange: false);
})`

**Comment by liliankasem** [comment]
This is related to a known issue (#1969), please refer to this [comment](https://github.com/Azure/azure-functions-dotnet-worker/issues/1969#issuecomment-1787637965) for details.

Closing this as a dupe.
