### ISSUE TITLE
InvalidOperationException "The gRPC channel URI 'http://:0' could not be parsed." when using dotnet watch with .NET 8 SDK

### ISSUE THREAD

**Issue by duncanworthy** [Azure/azure-functions-dotnet-worker#2211]
Unable to use dotnet watch combined with func start on command line after installing .NET 8 SDK.

Repro steps:

```
> func new --template "Http Trigger" --name MyHttpTrigger
Use the up/down arrow keys to select a worker runtime: dotnet-isolated
Use the up/down arrow keys to select a language: c#-isolated

> dotnet watch func start --verbose
...
dotnet watch 🚀 Started
dotnet watch 🔥 Hot reload capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters.
Unhandled exception. System.InvalidOperationException: The gRPC channel URI 'http://:0' could not be parsed.
   at Microsoft.Azure.Functions.Worker.Grpc.GrpcWorkerClientFactory.GrpcWorkerClient.CreateClient() in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorkerClientFactory.cs:line 110
   at Microsoft.Azure.Functions.Worker.Grpc.GrpcWorkerClientFactory.GrpcWorkerClient..ctor(GrpcHostChannel outputChannel, GrpcWorkerStartupOptions startupOptions, IMessageProcessor processor) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorkerClientFactory.cs:line 52
   at Microsoft.Azure.Functions.Worker.Grpc.GrpcWorkerClientFactory.CreateClient(IMessageProcessor messageProcessor) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorkerClientFactory.cs:line 33
   at Microsoft.Azure.Functions.Worker.GrpcWorker.StartAsync(CancellationToken token) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 57
   at Microsoft.Azure.Functions.Worker.WorkerHostedService.StartAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\src\DotNetWorker.Core\WorkerHostedService.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\WIP\Experiments\Function App\Program.cs:line 7
```

Alternatively, edit the .csproj file to add a custom target
```
  <Target Name="RunFunctions">
    <Exec Command="func start --verbose" />
  </Target>
```
and use the following to launch
```
> dotnet watch msbuild /t:RunFunctions
```
results in the same exception.

However if you omit the `dotnet watch` and launch it simply using `func start --verbose` then the app launches correctly.

Adding a global.json file with the following content to prevent the .NET 8 SDK being used resolves the issue for a .NET 6 app:
```
{
  "sdk": {
    "version": "6.0.100"
  }
}
```

Not working:
```
> dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\
```

Working:
```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92
```

The same issue is affecting function apps targetting .NET 8, and for those the workaround cannot be applied as they need to be run under the .NET 8 SDK.

**Comment by jviau** [comment]
This is a regression in dotnet watch for .net8 SDK. See here: https://github.com/dotnet/sdk/issues/34949

**Comment by dwoods-unimax** [comment]
The changes for the referenced issue https://github.com/dotnet/sdk/issues/34949 for `dotnet watch test` didn't fix this for me.

```
dotnet --version
8.0.204
```

When starting my function app with `dotnet msbuild /t:RunFunctions` it starts up fine but when running `dotnet watch msbuild /t:RunFunctions` I get the error below
```
dotnet watch 🚀 Started
Unhandled exception. System.InvalidOperationException: The gRPC channel URI 'http://:' could not be parsed.
   at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.GetFunctionsHostGrpcUri(IConfiguration configuration) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 97
   at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.<>c.<AddGrpc>b__1_3(GrpcWorkerStartupOptions grpcWorkerStartupOption, IConfiguration config) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 72
```

**Comment by dwoods-unimax** [comment]
> This is a regression in dotnet watch for .net8 SDK. See here: [dotnet/sdk#34949](https://github.com/dotnet/sdk/issues/34949)

#jviau could this issue be re-opened since the issue you reference didn't resolve it?

**Comment by jviau** [comment]
@dwoods-unimax this is not an issue with the functions product, but an issue with dotnet SDK. The issue is external and there is no action we can take.
