### ISSUE TITLE
Service bus message actions throwing Grpc.Core.RpcException when sending multiple requests

### ISSUE THREAD

**Issue by MathBouma** [Azure/azure-functions-dotnet-worker#2354]
### Description

This occurs with a C# isolated function, using .NET 8 and latest versions of all libraries.
 
For some reason, when using the message actions with batched service bus messages- some of them will fail with the following error: 
`Call failed with gRPC error status. Status code: 'Unimplemented', Message: 'Service is unimplemented.`

This looks similar to #1974, however only occurs after multiple requests have been made within one function execution.

My best guess is some kind of limit, be it connections / pooling not being handled correctly.  

### Steps to reproduce

- Have a function app which receives a large batch of messages (experienced with ~100).
- Use message actions to deadletter, abandon or complete a large number of the messages.
- Have multiple function executions occurring in short time of each other.
   - Short cut could be to fill service bus with a decent number of messages, then call abandon on each message with a large retry set.
 
Some of the requests will then fail with the GRPC error.

My specific scenario was a function which:
- Receives a batch of messages.
- Tries to bulk insert messages into cosmos.
- Completes successful requests, and abandons failed requests
   - This is because comos can hit rate limits, and only allow a portion of the records to be created. Simply allowing the function to retry or complete would cause issues, as either requests would be duplicated or missed. 

Happy to provide more info / source code as needed.

**Comment by kanetik** [comment]
Came looking for an answer on something very similar. We're getting bursts of RpcExceptions when we have a large number of concurrent messages we're processing. The error message isn't the same, but it's an RpcException on call to CompleteMessageAsync. We're also on .NET 8, isolated function, and latest version of all libraries (5.17.0 of Worker.Extentions.ServiceBus). 

The message we get, though is 
`Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. SocketException: An existing connection was forcibly closed by the remote host.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.")`

**Comment by zmerdev** [comment]
Also seeing this in logs of a batched servicebus triggered function using message actions to manually complete/abandon/deadletter all messages.  Our logging makes it difficult to trackdown where exactly the issue is cropping up.

partial stack trace
```

Result: Failure
Exception: Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Service is unimplemented.")

at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
```

**Comment by dmaples-midmark** [comment]
We have also seen this with low volumes of single messages. Running some tests yesterday (4/16), I saw 2 failures out of 20 test messages right after deploying a minor update in our development environment. Since then I've been unable to reproduce the exception intentionally after running several thousand messages through the function.

**We just upgraded the function to .NET 8 Isolated and running the latest release version of all libraries:**
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/146846085/75059b84-4a5b-4595-8a59-427953163e42)

**Example Full Stack Trace:**

```
Exception while executing function: Functions.ServiceContracts Result: Failure
Exception: Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Service is unimplemented.")
   at Microsoft.Azure.Functions.Worker.ServiceBusMessageActions.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in D:\a\_work\1\s\extensions\Worker.Extensions.ServiceBus\src\ServiceBusMessageActions.cs:line 78
   at Datahub.MessageBroker.Function.Consumers.MidmarkServiceBusConsumerBase.HandleMessageExceptionAsync(Exception ex, ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions) in /home/vsts/work/1/s/self/Datahub.MessageBroker.Function/Consumers/MidmarkServiceBusConsumerBase.cs:line 182
   at Datahub.MessageBroker.Function.Consumers.MidmarkServiceBusConsumerBase.HandleIncomingServiceBusMessage(ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions, String processName, String topicName, String subscriptionName) in /home/vsts/work/1/s/self/Datahub.MessageBroker.Function/Consumers/MidmarkServiceBusConsumerBase.cs:line 96
   at Datahub.MessageBroker.Function.Consumers.ASBConsumer.ServiceContractsFunctionAsync(ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions) in /home/vsts/work/1/s/self/Datahub.MessageBroker.Function/Consumers/ASBConsumer.cs:line 34
   at Datahub.MessageBroker.Function.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in /home/vsts/work/1/s/self/Datahub.MessageBroker.Function/Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator/GeneratedFunctionExecutor.g.cs:line 38
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
   at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at Microsoft.Azure.Functions.Worker.ServiceBusMessageActions.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in D:\a\_work\1\s\extensions\Worker.Extensions.ServiceBus\src\ServiceBusMessageActions.cs:line 78
   at Datahub.MessageBroker.Function.Consumers.MidmarkServiceBusConsumerBase.HandleMessageExceptionAsync(Exception ex, ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions) in /home/vsts/work/1/s/self/Datahub.MessageBroker.Function/Consumers/MidmarkServiceBusConsumerBase.cs:line 182
   at Datahub.MessageBroker.Function.Consumers.MidmarkServiceBusConsumerBase.HandleIncomingServiceBusMessage(ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions, String processName, String topicName, String subscriptionName) in /home/vsts/work/1/s/self/Datahub.MessageBroker.Function/Consumers/MidmarkServiceBusConsumerBase.cs:line 96
   at Datahub.MessageBroker.Function.Consumers.ASBConsumer.ServiceContractsFunctionAsync(ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions) in /home/vsts/work/1/s/self/Datahub.MessageBroker.Function/Consumers/ASBConsumer.cs:line 34
   at Datahub.MessageBroker.Function.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in /home/vsts/work/1/s/self/Datahub.MessageBroker.Function/Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator/GeneratedFunctionExecutor.g.cs:line 38
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
   at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
```

**Comment by dmaples-midmark** [comment]
There seems to be a possible correlation with the RpcExceptions and our function initializing. Since we are in consumption plan, our function is often not running during periods of downtime. The following telemetry is a 6 hour snapshot from Azure showing RpcExceptions overlayed with Process CPU.
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/146846085/8435d62f-61ee-48c4-8e20-4189ca01bd50)

What is interesting here is that all of the exceptions overlap with periods where the function was not reporting Process CPU yet, likely because it was initializing. There may be some time variation between the reporting of these individual metrics that could invalidate this. However, I thought it might be significant enough to share here.

**Comment by janus007** [comment]
I'm experiencing the exact same behavior and as this wasn't enough I get a ton of object disposed. 

These Object Disposed are apparently an issue that can't be fixed. I have spent tremendous amounts of time, trying to understand the problem. Others have same issues: https://github.com/Azure/azure-sdk-for-net/issues/19731

If I use the exact same SB Queue, but instead switch to a Topic everything works fine. What is going on?

It seems very unprofessional from you .NET guys, that the .NET 7.0 Isolated stops support May 10 2024, and we are left with this major bug in .NET 8 Isolated.

I can't imagine how much money there is wasted in the World due to this.

`System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.WebSockets.ClientWebSocket'. at System.Net.WebSockets.ClientWebSocket.get_ConnectedWebSocket() at System.Net.WebSockets.ClientWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken) at Microsoft.Azure.Amqp.Transport.WebSocketTransport.WriteAsync(TransportAsyncCallbackArgs args) at Microsoft.Azure.Amqp.AsyncIO.AsyncBufferWriter.Write(TransportAsyncCallbackArgs args) --- End of stack trace from previous location --- at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result) at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location --- at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, Uri connectionEndpoint, ServiceBusTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout) at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken) at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken) at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)`

**Comment by russaram-bham** [comment]
We are also experiencing the same issue when executing an Azure Function via a Service Bus Trigger (.Net 8 Isolated) when Cosmos returns a number of 429s.

Messages are not placed on the DLQ but a RpcExceptions is thrown.

**Comment by nkalfov** [comment]
I am also having this issue. An Azure Function is triggered by a Service Bus Message. The exception happens when executing
` await messageActions.CompleteMessageAsync(message);`

It is not thrown often, but I do see it occasionally in Application Insights. What is the reason? What is the resolution? 

Stack Trace:
`
Result: Failure
Exception: Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Service is unimplemented.")
at Microsoft.Azure.Functions.Worker.ServiceBusMessageActions.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in D:\a\_work\1\s\extensions\Worker.Extensions.ServiceBus\src\ServiceBusMessageActions.cs:line 78
at *******.Run(ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions) in /opt/atlassian/pipelines/agent/build/src/********/*******.cs:line 47
at *******.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in /opt/atlassian/pipelines/agent/build/src/*******/Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator/GeneratedFunctionExecutor.g.cs:line 42
at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack: at Microsoft.Azure.Functions.Worker.ServiceBusMessageActions.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in D:\a\_work\1\s\extensions\Worker.Extensions.ServiceBus\src\ServiceBusMessageActions.cs:line 78
at *******.Run(ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions) in /opt/atlassian/pipelines/agent/build/src/*******/*******.cs:line 47
at*******.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in /opt/atlassian/pipelines/agent/build/src/*******/Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator/GeneratedFunctionExecutor.g.cs:line 42
at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
`

**Comment by Vixan** [comment]
As others have mentioned, I'm also encountering this issue for a couple of weeks. Whether I'm using `CompleteMessageAsync`, `DeadLetterMessageAsync` or letting the function autocomplete messages without using `ServiceBusMessageActions`, I'm encountering these `RpcException`s with status "Unimplemented" or "Unavailable". 

Due to the fact that my functions create side effects (update database records, file creation, etc.), not being able to rely on message completion/dead-lettering after processing them causes multiple issues. I'd appreciate any help 🙂.

**Comment by wtrombly** [comment]
As others have mentioned I am also experiencing this issue when using CompleteMessageAsync and DeadLetterMessageAsync. We are using azure serverless functions with a consumption plan on .NET 8.
Would appreciate any help.

**Comment by AlexEngblom** [comment]
We are also experiencing this issue after upgrading to NET8 and isolated Function base.

**Comment by MichalDulski** [comment]
We're experiencing a very similar issue too. Our Azure Function uses .NET 8 isolated-worker model and runs on a consumption plan. We do not batch messages. The function works fine when the load is low (let's say 20 messages per minute) , but when the function receives more messages than that, it sometimes fails due to the Grpc.Core.RpcException being thrown by the CompleteMessageAsync or DeferMessageAsync methods. Our function processes over 3000 messages daily, and we encounter this issue once or twice almost every day. Although it’s not consistent, there are times when everything works properly, which might be related to slightly lower load on some days.

Stack trace:
```
Result: Failure
Exception: Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Service is unimplemented.")
   at Microsoft.Azure.Functions.Worker.ServiceBusMes`sageActions.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in D:\a\_work\1\s\extensions\Worker.Extensions.ServiceBus\src\ServiceBusMessageActions.cs:line 78
   at *.*.*.Run(ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions, CancellationToken cancellationToken) in Z:\*\*\*\FUNCTION_FILE.cs:line 87
   at *.*.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in Z:\*\*\*\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 38
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
   at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at Microsoft.Azure.Functions.Worker.ServiceBusMessageActions.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in D:\a\_work\1\s\extensions\Worker.Extensions.ServiceBus\src\ServiceBusMessageActions.cs:line 78
   at *.*.*.Run(ServiceBusReceivedMessage message, ServiceBusMessageActions messageActions, CancellationToken cancellationToken) in Z:\*\*\*\FUNCTION_FILE.cs:line 87
   at *.*.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in Z:\*\*\*\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 38
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
   at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
```

I would appreciate any help. If there's something more I could do to help, please let me know.

**Comment by RubenDelange** [comment]
We are also experiencing this issue after upgrading to NET8 and using isolated Functions. Also using batched mode and message actions to deadletter, abandon, or complete a message.

**Comment by fabiocav** [comment]
Apologies for the delayed response here.

Thank you for the information shared so far, this gives us a good idea of what the potential issue is and will be investigating and posting updates here as we make progress.

This is looking like a host problem, so we'll be transferring this issue to that repo.
