### ISSUE TITLE
Exception when running ServiceBusTrigger with managed identity locally

### ISSUE THREAD

**Issue by mpec** [Azure/azure-functions-dotnet-worker#2381]
### Description

When we run our functions that use ServiceBus Trigger locally we get an error log, but the function continues to run and connects to ServiceBus.

The error we see is:

``` 
False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.26 Microsoft Windows 10.0.22631 [2024-04-04 11:20:59Z - a5b037bc-4ded-4814-93cc-b888ba93c78f] Exception type: Azure.Identity.CredentialUnavailableException
[2024-04-04T11:20:59.554Z] ---> Inner Exception Details
[2024-04-04T11:20:59.554Z] Exception type: System.AggregateException
[2024-04-04T11:20:59.555Z] ---> Inner Exception Details
[2024-04-04T11:20:59.556Z] Exception type: Azure.RequestFailedException
[2024-04-04T11:20:59.557Z] ---> Inner Exception Details
[2024-04-04T11:20:59.558Z] Exception type: System.Net.Http.HttpRequestException
[2024-04-04T11:20:59.558Z] ---> Inner Exception Details
[2024-04-04T11:20:59.559Z] Exception type: System.Net.Sockets.SocketException
[2024-04-04T11:20:59.560Z]
[2024-04-04T11:20:59.560Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[2024-04-04T11:20:59.561Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[2024-04-04T11:20:59.562Z]    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
[2024-04-04T11:20:59.562Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2024-04-04T11:20:59.563Z] === End of inner exception stack trace ===
[2024-04-04T11:20:59.564Z]
[2024-04-04T11:20:59.564Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2024-04-04T11:20:59.565Z]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2024-04-04T11:20:59.566Z]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2024-04-04T11:20:59.566Z]    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
[2024-04-04T11:20:59.567Z]    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[2024-04-04T11:20:59.568Z]    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2024-04-04T11:20:59.568Z]    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[2024-04-04T11:20:59.569Z]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[2024-04-04T11:20:59.570Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2024-04-04T11:20:59.570Z] === End of inner exception stack trace ===
[2024-04-04T11:20:59.571Z]
[2024-04-04T11:20:59.572Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2024-04-04T11:20:59.572Z]    at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
[2024-04-04T11:20:59.573Z]    at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-04-04T11:20:59.574Z]    at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-04-04T11:20:59.575Z]    at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-04-04T11:20:59.575Z]    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-04-04T11:20:59.576Z] === End of inner exception stack trace ===
[2024-04-04T11:20:59.577Z]
[2024-04-04T11:20:59.577Z]    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-04-04T11:20:59.578Z]    at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2024-04-04T11:20:59.579Z]    at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2024-04-04T11:20:59.579Z] === End of inner exception stack trace ===
[2024-04-04T11:20:59.580Z]
[2024-04-04T11:20:59.580Z]    at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2024-04-04T11:20:59.581Z]    at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2024-04-04T11:20:59.582Z]    at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
[2024-04-04T11:20:59.583Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)
[2024-04-04T11:20:59.583Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
[2024-04-04T11:20:59.584Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
[2024-04-04T11:20:59.585Z]    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)

My local config for service bus is:
<img width="398" alt="image" src="https://github.com/Azure/azure-functions-dotnet-worker/assets/6253549/774b3974-ea92-4148-9112-8a7e3d331a9b">


The example function signature where we see this:
![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/6253549/27ad96bd-aec2-4e0c-b354-f383ef0331fa)


We aren't sure why we get this error, but I confirmed that it's showing up only in case of SB Trigger and managed identity.


### Steps to reproduce

Run function locally.

**Comment by enijburg** [comment]
I can confirm this issue is happening in all of our .NET isolated function apps created with .NET 8

**Comment by gitFire001** [comment]
The issue is happening even with the Python functions running locally.

**Comment by adae-palfinger** [comment]
Also having this issue

**Comment by ThomasDejbjerg** [comment]
I can confirm that this also happens on our .NET isolated function apps, and that setting ExcludeManageIdentity do change the outcome, it still tries to get the token from ManagedIdentity.

**Comment by enzosambucetti** [comment]
I can also confirm that is happening to us, in isolated mode, net 8.0, with ConfigureFunctionsWebApplication()  and ConfigureFunctionsWorkerDefaults().
Any ideas?

**Comment by ibis7** [comment]
Also having this issue running Az Function locally

**Comment by dean-dot-git** [comment]
We are also having these issues with this.  I can't seem to find a way to bypass it.

**Comment by dean-dot-git** [comment]
@liliankasem, how do we escalate this in priority?  This is putting me in a position to use Entra app registration client credentials and have to store them in my local.settings.json file to allow developers the ability to test service bus triggers.  My security team doesn't like having exposed credentials like this in our configurations.  We can't put it into app configuration/key vault as I don't want our azure infrastructure to use it.

Can someone please escalate this or articulate the proper solution to use managed identities with service bus in Azure, but use alternatives with Visual Studio/local development that doesn't use this as your documentation (https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob&pivots=programming-language-csharp#local-development-with-identity-based-connections) suggests:

![Image](https://github.com/user-attachments/assets/8c67f064-703e-4449-ba3b-efb60a5a3b91)

**Comment by JasonDWilson** [comment]
How is this not assigned -- it's been 9 months since it was reported

**Comment by dean-dot-git** [comment]
Following up.  Update?

**Comment by jordanchang** [comment]
I am also facing this problem.

Azure Functions v4
dotnet-isolated on .NET 8
