### ISSUE TITLE
Using (ITableEntity) POCO class for TableInput on a queue trigger throws a JSON exception, while a TableEntity does work

### ISSUE THREAD

**Issue by vverheijen** [Azure/azure-functions-dotnet-worker#2398]
### Description

We're in the process of upgrading our azure functions app from .net6 to .net8 and to isolation mode.
After doing all the needed changes and nuget package upgrades and removals, we ran in the issue that it started throwing a error on the database/table input binding whenever the function was triggered (queue trigger in this case). It was unable to convert the JSON string to our POCO

Cannot convert input parameter 'entity' to type 'Models.TeamRequest' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to Models.TeamRequest. Path: $ | LineNumber: 0 | BytePositionInLine: 1.

Even when i substituted our class for a class that implements only the ITableEntity interface, the error persists.

Our function looks like this
```
[Function("ProvisioningFunction")]
public async Task Run([QueueTrigger(Constants.QueueNameProvisioning, Connection = "AzureWebJobsStorage")] CloudEvent ProvisioningQueueItem,
    [TableInput(Constants.RequestsTableName, "{Subject}", "{Subject}")] TeamRequest entity,
    [DurableClient] DurableTaskClient starter)
{
    if (entity != null)
    {
        string instanceId = await starter.ScheduleNewOrchestrationInstanceAsync(nameof(ProvisioningOrchestrator.ProvisioningOrchestrationFunction), input: entity);
    }
    else
    {
        _logger.LogError("Input Entity is null");
    }
}
```

And even this simple POCO didn't work, still the same error

```
namespace Models
{
    public class DataTableTest : ITableEntity
    {
        // ITableEntity properties
        public string PartitionKey { get; set; } = string.Empty;
        public string RowKey { get; set; } = string.Empty;
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; } = new ETag("*");
    }
}
```

But if we change
[TableInput(Constants.RequestsTableName, "{Subject}", "{Subject}")] TeamRequest entity,
into
[TableInput(Constants.RequestsTableName, "{Subject}", "{Subject}")] **TableEntity** entity,

Then the trigger, and the bindings, works as expected, the TableEntity class has all the table data, but obviously we'd need to convert it to our own class first. That's a workaround, but using a POCO should still be supported as far as i can tell.

Also, it appears we aren't the only ones to run into this issue, but that was 2 months ago with no further activity
https://github.com/MicrosoftDocs/azure-docs/issues/119619
https://github.com/sergeevgk/azure-functions-university/commit/f2fe7b84ef2bff83c40c01be81c506a9135d5462

For completeness sake the Stacktrace (annoymised):

Executing 'Functions.ProvisioningFunction' (Reason='New queue message detected on 'provisioning'.', Id=3d67e60c-0817-4128-bad5-d3ebf108723e)
[2024-04-16T12:04:48.472Z] Trigger Details: MessageId: f6b0b0e3-64f6-421f-add8-88968c56a815, DequeueCount: 5, InsertedOn: 2024-04-16T12:04:33.000+00:00
[2024-04-16T12:04:48.582Z] Function 'ProvisioningFunction', Invocation id '3d67e60c-0817-4128-bad5-d3ebf108723e': An exception was thrown by the invocation.
[2024-04-16T12:04:48.587Z] Result: Function 'ProvisioningFunction', Invocation id '3d67e60c-0817-4128-bad5-d3ebf108723e': An exception was thrown by the invocation.
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'ProvisioningFunction': Cannot convert input parameter 'entity' to type 'Models.TeamRequest' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to Models.TeamRequest. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
[2024-04-16T12:04:48.591Z]    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
[2024-04-16T12:04:48.593Z]    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2024-04-16T12:04:48.594Z] Executed 'Functions.ProvisioningFunction' (Failed, Id=3d67e60c-0817-4128-bad5-d3ebf108723e, Duration=124ms)
[2024-04-16T12:04:48.595Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-04-16T12:04:48.598Z] System.Private.CoreLib: Exception while executing function: Functions.ProvisioningFunction. System.Private.CoreLib: Result: Failure
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'ProvisioningFunction': Cannot convert input parameter 'entity' to type 'Models.TeamRequest' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to Models.TeamRequest. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
[2024-04-16T12:04:48.604Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2024-04-16T12:04:48.608Z]    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
[2024-04-16T12:04:48.611Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
[2024-04-16T12:04:48.613Z]    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2024-04-16T12:04:48.618Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
[2024-04-16T12:04:48.620Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-04-16T12:04:48.622Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
[2024-04-16T12:04:48.624Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2024-04-16T12:04:48.626Z]    at Microsoft.Azure.Functions.Worker.Converters.JsonPocoConverter.GetConversionResultFromDeserialization(Byte[] bytes, Type type) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\JsonPocoConverter.cs:line 66
[2024-04-16T12:04:48.634Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 94
[2024-04-16T12:04:48.628Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
[2024-04-16T12:04:48.637Z]    at AzureFunctions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Code\AzureFunctions\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 33
[2024-04-16T12:04:48.639Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
[2024-04-16T12:04:48.641Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-04-16T12:04:48.643Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
[2024-04-16T12:04:48.647Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
[2024-04-16T12:04:48.651Z]    at Microsoft.Azure.Functions.Worker.Converters.JsonPocoConverter.GetConversionResultFromDeserialization(Byte[] bytes, Type type) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\JsonPocoConverter.cs:line 66
[2024-04-16T12:04:48.654Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 94
[2024-04-16T12:04:48.656Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 94
[2024-04-16T12:04:48.659Z]    at AzureFunctions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Code\AzureFunctions\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 33
[2024-04-16T12:04:48.663Z]    at AzureFunctions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Code\AzureFunctions\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 33
[2024-04-16T12:04:48.665Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-04-16T12:04:48.668Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-04-16T12:04:48.670Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
[2024-04-16T12:04:48.672Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
[2024-04-16T12:04:48.674Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77.
[2024-04-16T12:04:48.678Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2024-04-16T12:04:48.682Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 94
[2024-04-16T12:04:48.685Z]    at AzureFunctions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Code\AzureFunctions\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 33
[2024-04-16T12:04:48.687Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-04-16T12:04:48.689Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
[2024-04-16T12:04:48.694Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2024-04-16T12:04:48.696Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.

### Steps to reproduce

Using azure storage emulator 5.10 (for both the queue and input table)

Create a queue, and add a item in the emulator.
Create a table and one item with a rowkey and partitionkey you can reference in your queuetrigger

Create a C# azure functions project and add a queue trigger like the mentioned above (but you can use the rowkey and partitionkey directly as a string, no need to read them from the queuetrigger) 
add a simple POCO implementing just ITableEntity

Start a debug run, error will be thrown.
change the POCO to TableEntity, trigger will work as expected

Nugets versions installed in our project. 
Azure.Data.Tables Version=12.8.3
Azure.Storage.Blobs Version=12.19.1
Azure.Storage.Files.Shares Version=12.17.1
Azure.Storage.Queues Version=12.17.1
Microsoft.Azure.Functions.Worker.Extensions.DurableTask Version=1.1.2
Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs Version=6.3.0
Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues Version=5.3.0
Microsoft.Azure.Functions.Worker.Extensions.Tables Version=1.3.0
Microsoft.Extensions.Configuration.Abstractions Version=8.0.0
Microsoft.Extensions.Configuration.UserSecrets Version=8.0.0
Microsoft.IdentityModel.Protocols Version=7.5.1
Microsoft.Azure.Functions.Worker Version=1.21.0
Microsoft.Azure.Functions.Worker.Sdk Version=1.17.2
Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore Version=1.2.1
Microsoft.ApplicationInsights.WorkerService Version=2.22.0
Microsoft.Azure.Functions.Worker.ApplicationInsights Version=1.2.0

**Comment by svrooij** [comment]
Maybe this is related to https://github.com/Azure/azure-sdk-for-net/issues/43443

I'm facing similar issues, where converting to a class gives some random unexpected exception.

**Comment by MakanWG** [comment]
Facing exact same issue with HTTPTrigger.
Also, using TableEntity as a workaround will not work if you don't specify a RowKey as a TableInput parameter : 
` [TableInput("TableName", "{PartitionKey}",Take =1)] TableEntity tableInput`
Will throw
`Cannot convert input parameter 'tableInput' to type 'Azure.Data.Tables.TableEntity' from type 'Microsoft.Azure.Functions.Worker.Grpc.Messages.GrpcModelBindingData'. Error:System.ArgumentNullException: Value cannot be null. (Parameter 'RowKey')`

**Comment by MakanWG** [comment]
Adding more context and workarounds : 

I thought that it might be an issue with System.Text.Json as the default deserialization settings can be confusing especially when you come from Newtonsoft. So I switched the serializer to Newtonsoft and got a far better error message : 

`Cannot convert input parameter 'entity' to type 'Models.TeamRequest' from type 'System.String'. Error:Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'MenuShot.Functions.Model.Tables.DBDocument' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.`

So the issue here is that TableInput always returns an array.
@vverheijen  Indeed if you change your TableInput parameter to : 

`[TableInput(Constants.RequestsTableName, "{Subject}", "{Subject}")] IEnumerable<TeamRequest entity>`

Then you should be good to go. You can probably call SingleOrDefault on the result to get your single entity. It's probably better than parsing the TableEntity Dictionnary.

**Comment by liliankasem** [comment]
@kshyju - I wonder if this related? https://github.com/Azure/azure-functions-dotnet-worker/issues/2320

**Comment by kshyju** [comment]
> @kshyju - I wonder if this related? #2320

I think the TableEntityConverter still needs to be fixed so that binding happens there instead of falling back to JSON converter.

**Comment by kshyju** [comment]
@vverheijen the suggestion from @MakanWG is correct. Today, you need to use a collection type as parameter and get the item from that collection. 

```csharp
[Function("ProvisioningFunction")]
public async Task Run(
    [QueueTrigger(Constants.QueueNameProvisioning, Connection = "AzureWebJobsStorage")] CloudEvent item,
    [TableInput(Constants.RequestsTableName, "{Subject}", "{Subject}")] IEnumerable<TeamRequest> entities,
    [DurableClient] DurableTaskClient starter)
{
    var entity = entities.FirstOrDefault();
    .....
}
```

I have opened #2412 to improve this experience.

**Comment by vverheijen** [comment]
yes, with the simplified model class it works as expected after adding IEnumerable

Our own model still throws a exception but no longer on index 0 in the byte array, so it will be a different issue in the model/data, Probably related to azure functions no longer using the Newtonsoft libraries by default. I'll see if i can fix that, or switch it to use newtonsoft instead but that is unrelated to this issue.

Thank you all for help, I'll close this ticket, and monitor the progress of the other bug's progress.
