### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 'Microsoft.Azure.ServiceBus.Grpc.Settlement+SettlementClient' while attempting to activate 'Microsoft.Azure.Functions.Worker.ServiceBusMessageActionsConverter'

### ISSUE THREAD

**Issue by smichtch** [Azure/azure-functions-dotnet-worker#2408]
### Description

Facing a strange runtime failure in functions with `[ServiceBusTrigger]` + `ServiceBusMessageActions` parameters:
```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Azure.ServiceBus.Grpc.Settlement+SettlementClient' while attempting to activate 'Microsoft.Azure.Functions.Worker.ServiceBusMessageActionsConverter'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.GetOrCreateConverterInstance(Type converterType) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 74
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.<GetOrCreateConverterInstance>b__8_0(String key, String converterTypeAssemblyQualifiedName) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 101
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.GetOrCreateConverterInstance(String converterTypeName) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 91
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.GetConverterFromContext(ConverterContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 131
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.ConvertAsync(ConverterContext converterContext) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 39
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.ConvertAsync(FunctionContext context, FunctionParameter parameter, IConverterContextFactory converterContextFactory, IInputConversionFeature inputConversionFeature, Object source) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 157
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 55
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 46
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
```
The strange/puzzling part is this only occurs in our "official" OneBranch builds, I've not been able to reproduce this error running/building locally or even non-official pull request builds. The internal `Settlement+SettlementClient` type should be getting registered here:
https://github.com/Azure/azure-functions-dotnet-worker/blob/ca7afd23f6a7f68059e00bc642c13ef9efd21dee/extensions/Worker.Extensions.ServiceBus/src/ServiceBusExtensionStartup.cs#L19-L23
My theory is that source code generation here gets skipped somehow in our Official builds which results in `[assembly: WorkerExtensionStartup(typeof(ServiceBusExtensionStartup))]` being ignored:
https://github.com/Azure/azure-functions-dotnet-worker/blob/ca7afd23f6a7f68059e00bc642c13ef9efd21dee/sdk/Sdk.Generators/ExtensionStartupRunnerGenerator.cs
I'm not that familiar with source code generation and I don't know which build parameters or environment variables would affect it (`Debug` vs `Release` doesn't seem to be it) - maybe someone can refer me in the right direction.

Using these packages:
```xml
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.17.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Warmup" Version="4.0.2" />
```

### Steps to reproduce

See description.

**Comment by jviau** [comment]
@smichtch this is an issue with OneBranch builds - specifically the `RoslynAnalyzer` task they recommend you use to build. This task does not run source generators, which we rely on. This results in a broken application. I recommend using the dotnet cli task to build.

I am currently engaging with the OneBranch team to address this issue from the OB side.

**Comment by jviau** [comment]
Resolving in favor of #2453
