### ISSUE TITLE
Include CommandLine config source in `ConfigureFunctionsWorkerDefaults()`

### ISSUE THREAD

**Issue by cmap-gaz** [Azure/azure-functions-dotnet-worker#256]
I get the following when trying to run locally using func host start

```
[2021-03-09T14:31:58.246Z] Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
[2021-03-09T14:31:58.248Z]    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
[2021-03-09T14:31:58.249Z]    at System.Uri..ctor(String uriString)
[2021-03-09T14:31:58.250Z]    at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
[2021-03-09T14:31:58.251Z]    at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddFunctionsWorker>b__0_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker\Configuration\ServiceCollectionExtensions.cs:line 78
```

```
Azure Functions Core Tools
Core Tools Version:       3.0.3331 Commit hash: 0b57b1647c5a385beb8f7d64fa0e534ad4c7555d
Function Runtime Version: 3.0.15371.0

```

```
[Function("SearchIndexer")]
        public async Task Run([ServiceBusTrigger(TopicSubscriptionConstants.Topic, TopicSubscriptionConstants.IndexingSubscription, Connection = MessageConstants.MessageQueueConnectionSetting)] string message) {
}
```

**Comment by brettsam** [comment]
@cmap-gaz -- two questions:
1. Can you share your project file? I'm curious what package versions you're referencing.
2. What OS are you running this on?

**Comment by cmap-gaz** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
    <UserSecretsId>[id]</UserSecretsId>
    <RootNamespace>[namespace]</RootNamespace>
    <ProjectGuid>[guid]</ProjectGuid>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Core\Enumerations\**" />
    <EmbeddedResource Remove="Core\Enumerations\**" />
    <None Remove="Core\Enumerations\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.0.0-preview5" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1-preview1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.1-preview5" />
    <PackageReference Include="Dapper" Version="2.0.78" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
  </ItemGroup>

  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

This is on Windows 10 vs2019 16.9

**Comment by brettsam** [comment]
Can you get a few more pieces of info for me? Trying to narrow down what could be happening.
- Are you using VS or VS code to build?
- What directory are you running `func host start` from?
- In your built directory (the one that `func host start` is running from, typically `bin\debug\net5.0`), can you share the `functions.metadata` and `worker.config.json` files?

**Comment by cmap-gaz** [comment]
Using VS to build

running `func host start` from the root of the project

```
[
  {
    "name": "SearchIndexer",
    "scriptFile": "CMAP_SearchIndex.dll",
    "entryPoint": "CMAP.SearchIndex.SearchIndexer.Run",
    "language": "dotnet-isolated",
    "properties": {
      "IsCodeless": false
    },
    "bindings": [
      {
        "name": "message",
        "type": "ServiceBusTrigger",
        "direction": "In",
        "topicName": "[name of topic]",
        "subscriptionName": "[subscription]",
        "connection": "QueueConnection"
      }
    ]
  }
]
```

```
{
  "description": {
    "language": "dotnet-isolated",
    "extensions": [ ".dll" ],
    "defaultExecutablePath": "dotnet",
    "defaultWorkerPath": "CMAP_SearchIndex.dll"
  }
}
```

**Comment by brettsam** [comment]
Alternatively -- if you set the default loglevel to "Debug" in host.json, you should see a lot more logs when you run `func host start`. One of those will look like `Starting worker process with`.... If you could share that log, it'd tell me the arguments getting passed into the worker. Example host.json below:
```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
        "default": "Debug"    
    }
  }
}
```

**Comment by cmap-gaz** [comment]
```
class Program {

        static async Task Main(string[] args) {

    
            var host = new HostBuilder()
                .ConfigureAppConfiguration(c => {
                   
                })
                .ConfigureFunctionsWorker((c, b) => {
                    b.UseFunctionExecutionMiddleware();
                })
                .ConfigureServices(s => {
                    s.AddOptions<MessageHandlerOptions>()
                    .Configure<IConfiguration>((settings, configuration) => {
                        configuration.GetSection("Settings").Bind(settings);
                    });
                    s.AddOptions<SqlDbSettings>()
                    .Configure<IConfiguration>((settings, configuration) => {
                        configuration.GetSection("SQLRepo").Bind(settings);
                    });
                    ServicesSetup.RegisterServices(s);
                })
                .Build();

           

            await host.RunAsync();
        }

    }
```

This is from the extra logging:
```

[2021-03-09T19:01:23.346Z] Starting worker process with FileName:C:\Program Files\dotnet\dotnet.exe WorkingDirectory:C:\inetpub\wwwroot\Projects\CMAP v3\Source\CMAP_SearchIndex\bin\output Arguments: "C:\inetpub\wwwroot\Projects\CMAP v3\Source\CMAP_SearchIndex\bin\output\CMAP_SearchIndex.dll" --host 127.0.0.1 --port 1144 --workerId 5a2274e6-c23f-4ae5-bed1-e802c05efdfd --requestId 51796c42-f162-4f29-99a0-d68d86bc6254 --grpcMaxMessageLength 2147483647
[2021-03-09T19:01:23.350Z] C:\Program Files\dotnet\dotnet.exe process with Id=7588 started
[2021-03-09T19:01:23.352Z] Generating 1 job function(s)
[2021-03-09T19:01:23.370Z] Found the following functions:
[2021-03-09T19:01:23.372Z] Host.Functions.SearchIndexer
[2021-03-09T19:01:23.372Z]
[2021-03-09T19:01:23.396Z] Initializing function HTTP routes
[2021-03-09T19:01:23.397Z] No HTTP routes mapped
[2021-03-09T19:01:23.399Z]
[2021-03-09T19:01:23.406Z] Host initialized (115ms)
[2021-03-09T19:01:23.463Z] Host started (179ms)
[2021-03-09T19:01:23.464Z] Job host started
[2021-03-09T19:01:23.466Z] File event source initialized.
[2021-03-09T19:01:23.468Z] Debug file watch initialized.
[2021-03-09T19:01:23.469Z] Diagnostic file watch initialized.
[2021-03-09T19:01:23.470Z] Hosting started
[2021-03-09T19:01:23.470Z] Startup operation 'fda9a052-1a4e-45e1-b4cc-9ff3273037a0' completed.

Functions:

        SearchIndexer: ServiceBusTrigger

For detailed output, run func with --verbose flag.
[2021-03-09T19:01:23.713Z] Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
[2021-03-09T19:01:23.715Z]    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
[2021-03-09T19:01:23.716Z]    at System.Uri..ctor(String uriString)
[2021-03-09T19:01:23.718Z]    at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
[2021-03-09T19:01:23.719Z]    at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddFunctionsWorker>b__0_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker\Configuration\ServiceCollectionExtensions.cs:line 78
[2021-03-09T19:01:23.720Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
[2021-03-09T19:01:23.721Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[2021-03-09T19:01:23.722Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[2021-03-09T19:01:23.723Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[2021-03-09T19:01:23.724Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[2021-03-09T19:01:23.726Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[2021-03-09T19:01:23.727Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[2021-03-09T19:01:23.728Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[2021-03-09T19:01:23.729Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[2021-03-09T19:01:23.730Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[2021-03-09T19:01:23.735Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
[2021-03-09T19:01:23.736Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[2021-03-09T19:01:23.737Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[2021-03-09T19:01:23.739Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[2021-03-09T19:01:23.740Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[2021-03-09T19:01:23.742Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
[2021-03-09T19:01:23.743Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[2021-03-09T19:01:23.744Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
[2021-03-09T19:01:23.745Z]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
[2021-03-09T19:01:23.749Z]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[2021-03-09T19:01:23.750Z]    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[2021-03-09T19:01:23.752Z]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[2021-03-09T19:01:23.753Z]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[2021-03-09T19:01:23.754Z]    at CMAP.SearchIndex.Program.Main(String[] args) in c:\inetpub\wwwroot\Projects\CMAP v3\Source\CMAP_SearchIndex\Program.cs:line 39
[2021-03-09T19:01:23.755Z]    at CMAP.SearchIndex.Program.<Main>(String[] args)
[2021-03-09T19:01:28.005Z] Language Worker Process exited. Pid=7588.
[2021-03-09T19:01:28.009Z] C:\Program Files\dotnet\dotnet.exe exited with code -532462766
```

**Comment by brettsam** [comment]
Ah okay -- this line is currently required:
```
.ConfigureAppConfiguration(c =>
{
    c.AddCommandLine(args);
})
```

We're introducing a new API to make this smoother -- `.ConfigureFunctionsWorkerDefaults()` that will take care of this for you in the next release. But for now, you need to explicitly register the command line config source.

I've updated the title and assigned to @fabiocav, who is already looking at this.
