### ISSUE TITLE
EventHub default template runs into IndexOutOfRangeException when triggered with no data

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-dotnet-worker#270]
Hitting an IndexOutOfRangeException when event hub triggered function triggered with no data.

Repro:
```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace TestApp
{
    public static class MyEventHubFunc
    {
        [Function("MyEventHubFunc")]
        public static void Run([EventHubTrigger("samples-workitems-final", Connection = "MarieEventHub")] string[] input, FunctionContext context)
        {
            var logger = context.GetLogger("MyEventHubFunc");
            logger.LogInformation($"First Event Hubs triggered message: {input[0]}");
        }

        [Function(nameof(Test))]
        [EventHubOutput("samples-workitems-final", Connection = "EventHubConnectionAppSetting")]
        public static string Test(
[HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequestData req,
    FunctionContext context)
        {
            var logger = context.GetLogger(nameof(Test));
            logger.LogInformation(".NET Worker HTTP trigger function processed a request");
            string output = req.ReadAsString() ?? "hello world";
            return output;
        }
    }
}
```
To repro: Run the "Test" function with a request that has no body

Exception:
```
[2021-03-10T08:24:47.317Z] Executed 'Functions.MyEventHubFunc' (Failed, Id=9421dfc7-690a-4e31-a88c-03959c137eb6, Duration=161ms)
[2021-03-10T08:24:47.318Z] System.Private.CoreLib: Exception while executing function: Functions.MyEventHubFunc. System.Private.CoreLib: Result: Failure
Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
[2021-03-10T08:24:47.323Z]    at dotnetworkerga2.MyEventHubFunc.Run(String[] input, FunctionContext context) in D:\mhoeger\test\dotnetworkerga2\MyEventHubFunc.cs:line 14
[2021-03-10T08:24:47.326Z]    at lambda_method3(Closure , MyEventHubFunc , Object[] )
[2021-03-10T08:24:47.326Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidMethodInvoker.cs:line 22
[2021-03-10T08:24:47.330Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2021-03-10T08:24:47.336Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
[2021-03-10T08:24:47.339Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-03-10T08:24:47.341Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
Stack:    at dotnetworkerga2.MyEventHubFunc.Run(String[] input, FunctionContext context) in D:\mhoeger\test\dotnetworkerga2\MyEventHubFunc.cs:line 14
[2021-03-10T08:24:47.343Z]    at lambda_method3(Closure , MyEventHubFunc , Object[] )
[2021-03-10T08:24:47.344Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidMethodInvoker.cs:line 22
[2021-03-10T08:24:47.345Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2021-03-10T08:24:47.348Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 37
[2021-03-10T08:24:47.356Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-03-10T08:24:47.358Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169.
```

**Comment by fabiocav** [comment]
The template has been updated. This should no longer be an issue.
