### ISSUE TITLE
Azure Function with .NET and AOT produces Exception: System.InvalidOperationException: Reflection-based serialization

### ISSUE THREAD

**Issue by shotyme** [Azure/azure-functions-dotnet-worker#2715]
Hi, 

when I create a new Azure Function v4 with .NET8 in isolated-worker mode and add 

```
<PropertyGroup>
 <PublishAot>true</PublishAot>
</PropertyGroup>
```

to the .csproj I get this exception on the startup:

```
Exception: System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
[2024-09-06T13:56:38.895Z]    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
[2024-09-06T13:56:38.895Z]    at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
[2024-09-06T13:56:38.896Z]    at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
[2024-09-06T13:56:38.897Z]    at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
[2024-09-06T13:56:38.897Z]    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
[2024-09-06T13:56:38.897Z]    at Microsoft.Azure.Functions.Worker.Grpc.FunctionMetadata.FunctionMetadataRpcExtensions.GetBindingInfoList(IFunctionMetadata funcMetadata) in D:\a\_work\1\s\src\DotNetWorker.Grpc\FunctionMetadata\FunctionMetadataRpcExtensions.cs:line 29
[2024-09-06T13:56:38.898Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.GetFunctionMetadataAsync(String functionAppDirectory) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 185
Stack:    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
[2024-09-06T13:56:38.898Z]    at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
[2024-09-06T13:56:38.899Z]    at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
[2024-09-06T13:56:38.899Z]    at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
[2024-09-06T13:56:38.900Z]    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
[2024-09-06T13:56:38.900Z]    at Microsoft.Azure.Functions.Worker.Grpc.FunctionMetadata.FunctionMetadataRpcExtensions.GetBindingInfoList(IFunctionMetadata funcMetadata) in D:\a\_work\1\s\src\DotNetWorker.Grpc\FunctionMetadata\FunctionMetadataRpcExtensions.cs:line 29
[2024-09-06T13:56:38.901Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.GetFunctionMetadataAsync(String functionAppDirectory) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 185.
[2024-09-06T13:56:38.935Z] Unhandled exception. System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
```

The Azure Function was created by the Visual Studio 2022 template and just contained the boilderplate HttpTrigger. If you remove the  `PublishAot` option from your csproj you should remove the `bin` and `obj` folder and it should start again. Same goes the other way around when you add it back in and you want to produce the issue again. 
Do I miss something here?

**Comment by shotyme** [comment]
As I wrote in my initial post: Steps for reproduction:

1. Create a Azure Function with HttpTrigger via Visual Studio 2022
2. Change the .csproj and add
```
<PropertyGroup>
 <PublishAot>true</PublishAot>
</PropertyGroup>
```

You will get a ```System.InvalidOperationException: Reflection-based serialization```

**Comment by bhagyshricompany** [comment]
that is not supported. for now if have in future ill update.Thanks

**Comment by PaulVrugt** [comment]
any update on this?

**Comment by satvu** [comment]
We do not currently support AOT, but you can track the effort to here: https://github.com/Azure/azure-functions-dotnet-worker/issues/1056.

Closing this as a duplicate.
