### ISSUE TITLE
Cannot use multiple attributes per parameter

### ISSUE THREAD

**Issue by vanillajonathan** [Azure/azure-functions-dotnet-worker#2739]
### Description

I cannot bind a parameter such as `client` with both the `BlobTrigger` and the `BlobInput` attributes.

    Worker failed to index functions
     Result: Failure
    Exception: System.ArgumentException: Key already exists in map (Parameter 'key')
        at Google.Protobuf.Collections.MapField`2.Add(TKey key, TValue value)
        at Microsoft.Azure.Functions.Worker.Grpc.FunctionMetadata.FunctionMetadataRpcExtensions.GetBindingInfoList(IFunctionMetadata funcMetadata) in D:\a\_work\1\s\src\DotNetWorker.Grpc\FunctionMetadata\FunctionMetadataRpcExtensions.cs:line 34
        at Microsoft.Azure.Functions.Worker.GrpcWorker.GetFunctionMetadataAsync(String functionAppDirectory) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 185
    Stack:    at Google.Protobuf.Collections.MapField`2.Add(TKey key, TValue value)
        at Microsoft.Azure.Functions.Worker.Grpc.FunctionMetadata.FunctionMetadataRpcExtensions.GetBindingInfoList(IFunctionMetadata funcMetadata) in D:\a\_work\1\s\src\DotNetWorker.Grpc\FunctionMetadata\FunctionMetadataRpcExtensions.cs:line 34
        at Microsoft.Azure.Functions.Worker.GrpcWorker.GetFunctionMetadataAsync(String functionAppDirectory) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 185.

### Steps to reproduce

```cs
[Function(nameof(Function1))]
[BlobOutput("import/processed/{name}")]
public async Task Run([BlobTrigger("import/{name}"), BlobInput("import/{name}")] BlobClient client, string name)
{
}
```

**Comment by matt-lethargic** [comment]
I'm hitting the same problem, seems to be contrary to the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-input?tabs=python-v2%2Cisolated-process%2Cnodejs-v4&pivots=programming-language-csharp#usage). Looking at the error it seems to be trying to convert to JSON?!

Not working
```csharp
[Function(nameof(DeliveryFunction))]
[BlobOutput("processed/{name}", Connection = "Storage")]
public async Task<byte[]> Run([BlobTrigger("reporting/{name}", Connection = "Storage")] Stream inputStream, string name)
{ }
```
Error
```
Error converting 1 input parameters for Function 'DeliveryFunction': Cannot convert input parameter 'inputStream' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
Error:System.Text.Json.JsonException: '-' is invalid within a number, immediately after a sign character ('+' or '-'). Expected a digit ('0'-'9'). Path: $ | LineNumber: 0 | BytePositionInLine: 1.
```

If I take off the `[BlobOutput]` attribute then it works
```csharp
[Function(nameof(DeliveryFunction))]
public async Task Run([BlobTrigger("reporting/{name}", Connection = "Storage")] Stream inputStream, string name)
{ }
```

**Comment by satvu** [comment]
Closing as answered - @matt-lethargic if the linked issue and explanation does not help solve your problem, please open up a new issue to track. Thanks!

**Comment by vanillajonathan** [comment]
@satvu Yes, I can refactor my function to look more like that example but I think Azure function should either be able to handle multiple attributes on a parameter or it should throw a exception with a friendly error message.
