### ISSUE TITLE
Azure Functions - Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-functions-dotnet-worker#2776]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#46577](https://github.com/Azure/azure-sdk-for-net/issues/46577).

### Library name and version

 Azure.Data.Tables 12.9.1 and Azure.Storage.Blobs 12.22.2

### Describe the bug

Cannot use Azure.Data.Tables and Azure.Storage.Blobs in the same Azure Functions project in VS 2022. When I use the TableClient I get 

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Memory.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Azure.Core.RequestContent.Create(Object serializable, ObjectSerializer serializer)
   at Azure.Core.RequestContent.Create(Object serializable)
   at Azure.Data.Tables.TableClient.CreateIfNotExistsAsync(CancellationToken cancellationToken)
   at azfunct1.HelloWorld.Run(HttpRequest req, ILogger log) in xxxxxxx\az-func-cannot-load-assembly\azfunct1\HelloWorld.cs:line 29
```

```
var tsc = new TableServiceClient("UseDevelopmentStorage=true");
var tabc = tsc.GetTableClient("zzztest1");
await tabc.CreateIfNotExistsAsync();
```

Sample project with the issue:
https://github.com/fhtino/publicissues/tree/main/az-func-cannot-load-assembly

Workaround: place _FunctionsSkipCleanOutput in the project file:

```
<PropertyGroup>
	<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
```

### Expected behavior

no errors

### Actual behavior

Exception: System.Memory.Data, Version=6.0.0.0  not found

### Reproduction Steps

sample here:  https://github.com/fhtino/publicissues/tree/main/az-func-cannot-load-assembly

### Environment

 - Visual Studio 2022 17.11.5
 - Azure Functions Core Tools / Core Tools Version: 4.0.6518 (64-bit) / Function Runtime Version: 4.35.4.23179

**Comment by nodeomega** [comment]
Can confirm. Also facing this issue.

Workaround I have seems to be having System.Memory.Data 6.0.0 installed as a separate NuGet package, building the solution, and copying the System.Memory.Data.dll file to the bin subdirectory in the bin folder, at least in Debug. (I assume Release would be the same way).

Which leads to a folder structure like `bin\Debug\net8.0\bin`, where I had to copy the dll from `bin\Debug\net8.0`

For whatever reason, this dependency isn't getting copied to that bin subfolder.

Side effect: Any time I make a change to the Azure Function project and rebuild, the copied System.Memory.Data.dll file disappears, and the error pops up again.

**Comment by Rudresh-Dongre-Contractor** [comment]
Facing the same issue recently while trying to use Azure.Storage.Blobs

**Comment by Dave-DRX** [comment]
Having same issue with Microsoft.Azure.WebJobs.Extensions.Storage.Queues.

System.Private.CoreLib: Exception has been thrown by the target of an invocation. Microsoft.Azure.WebJobs.Extensions.Storage.Queues: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, Culture=neutral. The system cannot find the file specified.

**Comment by bishwaranjans** [comment]
I am also facing the same issue

**Comment by Dave-DRX** [comment]
The prescribed workaround (see above: "<PropertyGroup><_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>") worked. 
I guess I need to update to an isolated process, as recommended by Microsoft, sooner than I thought.

**Comment by sonofsmog** [comment]
Same issue with using Azure.Security.KeyVault.Secrets and callingSecretClient.GetSecretAsync. @nodeomega's workaround worked for me. Good looking out. Hopefully this gets fixed soon.

**Comment by mcremer-able** [comment]
Wer are using nodejs and as such can not use @nodeomega 's workaround.
Is there any way to maybe downgrade, so it can work again?

**Comment by shibayan** [comment]
Alternative workaround

```xml
  <ItemGroup>
    <FunctionsPreservedDependencies Include="System.Memory.Data.dll" />
  </ItemGroup>
```

**Comment by ZmorzynskiK** [comment]
Have exactly the same issue with `Microsoft.Azure.WebJobs.Extensions.EventHubs` updated to the newest version (6.3.6):
> Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0

None of the workarounds worked, so I just reverted to earlier versions of the assemblies and now it works:

```
<PackageReference Include="Azure.Identity" Version="1.13.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.4" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.2" />
<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="6.3.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.SignalRService" Version="1.14.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Tables" Version="1.3.0" />
```

But this is ridiculous... 🫤

**Comment by Y-Sindo** [comment]
Having the same issue for the latest `Microsoft.Azure.Functions.Worker.Extensions.SignalRService` 1.15.0 version. It blocks users from using managed identity to connect to SignalR Service.

**Comment by DavidKoolen** [comment]
We have the same issue with ```Microsoft.Azure.Functions.Worker.Extensions.SignalRService 1.15.0```. Downgrade to 1.14.1 resolves the issue and we can use the System-assigned managed identity again.

**Comment by sastru** [comment]
> Alternative workaround
> 
>   <ItemGroup>
>     <FunctionsPreservedDependencies Include="System.Memory.Data.dll" />
>   </ItemGroup>

That's it? no need to have it as a `PackageReference` ? as it's an implicit dependency...? No copy dll stuff mentioned in one of the comments above?
