### ISSUE TITLE
dotnet run does not work on Windows when Core Tools are installed from NPM

### ISSUE THREAD

**Issue by DavidZidar** [Azure/azure-functions-dotnet-worker#2884]
### Description

I just tried to run my isolated function app with `dotnet run` as it's supposed to be supported since version 2 but I get the following error:
```
Unhandled exception: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'func' with working directory 'D:\pathtoproject\bin\debug\net9.0\'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

It seems that the `RunCommand` is hardcoded as `func` here:
https://github.com/Azure/azure-functions-dotnet-worker/blob/c4113d1c5936ab3235d7a73ec5a88596977c8335/sdk/Sdk/Targets/Microsoft.Azure.Functions.Worker.Sdk.targets#L86

It should probably be `func.cmd` on Windows.

I have reproduced the problem in .NET by running `Process.Start("func")` which fails similarly while `Process.Start("func.cmd")` works.

My PATH does contain `func`, `func.ps1` and `func.cmd` as installed by npm.

### Steps to reproduce

```shell
npm install -g azure-functions-core-tools@4
dotnet run
```

**Comment by jviau** [comment]
@DavidZidar did you restart your terminal after running `npm install`? It is possible your path was not updated.

**Comment by jviau** [comment]
I am unable to reproduce this. On windows, path expansion is supposed to automatically handle going from `{file}` to `{process}.{exe|bin|cmd}`. From a powershell terminal, can you run `gcm func`. Does it find a command and show the source for it?

**Comment by DavidZidar** [comment]
Isn't path expansion a feature of the shell? I could be mistaken but I don't think `Process.Start` has path expansion.

In any case, yes, here is some terminal output:
```
> Get-Command func

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
ExternalScript  func.ps1                                                      C:\Users\david\scoop\apps\nodejs-lts\curre…

> ls C:\Users\david\scoop\apps\nodejs-lts\current\bin\func*

    Directory: C:\Users\david\scoop\apps\nodejs-lts\current\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2024-12-01    16:08            445 func
-a---          2024-12-01    16:08            353 func.cmd
-a---          2024-12-01    16:08            917 func.ps1

> $env:PATH -split ';' | rg nodejs-lts
C:\Users\david\scoop\apps\nodejs-lts\current\bin
C:\Users\david\scoop\apps\nodejs-lts\current

> func --version
4.0.6610
```

I reproduced this on a second machine, exact same behavior.

**Comment by DavidZidar** [comment]
Like I said I get the same error from .NET. When I try running `Process.Start("func")` in LINQPad it throws a `Win32Exception` in just the same way, if I run `Process.Start("func.cmd")` then it actually runs the command.

**Comment by DavidZidar** [comment]
`Process.Start(new ProcessStartInfo("func") { UseShellExecute = true })` works, apparently `UseShellExecute` used to be true by default in .NET Framework but in .NET Core it isn't.

**Comment by DavidZidar** [comment]
Oh, interesting, that explains it. I just tried installing it via winget and now it works, thanks! I didn't know it was possible to install the tools without using npm.

**Comment by mattchenderson** [comment]
Ah, that's an interesting limitation. We'll have to look into that. I can add a specific callout in the documentation to help others with this.

We definitely want this to work with an NPM installation though. We'll keep this item for tracking that. We've been looking at ways to help the tool provide more specifics around acquisition in general, and I think this aligns with that.

**Comment by fabiocav** [comment]
It's possible this is an issue with the MSBuild logic handling this. We'll follow up and provide an update.

**Comment by davidfowl** [comment]
I just hit this after installing functions 3 different ways 😄
