### ISSUE TITLE
Unable to use newtonsoft JObject for CosmosDbTrigger input parameter

### ISSUE THREAD

**Issue by vakuras** [Azure/azure-functions-dotnet-worker#2891]
### Description

Hi,

I'm getting the following exception:

```
Error converting 1 input parameters for Function 'DeviceDedupe': Cannot convert input parameter 'documents' to type 'System.Collections.Generic.IReadOnlyList`1[[Newtonsoft.Json.Linq.JObject, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to Newtonsoft.Json.Linq.JToken. Path: $[0].metadata | LineNumber: 0 | BytePositionInLine: 14.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Microsoft.Azure.Functions.Worker.Converters.JsonPocoConverter.GetConversionResultFromDeserialization(Byte[] bytes, Type type) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\JsonPocoConverter.cs:line 66,
Microsoft.Azure.Functions.Worker.FunctionInputConverterException,
```

I'm using `services.AddMvc().AddNewtonsoftJson()` to setup newtonsoft json.

### Steps to reproduce

-

**Comment by liliankasem** [comment]
Have you tried setting up newtonsoft using our documentation/sample?

- https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=hostbuilder%2Clinux#customizing-json-serialization
- Sample: https://github.com/Azure/azure-functions-dotnet-worker/blob/bf563c49c2f2ab20f6c2d5a56ae9915e87f2d2c6/samples/Configuration/Program.cs#L58
