### ISSUE TITLE
TimeOutException in HttpTrigger Function

### ISSUE THREAD

**Issue by ansonpinhero** [Azure/azure-functions-dotnet-worker#2910]
I am encountering a TimeOutException at the following line of code:

https://github.com/Azure/azure-functions-dotnet-worker/blob/2bbc2b98d18ebf16ce129d41dafb1ffada1ea2ec/extensions/Worker.Extensions.Http.AspNetCore/src/Coordinator/DefaultHttpCoordinator.cs#L36

This issue occurs intermittently. I have a Time Triggered function that invokes an HTTP Trigger function within the same Function App.

Below is the exception stack trace:

`Connection id "{ConnectionId}", Request id "{TraceIdentifier}": An unhandled exception was thrown by the application.

System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.WorkerRequestServicesMiddleware.Invoke(HttpContext context) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/AspNetMiddleware/WorkerRequestServicesMiddleware.cs:line 28
   at Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.BlockingMiddleware.Invoke(HttpContext context) in /project/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/AspNetCore/BlockingMiddleware.cs:line 115
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)` 

Could anyone provide insights or suggestions to debug and resolve this issue?

**Comment by fabiocav** [comment]
Hey @ansonpinhero, the exception above seems to indicate that either your worker didn't get the context information from the host, or there is something with the execution pipeline impacting the context synchronization.

How often are you seeing this happen? Can you tell whether this happens in specific scenarios like activation or scaling? If you can share your app name (or region, an invocation ID and a timeframe), we can also try to take a look a platform logs. If you're seeing this in production, opening a support request would also be a good way to proceed as your app information would be associated with that.

Thanks!

**Comment by ansonpinhero** [comment]
I have a Function App running in a Docker container on my local machine. I'm using Datadog for profiling and tracing. However, I am encountering this issue only when Datadog tracing is enabled (DD_TRACE_ENABLED = true).

According to the Datadog profiler's code, the exception is thrown when the WorkerRequestServicesMiddleware is invoked by a middleware injected by Datadog. Please see the following code snippet:

https://github.com/DataDog/dd-trace-dotnet/blob/47d26de6aeaf8b9552e9bfb148ac0061d1dd429f/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/AspNetCore/BlockingMiddleware.cs#L115C17-L115C60 

The test scenario involves sending HTTP requests, starting with 10 virtual users, ramping up to 100 virtual users, holding at that level for 10 minutes, and then ramping down to 0. The issue occurs when the load reaches 40 virtual users, where I start seeing exceptions.

Below is my function. 

`
[Function("Hello")]
public IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequest req)
{
    _logger.LogInformation("C# HTTP trigger function processed a request.");
    return new OkObjectResult("Welcome to Azure Functions!");
}
`
Dockerfile

`
# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated8.0 AS base
WORKDIR /home/site/wwwroot
EXPOSE 8080


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/TestFnApp/FunctionApp/.FunctionApp.csproj", "src/TestFnApp/FunctionApp/"]
RUN dotnet restore "./src/TestFnApp/FunctionApp/FunctionApp.csproj"
COPY . .
WORKDIR "/src/src/TestFnApp/FunctionApp"
RUN dotnet build "./FunctionApp.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./FunctionApp.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /home/site/wwwroot
COPY --from=publish /app/publish .

COPY --from=datadog/serverless-init:1.2.6 /datadog-init /app/datadog-init
COPY --from=datadog/dd-lib-dotnet-init:v2.56 /datadog-init/monitoring-home/ /dd_tracer/dotnet/

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

CMD ["/app/datadog-init", "/azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost"]
`

**Comment by kenthellck** [comment]
We noticed similar behavior in our application, as mentioned by @ansonpinhero . This issue is occurring in .NET 8 isolated and has resulted in numerous timeouts, causing our application to fail. When we disable Datadog, it works perfectly.

We urgently need a resolution from Datadog, as this issue is preventing us from delivering our applications to production. As a workaround, we are now attempting to implement Azure Application Insights, which functions correctly. And thinking to move away from DataDog.

 Datadog needs to improve its APM capabilities to address such issues effectively.

**Comment by mike-at-enpal-de** [comment]
i was facing similar issue, in my case disabling aspnet health check middleware helped
(i completely removed services.AddHealthChecks() call)

**Comment by ansonpinhero** [comment]
Closing this issue as Datadog has resolved it in the 3.9.0 release. More details: https://github.com/DataDog/dd-trace-dotnet/issues/6494
