### ISSUE TITLE
'Invalid URI: The hostname could not be parsed.' on startup

### ISSUE THREAD

**Issue by mizrael** [Azure/azure-functions-dotnet-worker#331]
Hi, I'm having issues writing and running a Function App with .NET 5 in isolated mode. I'm using VS Code on a Mac.
Fresh install of AZ CLI, .NET SDK.  Ran `func init MyHealthyFuncApp` in an empty folder.

I added a simple function class:

```
public class MyFunction
    {
        [Function(nameof(SayHello))]
        public static HttpResponseData SayHello([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequestData req,
    FunctionContext executionContext)
        {
            var response = req.CreateResponse(HttpStatusCode.OK);
            response.Headers.Add("Date", "Mon, 18 Jul 2016 16:06:00 GMT");
            response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

            response.WriteString("Hello!");

            return response;
        }
    }
```
then added the missing Nuget packages, `Microsoft.Azure.Functions.Worker.Extensions.Abstractions` and `Microsoft.Azure.Functions.Worker.Extensions.Http` (BTW, I would also suggest adding these to the samples, instead of directly reference the projects). No other changes.

When I launch the project, I immediately get this exception:

```
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
   at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.<>c.<AddGrpc>b__1_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 58
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at MyHealthyFuncApp.Program.Main() in /Volumes/Titano/Sources/dotnet/azure-functions-healthchecks/MyHealthyFuncApp/Program.cs:line 16
   at MyHealthyFuncApp.Program.<Main>()

```

any idea?

**Comment by fabiocav** [comment]
Can you share your project file? This looks like an issue that was resolved prior to GA.

By the way, there should be no need to reference the abstractions package directly.

**Comment by mizrael** [comment]
hi @fabiocav, thanks for replying! I've pushed the sources here: https://github.com/mizrael/azure-functions-healthchecks/

By the way, you were right about the Abstractions package. I just had to reference `Microsoft.Azure.Functions.Worker.Extensions.Http`.

**Comment by eriklieben** [comment]
not sure if this helps, but I just had this same error when starting by pressing F5 in vscode, but if I try to run the same app by using ```func host start``` it runs without expections.

**Comment by mizrael** [comment]
thanks @eriklieben , you're right, `func host start` works fine. Launching the project with either VS Code or VS for Mac doesn't work.

**Comment by fabiocav** [comment]
Tooling support is still pending for this model, so the environment is not correctly setup by default when using them. The recommendation is to indeed use Core Tools in the meantime. Thanks!

**Comment by mizrael** [comment]
thanks @fabiocav. What about debugging then? Should we rely on logic abstraction and unit/integration tests in the meantime?

**Comment by fabiocav** [comment]
We have some instructions on how to debug here: https://github.com/Azure/azure-functions-dotnet-worker#visual-studio , but let me know if you have any problems with that.

**Comment by Prinsn** [comment]
This is happening in our project using the methods listen above to run

**Comment by jeffward01** [comment]
Any progress on this issue? I am encountering it as well.

I have these packages installed:

` <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Abstractions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>`

**Comment by tjrobinson** [comment]
> Any progress on this issue? I am encountering it as well.

How are you starting it? If I use Rider and try and run it as a .NET project it fails with the errors above, but if I use Rider, or the command line to execute `func host start` it's fine.
