### ISSUE TITLE
System.UriFormatException when running on Linux

### ISSUE THREAD

**Issue by lufthavn** [Azure/azure-functions-dotnet-worker#403]
I have attempted to upgrade an existing Azure Functions application to use this new isolated model. 
It runs fine on my Windows development machine. But when I deploy it to the Function Application in Azure, it fails during startup with this exception: 

Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.

The App Service Plan in question is Linux based.

Stack trace:
```
2021-04-20T19:28:35.412 [Information] Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
2021-04-20T19:28:35.418 [Information] at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
2021-04-20T19:28:35.418 [Information] at System.Uri..ctor(String uriString)
2021-04-20T19:28:35.418 [Information] at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
2021-04-20T19:28:35.418 [Information] at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.<>c.<AddGrpc>b__1_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 58
2021-04-20T19:28:35.419 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
2021-04-20T19:28:35.419 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-04-20T19:28:35.419 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2021-04-20T19:28:35.419 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2021-04-20T19:28:35.419 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-04-20T19:28:35.419 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-04-20T19:28:35.419 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-04-20T19:28:35.419 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2021-04-20T19:28:35.420 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2021-04-20T19:28:35.420 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-04-20T19:28:35.421 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-04-20T19:28:35.421 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-04-20T19:28:35.421 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2021-04-20T19:28:35.457 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2021-04-20T19:28:35.457 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-04-20T19:28:35.457 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
2021-04-20T19:28:35.457 [Information] at Microsoft.ExtensioneScope scope)
2021-04-20T19:28:35.457 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2021-04-20T19:28:35.457 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2021-04-20T19:28:35.457 [Information] at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
2021-04-20T19:28:35.458 [Information] at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2021-04-20T19:28:35.458 [Information] at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2021-04-20T19:28:35.458 [Information] at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2021-04-20T19:28:35.458 [Information] at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2021-04-20T19:28:35.458 [Information] at MyApp.Functions.Program.Main() in /home/vsts/work/1/s/MyApp.Functions/Program.cs:line 20cyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2021-04-20T19:28:35.457 [Information] at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2021-04-20T19:28:35.457 [Information] at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
2021-04-20T19:28:35.458 [Information] at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2021-04-20T19:28:35.458 [Information] at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2021-04-20T19:28:35.458 [Information] at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2021-04-20T19:28:35.458 [Information] at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2021-04-20T19:28:35.458 [Information] at MyApp.Functions.Program.Main() in /home/vsts/work/1/s/MyApp.Functions/Program.cs:line 20
```

Is there a way to work around this? 🙂

**Comment by lufthavn** [comment]
This seems to be caused by me deploying via an Azure DevOps release pipeline. It works when deploying with the SDK. I guess it's just a matter of waiting for the tools to be updated?

**Comment by fabiocav** [comment]
Apologies for the delayed response here. Yes, this is a point in time issue and the VS support is coming in 16.10. We'll be enhancing the error you ran into to make this a bit more descriptive.

**Comment by thrixton** [comment]
What is / is there the fix for this?
I have a function deployed in a container to AKS and it's getting the same error.
This is deployed via pulumi (IaC), not by `func kubernetes deploy`.
