### ISSUE TITLE
System.UriFormatException: Invalid URI: The hostname could not be parsed'

### ISSUE THREAD

**Issue by thrixton** [Azure/azure-functions-dotnet-worker#464]
I have a 5.0 dotnet-isolated function which I've deployed to AKS using `mcr.microsoft.com/azure-functions/dotnet-isolated:3.0.15885-dotnet-isolated5.0-slim` as the runtime.
When it starts up, I get the error below.
Is there a runbook for isolated functions outside of the Azure functions service?

Error
```
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.<>c.<AddGrpc>b__1_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 58
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
at ODE.Functions.Program.Main() in /build/src/ODE.Functions/Program.cs:line 35
```

Related issues [331](https://github.com/Azure/azure-functions-dotnet-worker/issues/331) and [403](https://github.com/Azure/azure-functions-dotnet-worker/issues/403)

**Comment by ffMathy** [comment]
This happens for me as well when trying to start the host from an integration test.

**Comment by fabiocav** [comment]
@thrixton this means that, somehow, the expected arguments were not passed. Would you mind sharing the following:

1. The Docker file you're using (if you've crafted your own)
2. The logs emitted by the host showing the worker startup information (the arguments should be there as well)

@ffMathy I believe the issue you're running into is a bit different (same root, different context). Would you mind opening a separate issue so we can iterate there? 

Thanks!

**Comment by thrixton** [comment]
Hi @fabiocav ,
Thanks for taking the time to look at this.
Hopefull I've included enough info below.

J
---

**Dockerfile**
```dockerfile
ARG DOTNET_BUILD_IMAGE_TAG
ARG DOTNET_FUNCTIONS_BUILD_IMAGE_TAG
ARG FUNCTIONS_RUNTIME_IMAGE_TAG

FROM mcr.microsoft.com/dotnet/sdk:${DOTNET_BUILD_IMAGE_TAG} as net_3

FROM mcr.microsoft.com/dotnet/sdk:${DOTNET_FUNCTIONS_BUILD_IMAGE_TAG} AS build

# Build Git Hash argument is to bust the docker caching mechanism and needs to be different on unique builds
ARG BUILD_GIT_HASH
ARG BUILD_GIT_URL
ARG BUILD_GIT_BRANCH
ARG BUILD_SRC_DIR
ARG BUILD_CS_PROJECT
ARG DOTNET_TARGET_FRAMEWORK
ARG DOTNET_RID
ARG DOTNET_APP_VERSION

# https://github.com/Azure/azure-functions-dotnet-worker/issues/297
COPY --from=net_3 /usr/share/dotnet /usr/share/dotnet

WORKDIR /build

# build
RUN echo ${BUILD_GIT_HASH} > /tmp/build_git_hash.txt && \
    git clone ${BUILD_GIT_URL} --branch ${BUILD_GIT_BRANCH} --depth 1 ./ && \
    cd ${BUILD_SRC_DIR} && \
    rm -rf /build/output && \
    dotnet publish ${BUILD_CS_PROJECT} -c Release -f ${DOTNET_TARGET_FRAMEWORK} -r ${DOTNET_RID} /p:InformationalVersion=${DOTNET_APP_VERSION} --output /build/output && \
    cp /tmp/build_git_hash.txt /build/output/    

ARG FUNCTIONS_RUNTIME_IMAGE_TAG

FROM mcr.microsoft.com/azure-functions/dotnet-isolated:${FUNCTIONS_RUNTIME_IMAGE_TAG}

ARG BUILD_SRC_DIR
ARG DOTNET_TARGET_FRAMEWORK
ARG DOTNET_RID

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true    

COPY --from=build /build/output /home/site/wwwroot
```
**ARGS**
```
--build-arg BUILD_GIT_HASH=27b952d2 
--build-arg BUILD_GIT_URL=<REDACTED>
--build-arg BUILD_GIT_BRANCH=functions-dev 
--build-arg DOTNET_BUILD_IMAGE_TAG=3.1-focal 
--build-arg DOTNET_FUNCTIONS_BUILD_IMAGE_TAG=5.0-focal 
--build-arg FUNCTIONS_RUNTIME_IMAGE_TAG=3.0.15885-dotnet-isolated5.0-slim 
--build-arg DOTNET_STARTUP_ASSEMBLY=ODE.Functions.dll 
--build-arg BUILD_SRC_DIR=src/ODE.Functions 
--build-arg BUILD_CS_PROJECT=ODE.Functions.csproj 
--build-arg DOTNET_TARGET_FRAMEWORK=net5.0 
--build-arg DOTNET_RID=linux-x64 
--build-arg DOTNET_APP_VERSION=0.1.0-2021-06-03.1520-27b952d2
```

**Environment**
```
AzureFunctionsJobHost__Logging__Console__IsEnabled=true
AzureWebJobsScriptRoot=/home/site/wwwroot
AzureWebJobsQueueStorageConnection=<REDACTED>
AzureWebJobsStorage=<REDACTED>
```
**Logs**
[pod-log.txt](https://github.com/Azure/azure-functions-dotnet-worker/files/6589125/pod-log.txt)

**Comment by brettsam** [comment]
Hi @thrixton -- would you mind sharing a simple project that repro's this? Specifically, the Program.cs file...

**Comment by ffMathy** [comment]
Not stale.

**Comment by thrixton** [comment]
Thanks @brettsam, @ffMathy,
I've not forgotten this, we've had a lack of power and I've not had time to respond apologies.
I'm in the process of stripping it back to a workable example.
I've now got it working just using a vanilla function, I'll start overlaying my program changes on the top and provide it once I can repro it properly.
All I'm doing really in the program is setting up DI which works fine locally.
Stand by, thanks for your support and patience .

**Comment by thrixton** [comment]
Hi @brettsam,
This seems to be an issue with the RID that I'm passing to the build command.
I manually specify `linux-x64` in my publish command (`dotnet publish ${BUILD_CS_PROJECT} -c Release -f ${DOTNET_TARGET_FRAMEWORK} -r ${DOTNET_RID} /p:InformationalVersion=${DOTNET_APP_VERSION} --output /build/output`), when I remove this it works at runtime.
I have an example project [here](https://github.com/thrixton/func-test-50) which illustrates this.
What should the RID be per default settings?

**Comment by fabiocav** [comment]
Thank you for sharing the details. 

We're working on some samples and will look at the repro you've provided to see what is going on there. Leaving this with the `Needs: Attention` flag for now.

**Comment by fabiocav** [comment]
Providing an update here as we're still looking at some of the details on this. Will update when we have more information to share.

**Comment by metoule** [comment]
I think I found the issue, and it's due to the way command line args are passed to the function host.
On windows, the `args` array passed to `Program.cs` do not include the executable name, but on Linux it does.

It's easy enough to see:

```c#
public static void Main(string[] args)
{
  var host = Host
    .CreateDefaultBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices((appBuilder, services) =>
    {
      foreach (var arg in args)
      {
        Console.WriteLine(arg);
      }
    })
    .Build();

  host.Run();
}
```

On windows, we get: 

> --host
127.0.0.1
--port
59973
--workerId
bc04144e-0eb8-498d-bdca-75e4a5099fe3
--requestId
ce21fa00-35d3-44f7-84a8-619c8acee2f5
--grpcMaxMessageLength
2147483647
workerId = bc04144e-0eb8-498d-bdca-75e4a5099fe3

but on Linux, we get:

> /home/site/wwwroot/FunctionApp1.dll
--host
127.0.0.1
--port
44681
--workerId
8a6e5a61-b974-45c1-a6fb-bd538566c7e9
--requestId
9a94e9d0-8dcd-4240-8142-cc842bab6668
--grpcMaxMessageLength
2147483647

Because the executable name is the first argument, the `CommandLineConfigurationProvider`  wrongly parses the arguments, and we end up having a configuration key / value `home/site/wwwroot/FunctionApp1.dll = --host` and the host name is lost.

To remediate, we can remove the first argument when creating the default host builder:

```c#
public static void Main(string[] args)
{
  var newArgs = new string[args.Length - 1];
  Array.Copy(args, 1, newArgs, 0, args.Length - 1);

  var host = Host
    .CreateDefaultBuilder(newArgs)
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices((appBuilder, services) =>
    {
      foreach (var arg in newArgs)
      {
        Console.WriteLine(arg);
      }
    })
    .Build();

  host.Run();
}
```

**Comment by brettsam** [comment]
Thank you all -- I now have a PR out which should address this: #528.
