### ISSUE TITLE
Dependency Injection of multiple services with same interface fails

### ISSUE THREAD

**Issue by AdrianPell** [Azure/azure-functions-dotnet-worker#483]
Attempting to inject multiple services with the same interface as an array fails in an isolated function process but succeeds in a non-isolated process.

Consider the following function class:

```
public class Function1
{
    readonly ITestService testService;
    public Function1(ITestService[] testServices)
    {
        this.testService = testServices[0];
    }

    [Function("Function1")]
    public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
        FunctionContext executionContext)
    {
        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

        response.WriteString(testService.Message);

        return response;
    }
}
```

The service is defined as:
```
.ConfigureServices(s =>
{
    s.AddScoped<ITestService, TestService>();
})
```

In an in-process function, this succeeds. `testServices` is populated with an array of all the instances that match the interface. However, in out-of-process functions, the following error gets thrown at runtime:

```
[2021-06-08T09:00:04.692Z] System.Private.CoreLib: Exception while executing function: Functions.Function1. System.Private.CoreLib: Result: Failure
Exception: System.InvalidOperationException: Unable to resolve service for type 'OOPFunctions.Services.ITestService[]' while attempting to activate 'OOPFunctions.Function1'.
[2021-06-08T09:00:04.696Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2021-06-08T09:00:04.704Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2021-06-08T09:00:04.708Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2021-06-08T09:00:04.712Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.CreateInstance(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 26
[2021-06-08T09:00:04.725Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 27
[2021-06-08T09:00:04.742Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-06-08T09:00:04.751Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
Stack:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2021-06-08T09:00:04.759Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2021-06-08T09:00:04.773Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2021-06-08T09:00:04.787Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.CreateInstance(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 26
[2021-06-08T09:00:04.800Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 27
[2021-06-08T09:00:04.807Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2021-06-08T09:00:04.815Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169.
```

Any ideas? It looks as if some parts of the resolution are done in OOP functions specific middleware. Is that the issue?

**Comment by fabiocav** [comment]
Please take a dependency on an `IEnumerable<ITestService>`. This is consistent with the out-of-box .NET experience for service resolution.

**Comment by AdrianPell** [comment]
Oh, right!

Thanks @fabiocav. All good now.
