### ISSUE TITLE
HttpTrigger gives exception The header name format is invalid. 

### ISSUE THREAD

**Issue by ak37165** [Azure/azure-functions-dotnet-worker#490]
Create a simple function "func init, func new" add an HttpTrigger and in the function code try accessing some header:
```
var didSucceed = req.Headers.TryGetValues("User-Agent", out IEnumerable<string> values);
```

This should work fine if called from PostMan. However, **if called from a browser**, this fails with exception:

Exception
 One or more errors occurred. (The header name format is invalid.)
[2021-06-10T12:50:23.837Z]  ---> System.FormatException: The header name format is invalid.
[2021-06-10T12:50:23.838Z]    at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
[2021-06-10T12:50:23.841Z]    at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)

Error is coming from [https://github.com/Azure/azure-functions-dotnet-worker/blob/72b9d17a485eda1e6e3626a9472948be1152ab7d/src/DotNetWorker.Core/Http/HttpHeadersCollection.cs#L39-L45](https://github.com/Azure/azure-functions-dotnet-worker/blob/72b9d17a485eda1e6e3626a9472948be1152ab7d/src/DotNetWorker.Core/Http/HttpHeadersCollection.cs#L39-L45).

I tried the following code in the function:

```
var hdrs = new HttpHeadersCollection();
hdrs.Add("Accept", "*/*");
hdrs.Add(":authority:", "localhost:7071");

```
The second header being added, ":authority:" causes the exception. Both Chrome and Edge seem to add this header for localhost. So running on localhost becomes impractical if the function must access headers such as to access the auth header etc.

Related: [issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/386).

**Comment by ak37165** [comment]
Replaced with [https://github.com/Azure/azure-functions-dotnet-worker/issues/494](https://github.com/Azure/azure-functions-dotnet-worker/issues/494)
