### ISSUE TITLE
Cannot get dotnet-isolated project running in Azure ( works locally)

### ISSUE THREAD

**Issue by alanokelly** [Azure/azure-functions-dotnet-worker#553]
I have tried many different ways to get my C# .NET 5 (dotnet-isolated) project working in Azure, but have not had any success whatsoever. The function runs perfectly on my local machine. I've tried swapping from consumption to app plan, I've tried to build locally and then published directly from my machine to skip around the build and release steps. Still no luck. I'm out of ideas and I don't really want to rollback to .NET Core 3.1.

I'm getting constant RPCExceptions that do not occur locally. I am having no problems with dependency injection with my local machine.

```
Exception while executing function: Functions.HBA1C Result: Failure
Exception: System.InvalidOperationException: Unable to resolve service for type 'MediatR.IMediator' while attempting to activate 'CareInnovations.IHiS.HBA1C.Web.HbA1c'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker2.CreateInstance(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 26
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 27
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166
Stack:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker2.CreateInstance(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 26
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 27
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166 
```

Here's my config in Azure after a publish 

```
[
  {
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "value": "REMOVED",
    "slotSetting": false
  },
  {
    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
    "value": "REMOVED",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage",
    "value": "REMOVED",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~3",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "dotnet-isolated",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_RUN_FROM_PACKAGE",
    "value": "1",
    "slotSetting": false
  }
]
```

The app appears to be running, but any attempts to call the function fail. This is a Windows function.

Edit: Also Mediatr is on the server 
![image](https://user-images.githubusercontent.com/34655934/127044072-5e25d107-f3fa-49d3-8fc3-8d6f32f078ed.png)

**Comment by brandonh-msft** [comment]
I, too, am having issues though I'm able to run locallly. When I set up the Function App for Deployment from External Git (a GH repo) the deployment says it's succeeded

![image](https://user-images.githubusercontent.com/20270743/127048853-fa25ccc6-65fb-4baf-a9dd-c865e8c72f08.png)

but no Functions ever load (and no errors are shown in portal).

![image](https://user-images.githubusercontent.com/20270743/127048909-502233f3-28e7-4a3d-9430-f6c07247b732.png)

When I log into Kudu for the function app I can eventually get to logs which show:

```
[07/26/2021 19:43:45 > 099c13: SYS INFO] Run script 'Consumer.net5.exe' with script host - 'WindowsScriptHost'
[07/26/2021 19:43:45 > 099c13: SYS INFO] Status changed to Running
[07/26/2021 19:43:46 > 099c13: ERR ] Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
[07/26/2021 19:43:46 > 099c13: ERR ]    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
[07/26/2021 19:43:46 > 099c13: ERR ]    at System.Uri..ctor(String uriString)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.<>c.<AddGrpc>b__1_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 58
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Consumer.net5.Program.Main() in C:\home\site\repository\Consumer.net5\Program.cs:line 12
[07/26/2021 19:43:47 > 099c13: SYS ERR ] Job failed due to exit code -532462766
[07/26/2021 19:43:47 > 099c13: SYS INFO] Process went down, waiting for 60 seconds
[07/26/2021 19:43:47 > 099c13: SYS INFO] Status changed to PendingRestart
```

I, too, am using Dependency Injection for the `TelemetryConfiguration` object (due to #549)

If I then disconnect the External Git deployment from the Function App and use `func azure functionapp publish` _locally_, it succeeds and the Functions load in Azure without issue:

```
Uploading 6.95 MB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Functions in consumerzfk5ilpbbn6zu5:
    ClearDeadLetterServiceBusQueue - [TimerTrigger]

    EventGridProcessorAsync - [EventGridTrigger]

    EventHubProcessorAsync - [EventHubTrigger]

    ServiceBusQueueProcessorAsync - [ServiceBusTrigger]

    StorageQueueProcessorAsync - [QueueTrigger]
```

![image](https://user-images.githubusercontent.com/20270743/127050040-052998be-8e04-4929-9821-5c42d7fd882f.png)

The code I'm deploying can be found [here](https://github.com/Azure-Samples/durable-functions-producer-consumer/tree/main/Consumer.net5).

**Comment by alanokelly** [comment]
I don't think that the "554" is related. The error mentions an error parsing a URI, this is a DI issue

**Comment by brettsam** [comment]
@alanokelly -- would it be possible to give us a sample that repro's what you're seeing? That'd help us understand what's different between local and Azure.
