### ISSUE TITLE
'ExternalGit' deployments fail 

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-dotnet-worker#554]
I, too, am having issues though I'm able to run locallly. When I set up the Function App for Deployment from External Git (a GH repo) the deployment says it's succeeded

![image](https://user-images.githubusercontent.com/20270743/127048853-fa25ccc6-65fb-4baf-a9dd-c865e8c72f08.png)

but no Functions ever load (and no errors are shown in portal).

![image](https://user-images.githubusercontent.com/20270743/127048909-502233f3-28e7-4a3d-9430-f6c07247b732.png)

When I log into Kudu for the function app I can eventually get to logs which show:

```
[07/26/2021 19:43:45 > 099c13: SYS INFO] Run script 'Consumer.net5.exe' with script host - 'WindowsScriptHost'
[07/26/2021 19:43:45 > 099c13: SYS INFO] Status changed to Running
[07/26/2021 19:43:46 > 099c13: ERR ] Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
[07/26/2021 19:43:46 > 099c13: ERR ]    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
[07/26/2021 19:43:46 > 099c13: ERR ]    at System.Uri..ctor(String uriString)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.GrpcServiceCollectionExtensions.<>c.<AddGrpc>b__1_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcServiceCollectionExtensions.cs:line 58
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:46 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
[07/26/2021 19:43:47 > 099c13: ERR ]    at Consumer.net5.Program.Main() in C:\home\site\repository\Consumer.net5\Program.cs:line 12
[07/26/2021 19:43:47 > 099c13: SYS ERR ] Job failed due to exit code -532462766
[07/26/2021 19:43:47 > 099c13: SYS INFO] Process went down, waiting for 60 seconds
[07/26/2021 19:43:47 > 099c13: SYS INFO] Status changed to PendingRestart
```

I, too, am using Dependency Injection for the `TelemetryConfiguration` object (due to #549)

If I then disconnect the External Git deployment from the Function App and use `func azure functionapp publish` _locally_, it succeeds and the Functions load in Azure without issue:

```
Uploading 6.95 MB [###############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Functions in consumerzfk5ilpbbn6zu5:
    ClearDeadLetterServiceBusQueue - [TimerTrigger]

    EventGridProcessorAsync - [EventGridTrigger]

    EventHubProcessorAsync - [EventHubTrigger]

    ServiceBusQueueProcessorAsync - [ServiceBusTrigger]

    StorageQueueProcessorAsync - [QueueTrigger]
```

![image](https://user-images.githubusercontent.com/20270743/127050040-052998be-8e04-4929-9821-5c42d7fd882f.png)

The code I'm deploying can be found [here](https://github.com/Azure-Samples/durable-functions-producer-consumer/tree/main/Consumer.net5).

Possibly related to #553?

**Comment by alanokelly** [comment]
Huh, I'm the one that posted 553. Your message mentions "Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed." Which sounds like an event that occurs after DI is completed. It sounds like you have a bad URI being parsed. Not sure it's related.

**Comment by brandonh-msft** [comment]
> Huh, I'm the one that posted 553. Your message mentions "Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed." Which sounds like an event that occurs after DI is completed. It sounds like you have a bad URI being parsed. Not sure it's related.

No URIs to be parsed in my setup and it works perfectly w/ the same code deployed  via `func azure functionapp publish` from my local machine.

Additionally, on the Portal when I "Show Logs" for the deployment from Git it doesn't appear to have any problems:

```shell
Command: "C:\home\site\deployments\tools\deploy.cmd"
Handling .NET Console Application deployment with MSBuild16.7.0.
Determining projects to restore...
Restored C:\home\site\repository\Consumer.net5\Consumer.net5.csproj (in 1.08 min).
CSC : warning CS8032: An instance of analyzer Microsoft.Azure.Functions.Worker.Sdk.Analyzers.WebJobsAttributesNotSupported cannot be created from C:\home\.nuget\microsoft.azure.functions.worker.sdk.analyzers\1.0.0\analyzers\dotnet\cs\Microsoft.Azure.Functions.Worker.Sdk.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. [C:\home\site\repository\Consumer.net5\Consumer.net5.csproj]
Consumer.net5 -> C:\local\Temp\8d95071bc166005\app_data\jobs\continuous\deployedJob\Consumer.net5.dll
Determining projects to restore...
Restored C:\local\Temp\wi3aptfw.ope\WorkerExtensions.csproj (in 1.31 min).
WorkerExtensions -> C:\local\Temp\wi3aptfw.ope\buildout\Microsoft.Azure.Functions.Worker.Extensions.dll
1 file(s) copied.
Creating app_offline.htm
KuduSync.NET from: 'C:\local\Temp\8d95071bc166005' to: 'C:\home\site\wwwroot'
Copying file: 'hostingstart.html'
Copying file: 'app_data\jobs\continuous\deployedJob\Azure.Core.Amqp.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Azure.Core.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Azure.Messaging.EventGrid.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Azure.Messaging.ServiceBus.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Consumer.net5.deps.json'
Copying file: 'app_data\jobs\continuous\deployedJob\Consumer.net5.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Consumer.net5.exe'
Copying file: 'app_data\jobs\continuous\deployedJob\Consumer.net5.pdb'
Copying file: 'app_data\jobs\continuous\deployedJob\Consumer.net5.runtimeconfig.dev.json'
Copying file: 'app_data\jobs\continuous\deployedJob\Consumer.net5.runtimeconfig.json'
Copying file: 'app_data\jobs\continuous\deployedJob\extensions.json'
Copying file: 'app_data\jobs\continuous\deployedJob\functions.metadata'
Copying file: 'app_data\jobs\continuous\deployedJob\Google.Protobuf.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Grpc.Core.Api.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Grpc.Net.Client.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Grpc.Net.ClientFactory.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Grpc.Net.Common.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\host.json'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.ApplicationInsights.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Amqp.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.Core.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.Extensions.Abstractions.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.Extensions.EventGrid.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.Extensions.EventHubs.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.Extensions.ServiceBus.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.Extensions.Storage.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.Extensions.Timer.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Azure.Functions.Worker.Grpc.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Bcl.AsyncInterfaces.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Configuration.Abstractions.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Configuration.Binder.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Configuration.CommandLine.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Configuration.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Configuration.EnvironmentVariables.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Configuration.FileExtensions.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Configuration.Json.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Configuration.UserSecrets.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.DependencyInjection.Abstractions.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.DependencyInjection.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.FileProviders.Abstractions.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.FileProviders.Physical.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.FileSystemGlobbing.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Hosting.Abstractions.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Hosting.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Http.dll'
Copying file: 'app_data\jobs\continuous\deployedJob\Microsoft.Extensions.Logging.Abstractions.dll'
Omitting next output lines...
Finished successfully.
```

**Comment by anthonychu** [comment]
@ahmelsayed Is this a problem with the kudu build script not working with .NET isolated projects?

**Comment by brettsam** [comment]
I'm going to close this as stale... at first glance it seems to be related to Grpc options being passed in as the worker is starting. If anyone is able to repro this, feel free to re-open and ping me.
