### ISSUE TITLE
Grpc error with .NET 5 Function on Linux with VNet Integration

### ISSUE THREAD

**Issue by PoyaManouchehri** [Azure/azure-functions-dotnet-worker#640]
I'm running into an issue that was reported a little while ago but closed without a resolution:

https://github.com/Azure/azure-functions-dotnet-worker/issues/518

The stack is nearly identical:

```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:80) SocketException: Connection refused
---> System.Net.Sockets.SocketException (111): Connection refused
at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at Embrayse.Integrations.Functions.Program.Main() in /home/vsts/work/1/s/src/Embrayse.Integrations.Functions/Program.cs:line 18
at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at Microsoft.Azure.Functions.Worker.WorkerHostedService.StartAsync(CancellationToken cancellationToken) in D:\a\1\s\src\DotNetWorker.Core\WorkerHostedService.cs:line 25
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
```

As the title suggests, the issue happens on a Linux service plan with VNet Integration enabled. I know there was a suggestion to use a Windows ASP, but the cost of running a dedicated ASP for this is prohibitive for us. Is there a fix in the works for it? Or should I be looking for a different workaround?

Thanks

**Comment by fabiocav** [comment]
Can you share the version of the SDK you're using? If not the latest, can you please upgrade and retry? Thanks!

**Comment by PoyaManouchehri** [comment]
> Can you share the version of the SDK you're using? If not the latest, can you please upgrade and retry? Thanks!

I'm on version 1.5.1 which I understand is the latest
