### ISSUE TITLE
SignalR Output Binding with AAD authentication

### ISSUE THREAD

**Issue by c0dybrown** [Azure/azure-functions-dotnet-worker#803]
Hello,

I am trying to create a SignalR output binding using the connection string
`Endpoint=https://{signalrName}.service.signalr.net;AuthType=aad;ClientId={};Version=1.0;`
https://docs.microsoft.com/en-us/azure/service-connector/how-to-integrate-signalr

The error I get is

```
System.ArgumentException: Connection string missing required properties endpoint and accesskey. (Parameter 'connectionString')
   at Microsoft.Azure.SignalR.ConnectionStringParser.Parse(String connectionString)
   at Microsoft.Azure.SignalR.Management.ServiceManagerBuilder.Build()
   at Microsoft.Azure.WebJobs.Extensions.SignalRService.ServiceManagerStore.CreateHubContextStore(String connectionString)
   at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
   at Microsoft.Azure.WebJobs.Extensions.SignalRService.AzureSignalRClient.SendToUser(String userId, SignalRData data)
   at Microsoft.Azure.WebJobs.Extensions.SignalRService.SignalRAsyncCollector1.AddAsync(T item, CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.BindAsyncCollectorAsync[T](BindingContext context) in /_/src/WebJobs.Script/Binding/FunctionBinding.cs:line 199
   at Microsoft.Azure.WebJobs.Script.Binding.ExtensionBinding.BindAsync(BindingContext context) in /_/src/WebJobs.Script/Binding/ExtensionBinding.cs:line 84
   at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.<>c__DisplayClass13_0.<<BindOutputsAsync>b__0>d.MoveNext() in /_/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 170
```

Here's an example of the code:

```
[Function(nameof(MakeFilePublic))]
[SignalROutput(HubName = nameof(EventHub))]
public async Task<SignalRMessage> Run([ServiceBusTrigger("make-file-public")] string input)
{
    ....
    return new SignalRMessage
    {
        UserId = upload.UserId,
        Target = "makeFilePublicComplete",
        Arguments = new object[]
        {
            newBlobName
        }
    };
}
```
Is is possible to use this model? I would like to go completely passwordless. Thanks a lot

**Comment by Y-Sindo** [comment]
AAD authentication does not apply to isolated worker yet. It will be available in the next release.

**Comment by fabiocav** [comment]
Thank you @Y-Sindo 

@c0dybrown closing this as answered, but please let us know if you need any additional information.
