### ISSUE TITLE
.NET6 isolated function on Windows fails

### ISSUE THREAD

**Issue by msft-mw** [Azure/azure-functions-dotnet-worker#845]
I have a pair of functions in a .net 6.0 v4 project. When running locally they both work as expected - one is a queue trigger and the other is a timer trigger. But when I zip deploy to a function app in Azure, ~only the queue triggered function works. The timer triggered function fails immediately with the following error:~

EDIT: on further investigation, it doesn't appear that the queue function was working either. I'm starting to think that it's something about the configuration of the app itself.

```
Type : System.InvalidOperationException
Total Count : 9
Message : Did not find any initialized language workers
```

The full callstack is here:

```csharp
Full Exception :
 Exception while executing function: Functions.PcfReader ---> System.InvalidOperationException : Did not find any initialized language workers
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels) at /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs : 27
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) at /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 389
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at /_/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs : 95
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at /_/src/WebJobs.Script/Description/FunctionInvokerBase.cs : 82
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync[TReflected,TReturnType](TReflected instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs : 20
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 596
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 542
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 320
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 367
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 108
```

I can provide the function name and subscription details privately if necessary, thank you.

**Comment by msft-mw** [comment]
Adding some more context about the app configuration:

![image](https://user-images.githubusercontent.com/23460969/161300662-ba7ab692-9e05-48fe-a38d-448bf9739ecf.png)

`FUNCTIONS_EXTENSION_VERSION` is set to `~4`
`FUNCTIONS_WORKER_RUNTIME` is set to `dotnet-isolated`

The project configuration is set to net6:

```xml
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
</PropertyGroup>
```

But when I look at the functions in the portal, I see this warning banner: (`Editing .NET 5 Function Apps is not supported in the Azure portal. Use your local development environment to edit this Function App.`)

![image](https://user-images.githubusercontent.com/23460969/161301150-467220bc-a8d3-47d8-84ac-4b0172200141.png)

I'm internal so happy to share source or more details privately.

**Comment by msft-mw** [comment]
Additional information from Kudu logs:

```
2022-04-01T18:45:31.796 [Information] It was not possible to find any compatible framework version
2022-04-01T18:45:31.796 [Information] The framework 'Microsoft.NETCore.App', version '6.0.3' (x64) was not found.
2022-04-01T18:45:31.796 [Information] - The following frameworks were found:
2022-04-01T18:45:31.797 [Information] 2.2.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2022-04-01T18:45:31.797 [Information] 3.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2022-04-01T18:45:31.797 [Information] 3.1.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2022-04-01T18:45:31.797 [Information] 3.1.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2022-04-01T18:45:31.797 [Information] 5.0.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2022-04-01T18:45:31.797 [Information] 5.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2022-04-01T18:45:31.797 [Information] 6.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2022-04-01T18:45:31.797 [Information] 6.0.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2022-04-01T18:45:31.798 [Information] You can resolve the problem by installing the specified framework and/or SDK.
2022-04-01T18:45:31.798 [Information] The specified framework can be found at:
2022-04-01T18:45:31.798 [Information] - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.3&arch=x64&rid=win10-x64
2022-04-01T18:45:31.802 [Debug] Handling WorkerErrorEvent for runtime:dotnet-isolated, workerId:dotnet-isolated. Failed with: Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException: C:\Program Files\dotnet\dotnet.exe exited with code -2147450730
2022-04-01T18:45:31.802 [Debug] Attempting to dispose webhost or jobhost channel for workerId: 'd3ba9d55-3761-4121-b652-9e28048b778f', runtime: 'dotnet-isolated'
2022-04-01T18:45:31.803 [Debug] Disposing JobHost language worker channel with id:d3ba9d55-3761-4121-b652-9e28048b778f
2022-04-01T18:45:31.804 [Debug] No initialized worker channels for runtime 'dotnet-isolated'. Delaying future invocations
```

**Comment by msft-mw** [comment]
This turned out to be an issues with indirectly referenced old packages, configuration, and the publishing profile, all of which were only discoverable in the Kudu logs. The issue can be considered resolved, but some information from the team about **if or how the issue could've been seen in the portal would be very helpful for future readers.**

**Issue 1: It was not possible to find any compatible framework version**
This was caused by Visual Studio's default publishing profile having a `Deployment mode` setting of `Framework-dependent`.

**Resolution**
Changing the deployment mode in the publishing profile to `Self-contained`

**Issue 2: Did not find any initialized language workers**
This ended up being a combination of two things:
- a configuration setting was missing that instructed the `AzureServiceTokenProvider` to use the user-assigned identity
- the Azure Key Vault configuration extension package `Microsoft.Extensions.Configuration.AzureKeyVault` pulled in an older version of `Microsoft.Azure.Services.AppAuthentication` (1.0.3) which did not support the documented connection string.

**Resolution**
Adding the configuration string and then explicitly (rather than indirectly) referencing the most recent version of `Microsoft.Azure.Services.AppAuthentication`

There is a newer library for Key Vault integration but we haven't had time to investigate usage at this time, or compatibility with functions.

**Comment by fabiocav** [comment]
Thank you for the update. 

Do you have a repro you could share with us? I don't want to close this as resolved as I believe there are enhancements we can make that would, at least, make this simpler to diagnose, so we would like to validate the scenario.

Thanks!

**Comment by msft-mw** [comment]
Yes I think so. The repro for issue 2 should be trivial, but issue 1 might be harder. Let me look into this a bit and get back to you.

**Comment by msft-mw** [comment]
[repro.zip](https://github.com/Azure/azure-functions-dotnet-worker/files/8484410/repro.zip)

## Repro instructions
1. Download and unzip the attached respro code.
2. Create a function app with the following settings: 
    - `net6.0`
    - `v4`
    - `dotnet-isolated`
    - `windows`
3. Create a user managed identity and assign it to the function. The function _should not_ have a system assigned identity enabled, only the user managed identity.
4. Create a new key vault instance with RBAC-based access control.
5. Assign the user identity from step 3 using the `Key Vault Reader` role.
6. In the `Program.cs`, replace the `AppId` in the string on L28 with the `Client Id` from the user managed identity in step 3.
7. On line 32, replace the first parameter with the URL of the key vault created in step 5.
8. Publish the function to the function app using the following settings (I did this from Visual Studio 2022):
    - Configuration: `Release|AnyCPU`
    - Target framework: `net6.0`
    - Deployment mode: `Framework-dependent`
    - Target runtime: `win-x64`

9. Once the function starts up, it should start failing immediately. In Application Insights, `System.InvalidOperation` exceptions should start showing up with the message __Exception while executing function: Functions.Repro Did not find any initialized language workers__


10. Going to the Kudu debug console and navigating to the logs under `C:\home\LogFiles\Application\Functions\Host` will show the error:

    ```2022-04-13T19:54:21.317 [Information] It was not possible to find any compatible framework version
    2022-04-13T19:54:21.318 [Information] The framework 'Microsoft.NETCore.App', version '6.0.4' (x64) was not found.
    2022-04-13T19:54:21.318 [Information] - The following frameworks were found:
    2022-04-13T19:54:21.318 [Information] 2.2.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    2022-04-13T19:54:21.318 [Information] 3.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    2022-04-13T19:54:21.318 [Information] 3.1.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    2022-04-13T19:54:21.319 [Information] 3.1.23 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    2022-04-13T19:54:21.319 [Information] 5.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    2022-04-13T19:54:21.319 [Information] 5.0.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    2022-04-13T19:54:21.319 [Information] 6.0.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    2022-04-13T19:54:21.319 [Information] 6.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    ```

    __Observation__: The framework error only started appearing once I added the key vault extensions nuget package. Prior to that, the function actually ran as expected.

11. From the publish profile, change the `Deployment mode` setting to `Self-contained` and republish the function.
12. Identical errors will appear in Application Insights as in step 10.

13. Again going to the logs from the Kudu debug console, the error changes to:

    ```
    2022-04-13T20:04:25.536 [Information] Unhandled exception. System.ArgumentException: Connection string RunAs=App;AppId=REDACTED is not valid. Must contain 'TenantId' attribute and it must not be empty.
    2022-04-13T20:04:25.537 [Information] at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.ValidateAttribute(Dictionary`2 connectionSettings, String attribute, String connectionString)
    2022-04-13T20:04:25.538 [Information] at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.Create(String connectionString, String azureAdInstance)
    2022-04-13T20:04:25.538 [Information] at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider..ctor(String connectionString, String azureAdInstance)
    2022-04-13T20:04:25.538 [Information] at NoLanguageRepro.Program.<>c.<Main>b__0_0(HostBuilderContext _, IConfigurationBuilder c) in C:\Users\mwan\Documents\Visual Studio 2022\Projects\NoLanguageRepro\NoLanguageRepro\Program.cs:line 28
    2022-04-13T20:04:25.538 [Information] at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
    2022-04-13T20:04:25.538 [Information] at Microsoft.Extensions.Hosting.HostBuilder.Build()
    2022-04-13T20:04:25.539 [Information] at NoLanguageRepro.Program.Main() in C:\Users\mwan\Documents\Visual Studio 2022\Projects\NoLanguageRepro\NoLanguageRepro\Program.cs:line 23
    ```

**Comment by fabiocav** [comment]
Thank you for sharing the details. Out of curiosity, did you have App Insights enabled for your functions? Did that provide any helpful information?

**Comment by msft-mw** [comment]
Hi fabiocav, App Insights was enabled and the callstack in the first post of this issue was gathered from App Insights, but that's the extent of the information that it provided.

**Comment by jamyc** [comment]
@fabiocav same issue for us. Previously had consistent failures as seen in #556, but now they're very sporadic.
Out of the 2.39M executions in the past 7 days, we've had 25 failures with this `System.InvalidOperationException`.

Setup:
Operating system: `Windows`
App Service Plan: `Consumption`
Runetime version: `4.3.0.17971`
WindowsFxVersion: `DOTNET-ISOLATED|6.0`
FUNCTIONS_EXTENSION_VERSION: `~4`
FUNCTIONS_WORKER_RUNTIME: `dotnet-isolated`


Some of the last failures:
| TimeStamp                    | HostInstanceId                       | InvocationId                         |
|------------------------------|--------------------------------------|--------------------------------------|
| 2022-05-04T03:08:51.7136251Z | 7905fbb2-2990-4be3-bd92-637f9fbec107 | 555e86e8-18fb-43ee-b531-7aa7d0aec85e |
| 2022-05-03T23:25:47.7138427Z | 42fc5291-bed1-4bd0-969d-ff99e655bd45 | 8b658cd6-5540-4a74-bb91-34561f13ef64 |
| 2022-05-03T21:14:26.3257034Z | 0da286ef-7dd0-4012-80da-342b955ceefb | c9f27a64-87a9-45c2-a615-996c9eb0d6fb |
| 2022-05-03T18:12:53.1972301Z | d5274b13-889f-4fc7-ac68-0638be71c685 | abb306f4-258b-40dc-a621-675e8e8fcb62 |
| 2022-05-03T12:17:45.9711337Z | c0ec5404-4d10-4d86-adb4-b6e2453ce6bb | ca70c77e-8632-462c-a137-47b1c0a70c12 |
| 2022-05-03T07:52:16.7465396Z | 8868955c-ddf3-476f-af04-3ccd919d603d | 42758bc9-f4d8-40a1-8239-56c0747dfee7 |
| 2022-05-03T06:12:21.7960034Z | 447c6e5d-db93-4946-bafe-69418e21b729 | b3f7cb8c-c238-4b15-971b-3718dcf7d494 |

Taking the last one of this list shows the following in App Insights (timestamps in UTC+2)
![image](https://user-images.githubusercontent.com/6288420/166720807-1fec74b9-b656-4992-944e-284775c335fc.png)

With this stacktrace:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:353)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__18.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:108)
Inner exception System.InvalidOperationException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel (Microsoft.Azure.WebJobs.Script, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:27)
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher+<InvokeAsync>d__59.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:393)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker+<InvokeCore>d__9.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:95)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase+<Invoke>d__24.MoveNext (Microsoft.Azure.WebJobs.Script, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null: /_/src/WebJobs.Script/Description/FunctionInvokerBase.cs:82)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2+<InvokeAsync>d__2.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:20)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2+<InvokeAsync>d__10.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:52)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeWithTimeoutAsync>d__33.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:582)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__32.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:528)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:307)
```

Can somebody look at this? We're not sure what's causing this.

**Comment by Yashuaa** [comment]
any update on this?

**Comment by jviau** [comment]
@msft-mw is this issue still occurring? We have made several improvements to the functions host, want to see if it has addressed your issue.
