### ISSUE TITLE
Sample function HttpTriggerWithBlobInput doesn't work

### ISSUE THREAD

**Issue by madelinegordon** [Azure/azure-functions-dotnet-worker#889]
The sample function HttpTriggerWithBlobInput doesn't work when running locally - throws the following exception:

` System.Private.CoreLib: Exception while executing function: Functions.HttpTriggerWithBlobInput. System.Private.CoreLib: Result: Failure
Exception: System.ArgumentNullException: Value cannot be null. (Parameter 'json')
[2022-05-11T23:27:02.085Z]    at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
[2022-05-11T23:27:02.088Z]    at FunctionApp.HttpTriggerWithBlobInput.Run(HttpRequestData req, String myBlob, FunctionContext context) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\samples\FunctionApp\HttpTriggerWithBlobInput\HttpTriggerWithBlobInput.cs:line 18
[2022-05-11T23:27:02.091Z]    at lambda_method1(Closure , HttpTriggerWithBlobInput , Object[] )
[2022-05-11T23:27:02.093Z]    at Microsoft.Azure.Functions.Worker.Invocation.MethodInvokerWithReturnValue`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Core\Invocation\MethodInvokerWithReturnValue.cs:line 22
[2022-05-11T23:27:02.098Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2022-05-11T23:27:02.101Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2022-05-11T23:27:02.104Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2022-05-11T23:27:02.106Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Grpc\GrpcWorker.cs:line 178
Stack:    at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
[2022-05-11T23:27:02.108Z]    at FunctionApp.HttpTriggerWithBlobInput.Run(HttpRequestData req, String myBlob, FunctionContext context) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\samples\FunctionApp\HttpTriggerWithBlobInput\HttpTriggerWithBlobInput.cs:line 18
[2022-05-11T23:27:02.113Z]    at lambda_method1(Closure , HttpTriggerWithBlobInput , Object[] )
[2022-05-11T23:27:02.115Z]    at Microsoft.Azure.Functions.Worker.Invocation.MethodInvokerWithReturnValue`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Core\Invocation\MethodInvokerWithReturnValue.cs:line 22
[2022-05-11T23:27:02.118Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31
[2022-05-11T23:27:02.120Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2022-05-11T23:27:02.122Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2022-05-11T23:27:02.124Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in C:\Users\magordon\repos\v4\azure-functions-dotnet-worker\src\DotNetWorker.Grpc\GrpcWorker.cs:line 178.
`

**Comment by madelinegordon** [comment]
Needed to verify local AzureWebJobsStorage setting. Not a bug.
