### ISSUE TITLE
Repeated Failure to Start DOTNET-ISOLATED|6.0 Function

### ISSUE THREAD

**Issue by Kyelin25** [Azure/azure-functions-dotnet-worker#908]
Hi,

My Linux-hosted DOTNET-ISOLATED|6.0 triggered function is constantly restarting and will not run. I've checked the logs of various containers and have several interesting-looking yet ultimately useless exceptions and warnings.

These all repeat roughly every 5 minutes.

# In the function's host logs
`2022-05-20T01:11:37.977 [Error] Failed to start a new language worker for runtime: dotnet-isolated.
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at async Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) at /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs : 155
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(??) at /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 119
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(??) at /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 112
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.<>c__DisplayClass53_0.<StartWorkerProcesses>b__0(??) at /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 183
2022-05-20T01:11:49.334 [Error] Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recover
2022-05-20T01:16:30.602 [Error] Failed to start a new language worker for runtime: dotnet-isolated.
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at async Microsoft.Azure.WebJobs.Script.Grpc.GrpcWorkerChannel.StartWorkerProcessAsync(CancellationToken cancellationToken) at /src/azure-functions-host/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs : 155
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(??) at /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 119
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InitializeJobhostLanguageWorkerChannelAsync(??) at /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 112
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.<>c__DisplayClass53_0.<StartWorkerProcesses>b__0(??) at /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs : 183`

# In the docker log

`2022-05-20T01:31:37.609Z INFO  - Pulling image: mcr.microsoft.com/appsvc/middleware:stage5
2022-05-20T01:31:38.024Z INFO  - stage5 Pulling from appsvc/middleware
2022-05-20T01:31:38.031Z INFO  -  Digest: sha256:3aaa88af0761bb1882bbab9e262c645a38fd79de15141a6dda2cd38b4148d5f6
2022-05-20T01:31:38.032Z INFO  -  Status: Image is up to date for mcr.microsoft.com/appsvc/middleware:stage5
2022-05-20T01:31:38.037Z INFO  - Pull Image successful, Time taken: 0 Minutes and 0 Seconds
2022-05-20T01:31:38.078Z INFO  - Starting container for site
2022-05-20T01:31:38.088Z INFO  - docker run -d -p 2220:8181 -p 2763:8082 --name func-bwt-account-dev-ause_0_42c145b6_middleware -e WEBSITE_CORS_ALLOWED_ORIGINS=https://portal.azure.com -e WEBSITE_CORS_SUPPORT_CREDENTIALS=False -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=true -e WEBSITE_SITE_NAME=func-bwt-account-dev-ause -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=func-bwt-account-dev-ause.azurewebsites.net -e WEBSITE_INSTANCE_ID=9d0e1242a0dd8a20ab84c7e58df8f965a5d4bf8ec42752ae1b828b02f289ee06 -e HTTP_LOGGING_ENABLED=1 -e WEBSITE_USE_DIAGNOSTIC_SERVER=False mcr.microsoft.com/appsvc/middleware:stage5 /Host.ListenUrl=http://0.0.0.0:8181 /Host.DestinationHostUrl=http://172.16.0.4:80 /Host.UseFileLogging=true 

isolated:4-dotnet-isolated6.0-appservice-stage5  

2022-05-20T01:31:41.448Z INFO  - Initiating warmup request to container func-bwt-account-dev-ause_0_42c145b6_msiProxy for site func-bwt-account-dev-ause
2022-05-20T01:31:41.483Z INFO  - Container func-bwt-account-dev-ause_0_42c145b6_msiProxy for site func-bwt-account-dev-ause initialized successfully and is ready to serve requests.
2022-05-20T01:31:41.485Z INFO  - Initiating warmup request to container func-bwt-account-dev-ause_0_42c145b6 for site func-bwt-account-dev-ause
2022-05-20T01:31:46.369Z INFO  - Container func-bwt-account-dev-ause_0_42c145b6 for site func-bwt-account-dev-ause initialized successfully and is ready to serve requests.
2022-05-20T01:31:46.371Z INFO  - Initiating warmup request to container func-bwt-account-dev-ause_0_42c145b6_middleware for site func-bwt-account-dev-ause
2022-05-20T01:31:47.408Z INFO  - Container func-bwt-account-dev-ause_0_42c145b6_middleware for site func-bwt-account-dev-ause initialized successfully and is ready to serve requests.
2022-05-20T01:32:22.698Z ERROR - Container for func-bwt-account-dev-ause_0_42c145b6 site func-bwt-account-dev-ause is unhealthy, Stopping site.
2022-05-20T01:32:22.700Z INFO  - Stopping site func-bwt-account-dev-ause because it is not healthy.`

# In the easyauth logs

`2022-05-20T01:02:26.919233764Z [40m[1m[33mwarn[39m[22m[49m: Middleware[0]
2022-05-20T01:02:26.919298964Z       At least one of http20OnlyDestinationHostUrl and http20OnlyListenUrl not provided`

**Comment by Kyelin25** [comment]
Closing this as I finally determined the issue (entirely my own fault and specific to my application), although the logs were of no help, so I would be interested in any pointers towards better methods for doing so.
